### ISSUE TITLE
Move blog frontend editing feature into it's own module

### ISSUE THREAD

**Issue by camfindlay** [silverstripe/silverstripe-blog#118]
I also find this is never used on most projects I use this module for.

Suggest that any frontend ability to edit or create a blog post should be moved out into it's own module. Gives the developer a choice to include the extra features if they really need them.

**Comment by dhensby** [comment]
At first I was sceptical, but yes, I think this should be decoupled, that'd give the opportunity to allow greater integration to other modules, not just the Blog

**Comment by chillu** [comment]
+1 for decoupling into a module, particularly since it adds unnecessary "security surface" to the module

**Comment by mlewis-everley** [comment]
If it was possible to extend the new module so that it could be used to edit other page types too (as @dhensby suggests) then that would actually be really good.

It would also be REALLY nice if the module also allowed dev to fairly easily update the edit form (via an extension call or something similar) :-).

**Comment by micmania1** [comment]
I've changed this to 2.0.

Front-end editing no longer exists in 2.0 but would make a good module.

**Comment by camfindlay** [comment]
:+1:

**Comment by gordonbanderson** [comment]
I'm guessing nobody has written this module yet?

**Comment by micmania1** [comment]
@gordonbanderson not to my knowledge.

**Comment by tractorcow** [comment]
Can we close feature requests on supported modules? we don't allow them on core, and I'm not sure we should on modules either.

**Comment by camfindlay** [comment]
I think we should be able to allow feature requests on github issues since we want to keep them in content of the module (core refers to a collection of modules so a single place like uservoice is better).

**Comment by camfindlay** [comment]
Just for modules though.

**Comment by micmania1** [comment]
I'm going to close this for now. I think feature requests are fine but should be closed where nobody picks up the task to work on it (ie. as is the case here).

People can still find this on Google and i'd be happy to re-open and assign somebody if they were to take it over.
