### ISSUE TITLE
Blog module can't validate date and time.

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-blog#12]
Copied from http://open.silverstripe.org/ticket/3479

When the blog module is installed under SilverStripe? 2.3rc3, entering anything other than date in DD/MM/YYYY, causes Validation to fail, with a "Please enter a valid date format (DD/MM/YYYY)." message.

Previous versions of SilverStripe? allowed the date and time to be entered, useful if you have 2 entries in one day.

**Comment by camfindlay** [comment]
@tractorcow I think close
