### ISSUE TITLE
Entries() should allow tags to be arrays

### ISSUE THREAD

**Issue by SilbinaryWolf** [silverstripe/silverstripe-blog#120]
On Line 168 of BlogTree.php, Tags should have the the ability to be arrays so that BlogEntry items that fit multiple tag parameters can be returned.

public function Entries($limit = '', $tag = '', $date = '', $retrieveCallback = null, $filter = '') 

		$tagCheck = '';
		$dateCheck = '';
		
		if($tag) {
			// Start change 
			if (!is_array($tag))
			{
				$SQL_tag = Convert::raw2sql($tag);
				$tagCheck = "AND \"BlogEntry\".\"Tags\" LIKE '%$SQL_tag%'";
			}
			else
			{
				$tagCheck = "AND (";
				$tagOr = "";
				foreach ($tag as $t)
				{
					$SQL_tag = Convert::raw2sql($t);
					$tagCheck .= $tagOr . "\"BlogEntry\".\"Tags\" LIKE '%$SQL_tag%'";
					$tagOr = " OR ";
				}

				$tagCheck .= ")";
			}
			// End change 
		}

		if($date) {
			// Some systems still use the / seperator for date presentation
			if( strpos($date, '-') ) $seperator = '-';
			elseif( strpos($date, '/') ) $seperator = '/';
			
			if(isset($seperator) && !empty($seperator)) {
				// The 2 in the explode argument will tell it to only create 2 elements
				// i.e. in this instance the $year and $month fields respectively
				list($year,$month) = explode( $seperator, $date, 2);
				
				$year = (int)$year;
				$month = (int)$month;

				if($year && $month) {
					if(method_exists(DB::getConn(), 'formattedDatetimeClause')) {
						$db_date=DB::getConn()->formattedDatetimeClause('"BlogEntry"."Date"', '%m');
						$dateCheck = "AND CAST($db_date AS " . DB::getConn()->dbDataType('unsigned integer') . ") = $month AND " . DB::getConn()->formattedDatetimeClause('"BlogEntry"."Date"', '%Y') . " = '$year'";
					} else {
						$dateCheck = "AND MONTH(\"BlogEntry\".\"Date\") = '$month' AND YEAR(\"BlogEntry\".\"Date\") = '$year'";
					}
				}
			} else {
				$year = (int) $date;
				if($year) {
					if(method_exists(DB::getConn(), 'formattedDatetimeClause')) {
						$dateCheck = "AND " . DB::getConn()->formattedDatetimeClause('"BlogEntry"."Date"', '%Y') . " = '$year'";
					} else {
						$dateCheck = "AND YEAR(\"BlogEntry\".\"Date\") = '$year'";
					}
				}
			}
		}

		// Build a list of all IDs for BlogHolders that are children of us
		$holderIDs = $this->BlogHolderIDs();
		
		// If no BlogHolders, no BlogEntries. So return false
		if(empty($holderIDs)) return false;
		
		// Otherwise, do the actual query
		if($filter) $filter .= ' AND ';
		$filter .= '"SiteTree"."ParentID" IN (' . implode(',', $holderIDs) . ") $tagCheck $dateCheck";

		$order = '"BlogEntry"."Date" DESC';

		// By specifying a callback, you can alter the SQL, or sort on something other than date.
		if($retrieveCallback) return call_user_func($retrieveCallback, 'BlogEntry', $filter, $limit, $order);

		$entries = BlogEntry::get()->where($filter)->sort($order);

    	$list = new PaginatedList($entries, Controller::curr()->request);
    	$list->setPageLength($limit);
    	return $list;

/**
	 * Return the currently viewing tag used in the template as $Tag 
	 *
	 * Modified to allow for multiple tags in the address
	 *
	 * @return array
	 */
	public function SelectedTag() 

		if ($this->request->latestParam('Action') == 'tag') {
			// Start change 
			$tags = explode(',', $this->request->latestParam('ID'));
			foreach ($tags as &$tag)
			{
				$tag = urldecode($tag);
			}
			return $tags;
			// End Change
		}
		return '';

**Comment by assertchris** [comment]
@tractorcow / @cam-findlay: is this still an issue?

**Comment by tractorcow** [comment]
This feature is no longer relevant to the current version of blog. If you want to submit a PR to the older 1.0 branch then we'll have a look at it then.
