### ISSUE TITLE
Extend BlogEntries function in BlogTree class

### ISSUE THREAD

**Issue by nonconformatevi** [silverstripe/silverstripe-blog#125]
Can you insert a $this->extend() in BlogEntries function in order to be able to extend it in a module?

**Comment by assertchris** [comment]
@nonconformatevi sorry it's taken so long to get back to you. Is this still something you're looking to do?

**Comment by micmania1** [comment]
No response in almost a year so i'm closing. Feel free to submit a PR if this is something you're still looking for.
