### ISSUE TITLE
No entries found with tag filter and PostgreSQL module

### ISSUE THREAD

**Issue by witschko** [silverstripe/silverstripe-blog#137]
Hi everyone!

I'm using silverstripe and the blog module together with the postgresql module. It seems that entries are not always listed when filtering for tags.

For filtering the LIKE operator is used ([see here](https://github.com/silverstripe/silverstripe-blog/blob/master/code/BlogTree.php#L171)). But the PostgreSQL LIKE operator is case sensitive and so a tag with an uppercase letter won't be matched. The ILIKE operator should be used here.

I'm not sure if this is blog module or postgresql module related. I just wanted to give a hint.

Thanks,
Philipp

**Comment by micmania1** [comment]
No input for over s a year so closing. Please feel free to submit a PR against 1.x if you still need this fixed.
