### ISSUE TITLE
TrackbackPings as PageComments

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-blog#14]
Copied from http://open.silverstripe.org/ticket/5747

At the moment TrackbackPing? is a DataObject? as its own. This means that it needs its own template and it lacks of spam management (marked as spam or ham). From user interface point of it, they're separate from page comment list which in fact they should be treated as page comment.

By treating them as page comments, we can benefit from unified interface and we don't have make a duplicate effort to implement the spam management.

**Comment by assertchris** [comment]
@sminnee ping
