### ISSUE TITLE
forward slash in Tags breaks link

### ISSUE THREAD

**Issue by stevevu** [silverstripe/silverstripe-blog#141]
Hi,  

If I have have a forward slash in my blog tags, clicking on these tags returns a 404 page.  For example, on http://www.guidewire.com/blog/general-interest/, the third entry down has tags with slashes such as ‘property/casualty’ and ‘P/C’ and if you click on any of these tags, a 404 will result.

thanks,
Steve

**Comment by assertchris** [comment]
@stevevu sorry it's taken so long to respond. Are you still seeing this issue with `dev-master`?

**Comment by assertchris** [comment]
This is no longer an issue in `dev-master`.
