### ISSUE TITLE
Could not load package silverstripe/blog

### ISSUE THREAD

**Issue by MichaelCSLWeb** [silverstripe/silverstripe-blog#143]
Hi when using composer to install the module im getting an error 

 [RuntimeException]                                                           
 Could not load package silverstripe/blog in http://packagist.org: [UnexpectedValueException] Could not  parse version constraint ^3.1.0: Invalid version string "^3.1.0"

  [UnexpectedValueException]                                                  
  Could not parse version constraint ^3.1.0: Invalid version string "^3.1.0"

**Comment by phillprice** [comment]
The core modules are 3.1.9

**Comment by kinglozzer** [comment]
The `^` syntax is reasonably new I think, have you tried `composer self-update`?

**Comment by MichaelCSLWeb** [comment]
That fixed the issue thanks for your help
