### ISSUE TITLE
Freeform tags in develop branch?

### ISSUE THREAD

**Issue by mlewis-everley** [silverstripe/silverstripe-blog#149]
So I have been using the new development of the blog module and it is all great. But should a blog post be mapped to tags as a many_many?

I have always seen Categories as something you defined ridgedly (via a many_many) and tags as freeform input that can be added to on the fly as the user types. I think this is also quite common functionality for services like Blogger and Wordpress?

So I thought it might be worth raising this as a question now, should the new blog module use tags mapped via a many_many? Or should it use them in a way similar to the current blog module?

**Comment by tractorcow** [comment]
We're going to fix tags so you can easily add new ones. :)

**Comment by assertchris** [comment]
@mlewis-everley tags (and categories) are super easy to add in the new version. Check out `dev-master` for a sneak-peek!
