### ISSUE TITLE
RFC Editor, Writer, Contributor Roles

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-blog#151]
This proposal introduces per-blog roles of Editor, Writer, and Contributor.

The below user stories describe the various use cases of these features.

# Editor management

**Scenario: Nominate editor**
Given there is a BlogHolder page
And there is a Member called “Alex”
And the BlogHolder does not have any editors assigned
And I am a CMS administrator
When I view the BlogHolder in the Pages CMS section
And I make Alex an editor of the BlogHolder
Then I can see that Alex is an editor of the BlogHolder

**Scenario: Revoke editor**
Given there is a BlogHolder page
And there is a Member called “Alex”
And Alex is an editor of the BlogHolder
And I am a CMS administrator
When I view the BlogHolder in the Pages CMS section
And I remove Alex as an editor of the BlogHolder
Then I can see that Alex is not an editor of the BlogHolder

# Editor publishing

**Scenario: Change a blog entry**
Given there is a BlogHolder page
And there is a BlogEntry page under the BlogHolder
And I am an editor of the BlogHolder
When I view the BlogEntry in the Pages CMS section
Then I can edit the content of this BlogEntry
And I can change who is listed as writer of this BlogEntry
And I can save my changes
And I can publish any changes

# Writer management

**Scenario: Nominate writer**
Given there is a BlogHolder page
And the BlogHolder does not have any writers
And there is a Member called “Alex”
And I am an editor of the BlogHolder
When I view the BlogHolder in the Pages CMS section
And I make Alex an writer of the BlogHolder
Then I can see that Alex is an writer of the BlogHolder

**Scenario: Revoke writer**
Given there is a BlogHolder page
And there is a Member called “Alex”
And Alex is an writer of the BlogHolder
And I am an editor of the BlogHolder
When I view the BlogHolder in the Pages CMS section
And I remove Alex as an writer of the BlogHolder
Then I can see that Alex is not an writer of the BlogHolder

# Writer publishing

**Scenario: Publish a blog entry**
Given there is a BlogHolder page
And there is a BlogEntry page under the BlogHolder
And I am an writer of the BlogHolder
And I am a author of the BlogEntry
When I view the BlogEntry in the Pages CMS section
Then I can see if there are any changes on the BlogEntry that have not been made public
And I can make these changes public

**Scenario: Unpublish a blog entry**
Given there is a BlogHolder page
And there is a BlogEntry page under the BlogHolder
And I am an writer of the BlogHolder
And I am a author of the BlogEntry
When I view the BlogEntry in the Pages CMS section
Then I can remove this page from the public site
And doing so does not remove this page from the CMS

# Contributor management

**Scenario: Nominate contributor**
Given there is a BlogHolder page
And the BlogHolder does not have any contributors
And there is a Member called “Alex”
And I am an editor of the BlogHolder
When I view the BlogHolder in the Pages CMS section
And I make Alex a contributor of the BlogHolder
Then I can see that Alex is an contributor of the BlogHolder

**Scenario: Revoke contributor**
Given there is a BlogHolder page
And there is a Member called “Alex”
And Alex is an contributor of the BlogHolder
And I am an editor of the BlogHolder
When I view the BlogHolder in the Pages CMS section
And I remove Alex as a contributor of the BlogHolder
Then I can see that Alex is not an contributor of the BlogHolder

# Contributor rights

**Scenario: Create a new blog entry**
Given there is a BlogHolder page
And I am a contributor of the BlogHolder
When I view the BlogHolder in the Pages CMS section
And I create a new BlogEntry through the context menu
Then I am redirected to the edit page form for the newly created BlogEntry
And I can see this page appear beneath the selected parent in the blog tree
And I can see that I am listed as a author of the BlogEntry
And I can not edit the list of authors
And I can edit the content of the BlogEntry
And I can save my changes
And I can not publish my changes

**Scenario: Edit a blog entry**
Given there is a BlogHolder page
And there is a BlogEntry page under the BlogHolder
And I am a contributor of the BlogHolder
And I am a author of the BlogEntry
When I view the BlogEntry in the Pages CMS section
Then I can edit the content of the BlogEntry
And I can save my changes
And I can not publish my changes

**Comment by assertchris** [comment]
These have been implemented. :tada:
