### ISSUE TITLE
BlogMigrationTask

### ISSUE THREAD

**Issue by stevevu** [silverstripe/silverstripe-blog#161]
Hi,

We are converting a SS2.4 site to SS3.1 and using the SS3.1 compatible blog module.  When we run /dev/build, we are getting validation errors about specific blog page types not allowed as children of certain blog page types.

For example, in our client's SS2.4 site, there are BlogEntry pages that are children  of BlogEntry pages and BlogHolder pages that are children of BlogTree pages.

In the SS2.4 module, this is OK since I believe the hierarchy is:
BlogTree
  |_ BlogHolder
    |_ BlogEntry

The BlogMigrationTask appears to convert:
1. BlogTree and BlogHolder page types to Blog dataobjects
2. BlogEnty page types to BlogPost dataobjects

with the hierarchy restriction that Blog has allowed_children = array('BlogPost').

So my questions are:
1. Now that it appears that the major blog components are DataObjects instead of Pages, what is/are the page type(s) that can be used to manage Blog and BlogPost?
2. What is the best way to handle our clients' now disallowed blog hierarchy as described above?

thanks much!
Steve

**Comment by micmania1** [comment]
It sounds like you're trying to use the development version which is extremely unstable at the moment as work is ongoing. The latest stable release is 1.0.0 which works with 3.1.

**Comment by stevevu** [comment]
Thanks Michael!  That was it!  Using 1.0.0 version now and /dev/build runs fine.
