### ISSUE TITLE
Excerpt is not parsed for short codes

### ISSUE THREAD

**Issue by cjsewell** [silverstripe/silverstripe-blog#163]
Adding an image etc to a blog post makes the Excerpt in its parent Blog page show short codes.

The content should be parsed for shortcodes or strip them out

**Comment by LiamW** [comment]
Don't mean to piggyback off this, though not sure it needs its own issue opened but I'm having issues with $Excerpt in that there are <br>'s being inserted into the content every few words when viewed. The <br>'s don't exist in the tinymce field when I view html source. It is only being displayed like this. I've installed the module on 2 different sites on my dev machine and this happens both times.

**Comment by tractorcow** [comment]
Could be related to https://github.com/silverstripe/silverstripe-framework/issues/1381

**Comment by assertchris** [comment]
Thanks for pointing this issue out, by the way. We've added it to out internal issue tracker as potentially blocking a stable release of blog 2.0.

**Comment by tractorcow** [comment]
Fixed with #238
