### ISSUE TITLE
Blog ArchiveWidget $title is not i18n enabled

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-blog#18]
Copied from http://open.silverstripe.org/ticket/6462

The ArchiveWidget? in blog is not i18n enabled.

A possible solution would be to override the Widget::Title() method as below:

function Title()
{
    return _t('ArchiveWidget.BROWSE_BY_DATE', 'Browse by date');
}

**Comment by assertchris** [comment]
@tractorcow @sminnee can this be closed?
