### ISSUE TITLE
Minor z-index bug for Post Options and CMS View Mode

### ISSUE THREAD

**Issue by Turnerj** [silverstripe/silverstripe-blog#189]
As shown below, there is a minor z-index bug with the Post Options pane and the View Mode options.

![image](https://cloud.githubusercontent.com/assets/904226/7150880/a693bcac-e360-11e4-8027-e6481b8b229d.png)

![image](https://cloud.githubusercontent.com/assets/904226/7150985/a24a1824-e362-11e4-82c6-163b031ac218.png)

Not sure if this is something that is fixable from this module or whether it is a bug in the CMS. This is the first time I have seen a pane like that outside of the one used for the SiteTree and ModelAdmin in the CMS so I am not sure.

This is against the latest version on the master branch, updated a few minutes ago. Only happens when Edit mode is selected (so the Post Options is just above the view mode button on the page)

**Comment by assertchris** [comment]
Thanks for reporting this. Looks like a CMS CSS bug, but it can live here for now.

**Comment by assertchris** [comment]
This has been resolved in CMS. Look out for it in the next release! :)
