### ISSUE TITLE
master: showing first entry when adding two enries in a row

### ISSUE THREAD

**Issue by xini** [silverstripe/silverstripe-blog#190]
Process:
1. add a new blog post and publish it.
2. Go back to the blog and click on 'add new post' again
result: instead of adding a new post the post from step 1 gets displayed in the editor.

**Comment by assertchris** [comment]
I've just tested this and I cannot reproduce an error with the steps you've given. What version are you using?

**Comment by xini** [comment]
Hi Chris,
hm, very strange. 
I'm using SS 3.1.12 and blog 2.0.*@dev. I had updated suing composer yesterday and it showed that behavior, I have updated again now and it's fine.
Sorry for the false alarm. And thanks.
Regards, Flo

**Comment by assertchris** [comment]
It's not a problem. We're all about fixing bugs here, so we love to hear about them! :)
