### ISSUE TITLE
Hardcoded pieces of text in blog module

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-blog#20]
Copied from http://open.silverstripe.org/ticket/6870

Hi!

I noticed that the blog module for SilverStripe? have hardcode pieces of text:

Left sidebar titles:

 * blog management
 * tag cloud
 * browse by date

Name of the months in sidebar 'browse by date'.

BlogSummary?.ss

 * Read the full post
 * comments

Would require an update of the blog module to include these texts in translation mode. It seems long ago that this problem exists. When you can an update on the blog module with these fixes?

Thanks.

Regards, Jose A.

**Comment by assertchris** [comment]
@sminnee ping

**Comment by tractorcow** [comment]
New template supercedes these issues :)
