### ISSUE TITLE
BUG Add a custom summary field overflow

### ISSUE THREAD

**Issue by micmania1** [silverstripe/silverstripe-blog#209]
![image](https://cloud.githubusercontent.com/assets/881537/7388190/6a37cd18-eeb7-11e4-8fce-10374e789b94.png)

Further to the above issue, I don't think this (especially being hidden) is the second most important input element in the blog post. This should appear after the content and probably even after featured image as an extra optional input. See WordPress for reference.

**Comment by assertchris** [comment]
The overflow bug is fixed in `3.1.13`.

**Comment by tractorcow** [comment]
I feel that having it before the content makes more sense, since the start of the Content field actually relates to the copy in the summary.

Placing it after Content would juxtapose it with the end of the actual article, which doesn't make for good review.

**Comment by micmania1** [comment]
The current layout doesn't make much sense. Its more likely that you'd add a featured image than a custom summary but you have to scroll down the entire page to know it exists.

The idea behind showing title and content first was that the display becomes minimal whereas this does the opposite by pushing optional fields to the top.

**Comment by flashbackzoo** [comment]
For reference, this is the wordpress screen...
![wordpress](https://cloud.githubusercontent.com/assets/878176/7579688/c16e231c-f8bb-11e4-975a-433d3421f039.png)

**Comment by flashbackzoo** [comment]
I agree with @micmania1 

You always have a Post Title and Content, and may not require anything else, so it makes sense to have these fields grouped together that the top.

Featured Image and Custom Summary seem to be a logical grouping too, they're additional fields and are the main components which make up the post's summary view.

**Comment by tractorcow** [comment]
Ok, I guess the consensus of the majority can rule. Submit a PR and I'll merge.

**Comment by clarkepaul** [comment]
I feel that if the summary is placed by metadata it will be overlooked (specially as they look the same), if it was to move down then it should be open permanently. 
I don't actually have a problem with the current placement (but I'm not a wordpress user). From what I've seen most authors would actually write outside of the cms and paste it into it to do the final touches. I would have thought from both a reader and author perspective the Title flows into the Summary which then leads into the content. For me its like having a hero panel above the content of the page, we don't present it the hero below the content within the CMS. Might be a good one to test with a few people?

**Comment by clarkepaul** [comment]
That consensus would be coming from developers and not the people using it - in other words it would be slightly biased (just like the current implementation).

**Comment by flashbackzoo** [comment]
@clarkepaul there is a good test in there somewhere. The first thing to do might be segment the sample group based on whether or not they use the custom summary field. It doesn't make much sense to run a 'time to complete' test on the entire group if a large percentage of those people never even use the feature.

If there is a large group of people using the field all the time, it would make a good A/B test, using that group of people. The task could be 'Create a blog post with a custom summary'. The 'time to complete' could be measured on the current field order, and on the proposed field order. This would give a pretty good indication of which better.

If there are hardly any people using the custom summary field, it might be better to have to lower in the order.

**Comment by clarkepaul** [comment]
Sounds good, challenging getting that info but could be a good one to try out the process though.

**Comment by tractorcow** [comment]
Addressing the above, for the time being shall we order these fields as:

- Content
- Summary
- Featured Image
- Metadata

That way the metadat isn't put rirght beside the summary (and thus isn't confused for it).

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-blog/pull/228 and the latest version of framework (to be released soon).

I'm happy to leave this ticket open until the stable framework release.

**Comment by flashbackzoo** [comment]
There's a survey about this issue http://www.silverstripe.org/community/contributing-to-silverstripe/

**Comment by tractorcow** [comment]
3.1.13-rc1 is out so I'm going to close this. :D
