### ISSUE TITLE
Success message overflows

### ISSUE THREAD

**Issue by micmania1** [silverstripe/silverstripe-blog#210]
![image](https://cloud.githubusercontent.com/assets/881537/7388348/6e4371c2-eeb8-11e4-9de1-bc9876b9faa8.png)

Runs behind the right menu.

**Comment by micmania1** [comment]
Also displays space under the right menu when you scroll, but only when the success message above is present.

![image](https://cloud.githubusercontent.com/assets/881537/7388364/9a826086-eeb8-11e4-9558-8d714770aab6.png)

**Comment by assertchris** [comment]
Beta is a time for growth-hacking, not fixing things...

**Comment by micmania1** [comment]
FYI this isn't possible with CSS. The HTML kind of looks like this.

```
<div class="cms-thing">
    <p class="message">Page created blah</p>
    <fieldset>
        <div class="blog-sidebar">...</div>
        <div class="blog-fields">...</div>
    </fieldset>
</div>
```

The only part of the template we control is inside fieldset and unfortunately CSS doesn't have parent selectors.
