### ISSUE TITLE
NEW Collapse SiteTree menu when editing a blog post

### ISSUE THREAD

**Issue by micmania1** [silverstripe/silverstripe-blog#211]
The content editing section doesn't provide much room on small screens and everything looks squashed. 

My aim was to have the left menu collapsed by default when editing a BlogPost so the user could focus on writing. I was also planning on adding a back button to the top toolbar to replicate GridField functionality - this would replace the breadcrumbs. 

I didn't get as far as playing with this so not sure what issues would be encountered.

**Comment by flashbackzoo** [comment]
This is something that is being considered for 3.2 in relation to page editing. No code has been written yet, but wireframes are being put together for community feedback. If it ends up going ahead, Blog will get this behaviour too.

**Comment by flashbackzoo** [comment]
Here's the RFC for the updates to the SiteTree menu https://github.com/silverstripe/silverstripe-framework/issues/4185

@micmania1 will this help?

**Comment by flashbackzoo** [comment]
This will happen in 3.2 https://github.com/silverstripe/silverstripe-framework/pull/4212

**Comment by tractorcow** [comment]
I guess it's fixed so closing. :)

Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4212
