### ISSUE TITLE
Dev/Build won't complete

### ISSUE THREAD

**Issue by jamietotten** [silverstripe/silverstripe-blog#216]
I'm having a problem running a dev/build when adding the new blog module. The build won't complete and then can't access the admin. 

Tested on 
SS Version: 3.1.6 & 3.1.8

**Comment by MattyBalaam** [comment]
I am having the same problem upgrading from a site with the old blog module installed. 

[User Error] Uncaught SS_DatabaseException: Couldn't run query: SELECT COUNT(*) FROM "BlogEntry_versions" LEFT JOIN "BlogPost_versions" ON "BlogPost_versions"."RecordID" = "BlogEntry_versions"."RecordID" AND "BlogPost_versions"."Version" = "BlogEntry_versions"."Version" WHERE "BlogPost_versions"."ID" IS NULL Table 'ss_xxxx.blogpost_versions' doesn't exist

**Comment by MattyBalaam** [comment]
Noticed my composer.json had 3.* for the cms and framework. Rolled back to 3.1.* and now the build finishes.

**Comment by assertchris** [comment]
Well spotted. Thanks for pointing this issue out, by the way. We've added it to out internal issue tracker, so it'll get fixed before blog is out of beta. :)
