### ISSUE TITLE
Edited BlogPosts show up in Sitree

### ISSUE THREAD

**Issue by wandl** [silverstripe/silverstripe-blog#218]
When editing a blogpost it suddenly appears under the Blog (parent) in SiteTree editing subsequent posts shows each item that has been edited. This seems like strange behavior?
![screen shot 2015-05-04 at 5 03 22 pm](https://cloud.githubusercontent.com/assets/7665399/7450058/8e243b5a-f27f-11e4-84b1-db47c84214c6.png)

SS 3.1.12
Blog 2.0.x-dev

**Comment by lerni** [comment]
I see this as a feature (of lumberjack?) since it helps to navigate back and forth the Posts edited.

**Comment by tractorcow** [comment]
It's definitely a bug but it is an issue in lumberjack not just in blog. :)

**Comment by micschk** [comment]
@dhensby pointed this out a while ago but both @micmania1 and me (excludechildren module) considered this a feature. I cannot find the thread now but I remember it had something to do with the ajax call for the sitetree circumventing the regular Children method. Dan proposed a solution as well, should you want to change this behaviour.

**Comment by micschk** [comment]
Found it: https://github.com/silverstripe/silverstripe-framework/pull/3837#issuecomment-72051891
and: https://github.com/micmania1/silverstripe-lumberjack/issues/13

**Comment by micmania1** [comment]
Its definitely a bug, but I've found it more useful to keep than to get rid of. In the real world if you're editing multiple blog posts its useful to switch between them.

Personally, I don't think its worth spending time on. If somebody feels strongly that it should be fixed then they are more than welcome to submit a PR.

**Comment by tractorcow** [comment]
Your cms is very green :recycle:

**Comment by wandl** [comment]
Personally I think it would be good to fix this as from a content author perspective this is sort of confusing, a config option to enable it as a feature would be better, I would lean towards filtering out any pages that have been flagged not to show whether this is the showHidden or some new flag for lumberjack enabled objects I don't know: )

@tractorcow yes is very green have been working on branding SS for our business, just have tinymce and buttons to go is looking really good! This is also something I am interested in improving in SS is the way the sass themes work be much better if this was separated out of the framework but was a dependency and had some sort of build system which could simply be a package.json and npm scripts [good example here](http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/)... but this is for another discussion :)

**Comment by tractorcow** [comment]
Maybe it'd be a great project to look at theming within the CMS? Nice job in any case. :D

**Comment by tractorcow** [comment]
Given that, despite the fact that this is a legitimate bug, it seems generally undesirable that this behaviour is removed/changed.

Shall we agree to keep this behaviour and not mark this as a bug anymore?

**Comment by wandl** [comment]
Maybe move to Lumberjack, I think this is reasonable for the Blog but I am also thinking of using Lumberjack for other types of objects and I do not want to see them popping up when edited, a config option to turn this bug on and off would get my vote :)

**Comment by assertchris** [comment]
+1 for config option to toggle the behaviour off.

**Comment by micmania1** [comment]
I would be against adding a config option. When this is *actually* fixed in core this may become problematic.

I stick with my original stance: Its a feature until someone cares enough to fix the bug.

**Comment by tractorcow** [comment]
Let's leave this issue open until we decide what to do in core. ;)

**Comment by JorisDebonnet** [comment]
For what it's worth, I was also confused when I saw this at first, but now, I actually find it useful. 

I think that for a true fix, both parties need to be made happy: the feature remains ("I can switch back and forth easily"), but it is made less confusing ("huh, that isn't supposed to happen"). This might be done by adding a visual element in the site tree that indicates there may be more items before or after the shown subpage. I realize this would be an unprecented change though, but it could be an idea for when it is "ever" fixed.

**Comment by tractorcow** [comment]
I am not sure if anyone will realistically fix this though. If that's the case, there's no point keeping an issue open.

**Comment by JorisDebonnet** [comment]
Maybe it could be kept open just to dupe future issues into this one (if that is likely to happen). But apart from that, I would agree.
