### ISSUE TITLE
On translated site the date changes to LastEdited in template

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-blog#22]
From http://open.silverstripe.org/ticket/6645

If I update a non-translated page(German) in the back-end, the translated(English) page get's changed too(green color in the site tree). And if I don't update these non-visible change I get the LastEdited? date from the German page in the English front-end side, via $Date.FormatI18N(%d. %B %Y). But in the database there is no visible change on the English page.

----

OK, I ran a view tests, and I think it's a global issue. When I ask for $Created it also jumps on the LastEdited? field of the original(German) page. The other way around I couldn't recognize this behaviour - the German page doesn't turn green and don't "forget" it's Created date, when I make a change to the translated counterpart. I don't know where to look next, and need to find any solution, as I can't prompt the user to save all it's translations after a little change on the original. (Maybe an auto save...)

**Comment by micmania1** [comment]
This was first raised 5 years ago so i'm not going to bother asking for steps to reproduce :p It sounds like an issue with translatable or w/e was used back then so i'm going to close.
