### ISSUE TITLE
BlogFilter LumberjackGridConfig

### ISSUE THREAD

**Issue by Tangdongle** [silverstripe/silverstripe-blog#222]
BlogFilter calls this to construct the Blog post gridfield: $this->getLumberjackGridFieldConfig()
getLumberjackGridFieldConfig() does not exist on either the Lumberjack class, nor the BlogFilter class, but it does exist on blog.

I propose either changing $this->getLumberjackGridFieldConfig() to $this->owner->getLumberjackGridFieldConfig() or adding the getLumberjackGridFieldConfig() method to Lumberjack or BlogFilter

**Comment by micmania1** [comment]
Can you link to the code you're talking about so I can get a better picture of what you propose to change?

**Comment by kinglozzer** [comment]
@Tangdongle Looks like `Lumberjack::getLumberjackGridFieldConfig()` does exist: https://github.com/silverstripe/silverstripe-lumberjack/blob/1.1/code/extensions/Lumberjack.php#L108-L118

**Comment by assertchris** [comment]
@Tangdongle would you mind showing us your `composer.lock` file?

**Comment by Tangdongle** [comment]
I didn't use composer to grab it. 
silverstripe-blog/code/extensions/BlogFilter.php:83 is the line I'm talking about.
BlogFilter is calling $this->getLumberjackGridFieldConfig() when getLumberjackGridFieldConfig() only exists on Blog, which the BlogFilter extension is being applied to.

**Comment by kinglozzer** [comment]
`BlogFilter` extends [`Lumberjack`](https://github.com/silverstripe/silverstripe-lumberjack/blob/1.1/code/extensions/Lumberjack.php), so it should inherit that method. @Tangdongle Have you downloaded [this version](https://github.com/micmania1/silverstripe-lumberjack) of the module instead of [the newer one](https://github.com/silverstripe/silverstripe-lumberjack)?

**Comment by Tangdongle** [comment]
@kinglozzer Yeah, turns out I was .1 of a version behind LumberJack. Not an issue
