### ISSUE TITLE
Folder structure for images in blog-posts

### ISSUE THREAD

**Issue by mediaclinic** [silverstripe/silverstripe-blog#224]
Upload field should put images inside /Uploads/blogimages/ by default. Or even like /Uploads/blogimages/year/month/ or /Uploads/blogimages/year/category. It would give users a good starting point for big blogs to get organized with images.

**Comment by assertchris** [comment]
That's an interesting idea... @tractorcow: do you know if there is an easy way to do this (assuming others agree with this idea)?

**Comment by tractorcow** [comment]
you just set `$field->setUploadFolder()`. We couldn't do it with years probably because that information might be changed in the same request that files are uploaded.

**Comment by assertchris** [comment]
@mediaclinic does that solve the organisation issues, for you?

**Comment by mediaclinic** [comment]
It helps a lot, if the images are saved by default to blog-specific folder, yes. And yes, it should be as default in the module (like /Uploads/blogimages/).

**Comment by camfindlay** [comment]
I did a project a while back migrating a large WP to SilverStripe while retaining the WP style folder structure. I used something like this...

$field->setUploadFolder('Uploads/'.date('Y',strtotime($this->owner->Date)).'/'.date('m',strtotime($this->owner->Date)).'/');

**Comment by assertchris** [comment]
I don't think this is something we want to enforce for the module. It's a good idea to talk about it in the lessons though...
