### ISSUE TITLE
Pagination Not Documented

### ISSUE THREAD

**Issue by gordonbanderson** [silverstripe/silverstripe-blog#227]
Whilst testing a template for pagination I noticed that the default for pagination is set to none whatsoever.  Looking through the code, it appears there is a field called PostsPerPage within the Blog model, and this is editable from the settings tab.  However PostsPerPage is initialized with a value of 0, meaning no pagination.

1) Should there not be a sensible default, perhaps maybe '10', the same default as for a PaginatedList in SilverStripe
2) The method to change the number of blog posts per page should be documented, even if just briefly as a mention.

**Comment by assertchris** [comment]
When we were creating 2.0, we decided to let template authors decide how they want to paginate the comments list. Unless site owners expect a large volume of comments for each post, pagination is likely to complicate the template creation process for little value. This was the "sensible default" we chose... :)

That said, you can still access un-paged comments with `$Comments` or paged comments with `$PagedComments` (@tractorcow: this is correct?).

**Comment by tractorcow** [comment]
I think we could set it to 10 per page. It's a good reasonable default.
