### ISSUE TITLE
Inheriting fields from Page class

### ISSUE THREAD

**Issue by dawb** [silverstripe/silverstripe-blog#229]
Tying to access extra $db fields and $has_one relations that are set through the Page class within the Blog Post template returns a database error.

Adding these extra fields through a dataextension of BlogPost solved this issue, but should they be accessible within the template or calling them on the object without having to do this?
It seems to be fine both viewing and writing within the admin fields without having to add the dataextension. 

The additional fields are all accessible through the Blog class.

Page class:
```
private static $db = array(
	'SubTitle' => 'Text'
);

private static $has_one = array(
	'BannerImage' => 'Image'
);
```
Error returned from template:
![screen shot 2015-05-12 at 7 09 33 pm](https://cloud.githubusercontent.com/assets/777930/7581753/eb956f32-f8da-11e4-8f1a-8671cb10f150.png)

**Comment by assertchris** [comment]
Could you show us the template code, which is generating the error?

**Comment by dawb** [comment]
Hi, 

The template code is below, cheers

<% if BannerImage %>
    <section class="home small-banner reverse cover" style="background-image: url('$BannerImage.CroppedImage(1900,380).URL')"></section>
<% end_if %>
<section class="top-content-area">
    <div class="content row">
        <div class="small-12 columns">
            <h1>$Title</h1>
            <% if SubTitle %>
                <h3>$SubTitle</h3>
            <% end_if %>
        </div>
    </div>
</section>

**Comment by assertchris** [comment]
I can't reproduce this error (on `master`). Are you using the `1.0` branch?

**Comment by micmania1** [comment]
@dawb I'm unable to reproduce this also. Could you provide the full backtrace of your error please?

**Comment by tractorcow** [comment]
The problem here is that you are querying in live mode, but your conditions are somehow pointing to the stage tables? e.g. `select Table.Field from Table_Live` is a table mis-match.

This code has changed a LOT since the last year though. It looks like it's probably been fixed?

**Comment by dawb** [comment]
Thanks, yes the error doesn't seem to be repeating so I'd say this has already been fixed.
