### ISSUE TITLE
Blog module creates a new BlogHolder when used with subsites

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-blog#23]
From http://open.silverstripe.org/ticket/6234

Blog module creates a default page when installed which is fair enough since if you didn't want a blog you wouldn't have installed the module. However when using the blog module and the subsites module a new Blog Holder is created for every subsite when dev build is run.

Attached is a patch to blog which disables the filter and then renables it again after searching for a BlogHolder?.

Patch: http://open.silverstripe.org/attachment/ticket/6234/blog_subsites.patch

**Comment by assertchris** [comment]
@sminnee/@tractorcow Is this still an issue with `dev-master`?

**Comment by assertchris** [comment]
The new version doesn't automatically create holders when installing the blog.
