### ISSUE TITLE
BlogArchiveWidget GroupBy Issue

### ISSUE THREAD

**Issue by adrian-stein** [silverstripe/silverstripe-blog#232]
I am getting an error with the widget since the "Clean up" commit (https://github.com/silverstripe/silverstripe-blog/commit/787c02a19d2491ace59948630795e5bc6da40bf0)

It appears changing the quote tags around the groupBy line in the method getArchive() in BlogArchiveWidget.php now breaks the select statement as seen here: http://postimg.org/image/hllern6yn/ 

if I change put them back to the way it was before the commit it appears to work. Are you able to fix it up?

**Comment by assertchris** [comment]
Well spotted - I'll fix this shortly!

**Comment by tractorcow** [comment]
Fixed with #234
