### ISSUE TITLE
Adding Widgets to blog page Fatal error

### ISSUE THREAD

**Issue by adrian-stein** [silverstripe/silverstripe-blog#233]
Since one of the last commits when adding a widget to a page in the CMS I get the below error:

Fatal error: Call to a member function merge() on a non-object in G:\Nimbler\es\blog\code\widgets\BlogArchiveWidget.php on line 64

if I comment out that line of code I then get this error:

Fatal error: Call to a member function push() on a non-object in G:\Nimbler\es\blog\code\widgets\BlogTagsWidget.php on line 43

If both lines are commented out then the page loads. Any ideas?

**Comment by assertchris** [comment]
Will check it out!

**Comment by tractorcow** [comment]
I think the issue is you are using widgets 1.0, when 1.1 is the one we were testing against.

A fix on the 1.0 branch is available at https://github.com/silverstripe/silverstripe-widgets/pull/89, although in your case I would still recommend you upgrade. ;)

**Comment by adrian-stein** [comment]
Ah. Yeah changed from using dev/master due to the restriction of having to have at least Silverstripe 3.2. I must have gone back to to 1.0 and not 1.1. I have not put it to 1.1 and it works a treat again. Thanks.
