### ISSUE TITLE
Error while saving a BlogPost

### ISSUE THREAD

**Issue by marcokernler** [silverstripe/silverstripe-blog#239]
Hi,

I've installed the blog module within a project of mine. Here are the entries from the composer.json:

```
{
	"silverstripe/cms": "~3.1",
	"silverstripe/framework": "~3.1",
	...
	"silverstripe/blog": "2.0.x-dev",
}
```
If I'm now want to save a BlogPost, the following Error's appear:

```
ERROR [Warning]: array_key_exists(): The first argument should be either a string or an integer
IN POST /admin/pages/edit/EditForm
Line 317 in /xxxx/framework/forms/DropdownField.php

Source
======
  308: 
  309: 	/**
  310: 	 * Validate this field
  311: 	 *
  312: 	 * @param Validator $validator
  313: 	 * @return bool
  314: 	 */
  315: 	public function validate(Validator $validator) {
  316: 		$source = $this->getSourceAsArray();
* 317: 		if (!array_key_exists($this->value, $source)) {
  318: 			if ($this->getHasEmptyDefault() && !$this->value) {
  319: 				return true;
  320: 			}
  321: 			$validator->validationError(
  322: 				$this->name,
  323: 				_t(
```

and:

```
ERROR [Notice]: Array to string conversion
IN POST /admin/pages/edit/EditForm
Line 2112 in /xxx/framework/i18n/i18n.php

Source
======
  2103:					function($matches) use(&$injectionArray) {
  2104:						return $injectionArray ? array_shift($injectionArray) : '';
  2105:					},
  2106:					$returnValue
  2107:				);
  2108:			} else {
  2109:				// Standard placeholder replacement with named injections and variable order.
  2110:				foreach($injectionArray as $variable => $injection) {
  2111:					$placeholder = '{'.$variable.'}';
* 2112:					$returnValue = str_replace($placeholder, $injection, $returnValue, $count);
  2113:					if(!$count) {
  2114:						SS_Log::log(sprintf(
  2115:							"Couldn't find placeholder '%s' in translation string '%s' (id: '%s')",
  2116:							$placeholder,
  2117:							$returnValue,
  2118:							$entity
```

Did anyone else had the same problem?

**Comment by assertchris** [comment]
Did you run `dev/build` after adding the blog module?

**Comment by tractorcow** [comment]
Hi @marcokernler it's possible you are trying to run the blog on the (yet unreleased) 3.2, which we haven't got around to providing a compatible version of blog for.

If you change your composer.json to the following it should work.

```json
{
    "silverstripe/cms": "~3.1.0",
    "silverstripe/framework": "~3.1.0",
    "silverstripe/blog": "2.0.x-dev",
}
```

**Comment by marcokernler** [comment]
Hi @tractorcow,

thank you, it works!

**Comment by RuthAdele** [comment]
I'm using the latest release of Silverstripe (3.2), and I'm getting this same error.

Now that Silverstripe has released 3.2, will Silverstripe Blog be updated?

**Comment by kinglozzer** [comment]
@RuthAdele The blog module has already been updated to fix this issue, make sure you’re using the latest release (currently 2.3.0 - https://github.com/silverstripe/silverstripe-blog/releases)

**Comment by RuthAdele** [comment]
Ah, I see what's happened, I've used composer to include dev-master, but that's the 2.2 version, not the 2.3 version which works with Silverstripe 3.2.

Thanks :)

**Comment by tractorcow** [comment]
Actually thanks for poiting this out... master branch alias needs updating to 2.3.

**Comment by tractorcow** [comment]
https://github.com/silverstripe/silverstripe-blog/commit/ad8a9f142936e3ffafd73bdcb118cf73a824bb71
