### ISSUE TITLE
Blogs RSSWidget loosing native language characters

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-blog#24]
From http://open.silverstripe.org/ticket/5189

Hello,

I've stumbled upon a strange issue. The RSSWidget is loosing native language characters in the titles.

Lets say we have a title:

Ma?a rewolucja ...

then in the widget I get:

Maa rewolucja ...

I'm using todays svn build. Example:

widget:  http://www.silverstripe.org.pl/
it's source:  http://www.silverstripe.org.pl/wiadomosci/rss

**Comment by assertchris** [comment]
@sminnee/@tractorcow is this still an issue?

**Comment by tractorcow** [comment]
RSSWidget was removed.
