### ISSUE TITLE
AuthorID is still referenced

### ISSUE THREAD

**Issue by assertchris** [silverstripe/silverstripe-blog#240]
See: https://github.com/silverstripe/silverstripe-blog/pull/142

**Comment by micmania1** [comment]
@textagroup I see you raised the original issue. is this something you're still looking at?

**Comment by textagroup** [comment]
@micmania1 I did create a pull request but it would have gone stale now.
So I am no longer looking at it.

**Comment by micmania1** [comment]
@textagroup apologies for that.

This is an old version of blog now so I doubt it will be picked up again.
