### ISSUE TITLE
Set pagination to 10 by default

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-blog#249]
Hi

We recently upgrade to the new blog system for an existing site with 2000+ blog entries.  This crashed the site because the blog "holder" page has the default "Page Limit" set to 0 which means infinite.  I think it would be better to set to a hard-coded default in case PostsPerPage set to zero - e.g. 10. 

Another "problem" was that having the PostsPerPage field in the settings is something that surprised me. I can see how it is a "settings", but I did not look there (as I hardly ever look in settings at all). Not sure how to solve this, but perhaps a little note on the "blog posts" tab in CMS would be useful (to adjust the number of posts shown per page, go to the [settings] tab and adjust.

**Comment by assertchris** [comment]
That's been fixed here: https://github.com/silverstripe/silverstripe-blog/commit/ea06252f2d733befe0d6a33451a6de5c1a608677

**Comment by sunnysideup** [comment]
also, having PostsPerPage tagged at the bottom of a whole bunch of stuff that does not really relate to "blog" specific stuff is making it hard to find.  Why not change the settings.users stuff to settings.blogsettings and add all the fields there?

**Comment by assertchris** [comment]
It does seems a little hard to find them. I'll chat to the team UX specialists and respond with their feedback.

**Comment by assertchris** [comment]
Consensus is that this is the best place for it for the moment. The logic change you suggest sounds good, but it would have to be tested. Do you have time for a pull request?

**Comment by micmania1** [comment]
I'm going to consider this fixed as there hasn't been any movements since June and the initial issue has been resolved.

The problem with the proposed code is that you can't then remove pagination without updating the defaults to 0 in YAML which CMS admins can't do.
