### ISSUE TITLE
Add Twitter Mentions as "tweetbacks" to blog comments

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-blog#25]
From http://open.silverstripe.org/ticket/4386

The death of comments is on us, thanks to facebook and twitter. In other words, people are beginning to no longer write comments on blogs but just tweet about them. Put SilverStripe? at the head of the back by allowing tweets to do with a blog post to show up as comments, in the same vein as trackbacks. In true twitter form, these are known as tweetbacks.

References:  http://www.readwriteweb.com/archives/comments_dead_twitter_holds_smoking_gun.php (Read the content AND notice that it lists tweet mentions on the page)

 http://yoast.com/wordpress/tweetbacks/

 http://danzarrella.com/beyond-tweetbacks-introducing-tweetsuite.html

 http://danzarrella.com/tweetbacks-beta.html

I suggest we first add this to the blog, possibly as an extension.

I'm also interested in seeing whether you can use the search API of facebook to highlight people mentioning your blog post on Facebook.

**Comment by micmania1** [comment]
@sminnee I'm going to close this as it hasn't been actioned in 4 years. Also, this kind of feature would now make sense to be added to the comments module.
