### ISSUE TITLE
Access level to onBeforeWrite() must be public

### ISSUE THREAD

**Issue by jfullerton** [silverstripe/silverstripe-blog#251]
Happens in Blog.php and BlogPost.php

`PHP Fatal error:  Access level to Blog::onBeforeWrite() must be public (as in class Page) in /blog/code/model/Blog.php on line 15`

`PHP Fatal error:  Access level to BlogPost::onBeforeWrite() must be public (as in class Page) in /blog/code/model/Blog.php on line 18`

Using: 
```
"php": ">=5.3.2",
"silverstripe/cms": "3.1.12",
"silverstripe/framework": "3.1.12",
"silverstripe/blog": "dev-master",
"silverstripe/lumberjack": "~1.1",
"silverstripe/tagfield": "2.0.x-dev"
```

**Comment by kinglozzer** [comment]
@jfullerton From the description you’ve given, it sounds like you’ve got a `public function onBeforeWrite()` in your Page.php: it should be `protected function onBeforeWrite()`

**Comment by jfullerton** [comment]
@kinglozzer Ah ok, that took care of it. I should have looked there first! Thanks very much!
