### ISSUE TITLE
Icons for Blog and BlogPost

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-blog#267]
Can we get some sexy icons for the CMS site tree please? I assume these can be overridden through the config system if people desire so don't see any harm in providing a default. Although if it's going to be a... some kind of... monkey head? ![monkey face](https://raw.githubusercontent.com/silverstripe/silverstripe-blog/0.5/images/blogholder-file.gif) like the last blog module maybe leave it generic :stuck_out_tongue:

**Comment by micmania1** [comment]
Have any in mind? We'd need to use icons with an appropriate license.

I kept meaning to do this but I just never got around to it.

Definitely not <img src="https://raw.githubusercontent.com/silverstripe/silverstripe-blog/0.5/images/blogholder-file.gif" /> though. Looks like he's eaten too many smarties.

**Comment by jonom** [comment]
Haha he sure does. I don't have anything particular in mind. The Blog Post icon isn't so important because it isn't seen so much. I quite like the book/journal metaphor for Blog... don't know if SilverStripe Ltd have a style guide for their site tree icons but these

![1433483462_bookmark_book_open](https://cloud.githubusercontent.com/assets/1079425/7997462/657b5f78-0ae2-11e5-9997-d2d61ac9a55d.png) [source](https://www.iconfinder.com/icons/16132/book_bookmark_open_icon#size=16) or ![1433483484_book](https://cloud.githubusercontent.com/assets/1079425/7997469/75b97a64-0ae2-11e5-9e05-9b953691d5e9.png) [source](https://www.iconfinder.com/icons/16125/book_icon#size=16) with ![1433483751_document_letter_marked](https://cloud.githubusercontent.com/assets/1079425/7997511/1a911e5c-0ae3-11e5-9ca9-b017415793a2.png) [source](https://www.iconfinder.com/icons/14392/document_letter_marked_icon#size=16)

could work if the green was changed to SilverStripe  blue maybe?

Something a bit flatter might be more keeping with the times though.

**Comment by micmania1** [comment]
Maybe @clarkepaul has ideas?

I think a speech bubble is quite good for a blog. eg. http://www.flaticon.com/free-icon/black-speech-bubble_71580

**Comment by camfindlay** [comment]
+1

**Comment by clarkepaul** [comment]
I've started collecting icons for the ui, I'll see what I can find and present back.

**Comment by tractorcow** [comment]
Closed with https://github.com/silverstripe/silverstripe-blog/pull/357
