### ISSUE TITLE
Entering tags with spaces on the fly is problematic

### ISSUE THREAD

**Issue by camfindlay** [silverstripe/silverstripe-blog#282]
Attempted to create a blog tag which contained spaces (I think this is a legitimate use case), only to have the tag field split the tags as I typed into separate word tags. Idea user experience would be spaces allowed and to generate the new tag on comma not space.

**Comment by tractorcow** [comment]
Related to https://github.com/silverstripe-labs/silverstripe-tagfield/pull/24

**Comment by assertchris** [comment]
Fixed in https://github.com/asecondwill/silverstripe-tagfield/commit/989e7cae0846d374a499a15f997d78b3bef18ac0
