### ISSUE TITLE
Non-admins using a future PublishDate throws an error in certain cases

### ISSUE THREAD

**Issue by camfindlay** [silverstripe/silverstripe-blog#283]
When an editor, writer or contributor creates a BlogPost with a future PublishDate the following occurs:
 
1. An error is thrown - [User Notice] Requirements_Backend::combine_files(): Already included files framework/thirdparty/jquery/jquery.js,framework/thirdparty/jquery-ui/jquery-ui.js in combined file 'lib.js'
GET /admin/pages/edit/show/13?locale=en_NZ

Line 1048 in /framework/view/Requirements.php 

 2.  The blog post disappears from the Blog gridfield while I'm logged in as this non-admin user

 3. If I log in as an admin, I can see these future scheduled posts.

Have replicated the issue on fresh checkout of cwp recipe 1.1.0 on both local dev, a uat and a prod environment.

**Comment by tractorcow** [comment]
My feeling is the requirements issue is separate to the underlying issue. Will investigate and let you know.
