### ISSUE TITLE
Invalid path for internal page link shown on blog homepage

### ISSUE THREAD

**Issue by jeffreyguo** [silverstripe/silverstripe-blog#285]
When I was browsing a blog on SS blog homepage http://www.silverstripe.org/blog, I found an invalid link on the page. While I navigated to the individual blog page itself, that link works fine.
I'm not sure if it's an issue of the blog module as the issues appears for each internal link in SS blog.
![screen shot 2015-07-07 at 3 18 33 pm](https://cloud.githubusercontent.com/assets/6565447/8538182/13a3fabc-24bd-11e5-93d3-441e3d2bc2e0.png)

**Comment by tractorcow** [comment]
It's actually a bug in framework.

https://github.com/silverstripe/silverstripe-framework/issues/1381

**Comment by camfindlay** [comment]
@micmania1 ^ perhaps can be closed here?

**Comment by micmania1** [comment]
I've tried to replicate this in 2.0 and can't.

I've also checked which version of blog was running at the time and it was 0.7 (old). Given that this is an old version of blog and the issue is upstream, i'm going to close :)
