### ISSUE TITLE
Entwine property minInnerWidth does not start with a capital letter

### ISSUE THREAD

**Issue by webspilka** [silverstripe/silverstripe-blog#288]
Hi
I install
silverstripe 3.2.x-dev
and 
silverstripe/blog (dev-master a8e7bff)

And can not save Blog Posts 
![ss-blog-eror](https://cloud.githubusercontent.com/assets/1138069/8633392/c6290754-27ce-11e5-9c94-e24b16156f5c.png)
what may be caused by the appearance of such an error? 
```
Entwine property minInnerWidth does not start with a capital letter
lib.js?...6608729 (рядок 1629)
.warn()lib.js?...6608729 (рядок 1629)
message = "Entwine property minInne...t with a capital letter"
level = 2
.bind()lib.js?...6608729 (рядок 1697)
selector = null
k = "minInnerWidth"
v = 620
...
```

**Comment by nimeso** [comment]
I have the same issue :(

**Comment by tractorcow** [comment]
That issue is a warning, is it not?
If you cannot save the blog post are you certain it's this issue?

In any case, it shouldn't be hard to fix the case on it.
