### ISSUE TITLE
Sort Order of Blog Posts in Admin

### ISSUE THREAD

**Issue by basepath** [silverstripe/silverstripe-blog#289]
I haven't been able to find an alternative way of doing this so can the default sort be based on Publish Date? 

ie. in BlogPost.php add inner join as per below...
$pages = SiteTree::get()->innerJoin('BlogPost', '"SiteTree"."ID" = "BlogPost"."ID"')->filter(array(
	'ParentID' => $this->owner->ID,
	'ClassName' => $excluded
))->sort('"BlogPost"."PublishDate" DESC');

**Comment by JorisDebonnet** [comment]
I also had issues with the ordering, and finally found where it actually happens: not in `BlogPost.php`, but in `BlogFilter.php`. 

```php
			$pages = BlogPost::get()->filter(array(
				'ParentID' => $this->owner->ID,
				'ClassName' => $excluded
			))->sort('"PublishDate" DESC');
```
suffices in `updateCMSFields` there, instead of the current situation which does `->sort('"SiteTree"."Created" DESC');`.

**Comment by JorisDebonnet** [comment]
This is now fixed in the most recent commit! You should see it if you pull in the lastest dev version. So I think this can be closed.
