### ISSUE TITLE
Validation error for tag fields on SS 3.2

### ISSUE THREAD

**Issue by markguinn** [silverstripe/silverstripe-blog#291]
When I try to save a blog post under 3.2 I get the following error:

ERROR [Warning]: array_key_exists(): The first argument should be either a string or an integer
IN POST /admin/pages/edit/EditForm
Line 323 in /Users/guinns/projects/premierderm/framework/forms/DropdownField.php

This may be an issue with TagField - I'm not sure which place to post it. I apologize in advance if this is the wrong place. :)

EDIT: Just to be clear - this is on a fresh installation of SS via composer. When I switch the version constraints to 3.1.x-dev in composer.json and run `composer update` the error disappears.

**Comment by markguinn** [comment]
Confirmed that this is an issue with TagField (just needed to overwrite the validate() method) but this is still relevant as it will affect which version is compatible with blog + 3.2.

**Comment by markguinn** [comment]
Submitted a PR to the tagfield module here: https://github.com/silverstripe-labs/silverstripe-tagfield/pull/34

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe-labs/silverstripe-tagfield/pull/34
