### ISSUE TITLE
batch actions - can we have those back? 

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-blog#292]
Hi

because blogs are now more like dataobjects than pages you can not do the batch actions anymore (select many and publish / unpublish).  A client of mine finds this very frustrating. Are batch actions available or on the cards?

**Comment by tractorcow** [comment]
Hi @sunnysideup ,

You might be able to use gridfield-bulk-editing-tools module to add a bulk action checkbox to the lumberjack gridfield. Have you tried this? It might not work exactly the same as the old bulk actions did, though, but it should be possible. :D

**Comment by tractorcow** [comment]
Maybe we should add an option for "don't use lumberjack" for pages, in case people prefer the old interface.

**Comment by micmania1** [comment]
@tractorcow you can already disable it by setting BlogPost.show_in_sitetree = true

**Comment by tractorcow** [comment]
Ok, then that is the solution. :D
