### ISSUE TITLE
Access level to BlogPost::onBeforeWrite() must be public

### ISSUE THREAD

**Issue by pandauxstudio** [silverstripe/silverstripe-blog#294]
I tried to install the latest (dev-master) branch with the latest stable release of SS and got the following error when I tried to build:
**Access level to BlogPost::onBeforeWrite() must be public ...**

Here's my composer.json:

```javascript
{
	"name": "silverstripe/installer",
	"description": "The SilverStripe Framework Installer",
	"require": {
		"php": ">=5.3.2",
		"silverstripe/cms": "3.1.13",
		"silverstripe/framework": "3.1.13",
		"silverstripe-themes/simple": "*",
		"silverstripe/mssql": "*",
		"silverstripe/blog": "dev-master",
		"silverstripe/restfulserver": "dev-master"
	},
	"require-dev": {
		"phpunit/PHPUnit": "~3.7@stable"
	},
	"config": {
		"process-timeout": 600
	},
	"minimum-stability": "dev"
}
```

Had to downgrade to 1.0 for it to work:
```javascript
"silverstripe/blog": "1.0"
```

**Comment by stevie-mayhew** [comment]
Check out https://github.com/silverstripe/silverstripe-blog/issues/251 @pandauxstudio  :)

**Comment by pandauxstudio** [comment]
Thanks that fixed it.
Solution: Just had to replace ```public function onBeforeWrite() { ... }``` to ```protected function onBeforeWrite() {...}``` in my Page.php.
