### ISSUE TITLE
Bugs selecting Category and Tags with multiple Blog Holders

### ISSUE THREAD

**Issue by sweddell** [silverstripe/silverstripe-blog#295]
When there are multiple blogs with their own categories and tags, creating a post allows selection of all categories and tags instead of the ones specific to the Blog Holder.

![screenshot-localhost 8888 2015-09-12 10-29-59](https://cloud.githubusercontent.com/assets/75909/9831090/84c005fc-598c-11e5-9871-c872e3a6491e.png)

Selecting a category or tag from another Blog moves it to the Blog where the post is being created from.

![screenshot-localhost 8888 2015-09-12 20-15-13](https://cloud.githubusercontent.com/assets/75909/9831109/10491ee2-598d-11e5-9340-f29e803a14ac.png)

![screenshot-localhost 8888 2015-09-12 20-15-38](https://cloud.githubusercontent.com/assets/75909/9831121/5df8a4be-598d-11e5-9ffd-d9ce462996ed.png)

![screenshot-localhost 8888 2015-09-12 20-16-01](https://cloud.githubusercontent.com/assets/75909/9831117/3fa22954-598d-11e5-8efa-048e576f749f.png)

**Comment by nathanbrauer** [comment]
This is affecting us at Marketo. :)

**Comment by tractorcow** [comment]
The issue seems to be in the tagfield, not the blog module.

A fix is available at https://github.com/silverstripe-labs/silverstripe-tagfield/pull/57.
