### ISSUE TITLE
BUG future publish date doesn't prevent publish

### ISSUE THREAD

**Issue by mikeyc7m** [silverstripe/silverstripe-blog#296]
Blog posts with a future publish date are still showing up on the live site. They don't show on the blog listing page but can be accessed directly via their url or in other types of lists.

**Comment by mikeyc7m** [comment]
Looking at the canView function in BlogPost, it seems future posts do not report a PublishDate. I have no idea why it is suppressed.

**Comment by micmania1** [comment]
@mikeyc7m is this still an issue for you?

**Comment by mikeyc7m** [comment]
Yes.

I've installed the latest version, nothing has changed. Future-dated posts are still directly accessible via their URL on a live site, and show in the site search. They are also included in any datalists unless you filter by ClassName.

**Comment by mikeyc7m** [comment]
bump

the publishDate should always be there, perhaps canView could be altered so that when publishDate is missing the function returns false.

**Comment by dhensby** [comment]
Hmm, is this meant to be an embargo feature?

**Comment by tractorcow** [comment]
> I've installed the latest version, nothing has changed. Future-dated posts are still directly accessible via their URL on a live site, and show in the site search. 

This is a bug, from my point of view. These should have canView = false for those without draft permissions.

**Comment by mikeyc7m** [comment]
the new solution seems to work, yay! but... might it be better if the future article URL returned 404 instead of login? not sure what is more relevant.

**Comment by tractorcow** [comment]
In any case, fixed with #373
