### ISSUE TITLE
Feature: support sticky posts

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-blog#305]
Would be great if a blog post could be made sticky. 

This makes the ordering a bit more complicated of course, it has to sort by "sticky yes/no" first, and then by "PublishDate" (or creation date if there is no PublishDate, I guess).

**Comment by jonom** [comment]
Just adding a sort on sticky shouldn't be hard - think you can just do `sort("Sticky DESC, PublishDate DESC")`?

I kind of like this idea but would prefer if the sticky status was automatic... like new BlogPosts are sticky by default when first created but it is removed when a post is published. Likewise if you save changes but don't publish them the post becomes sticky. That would turn the gridfield in to a 'To Do' list where posts you need to do some work on are listed first.

**Comment by JorisDebonnet** [comment]
I understand your reasoning, but I think it is another use-case :) I want sticky posts to stay on top on the public website - not just in the CMS. Keeping drafts on top in the CMS certainly makes sense, but it feels like a separate issue for me. Anyway, let's see how the discussion on #302 unfolds first.

**Comment by jonom** [comment]
Ah true and fair enough. I'm sure you realise, but if this isn't added to the core module it should be very easy to add this behaviour to your own site with a DataExtension and a config override. Personally I would probably opt not to include this in the main module unless it's going to be used by a majority of users. Maybe it would be though - does anyone else have an opinion on this?

**Comment by stevie-mayhew** [comment]
We have a requirement for a "Featured Blog" about 30% of the time, so I wouldn't put it in core.

**Comment by micmania1** [comment]
I think it would make a good module but probably shouldn't make core.

**Comment by micmania1** [comment]
https://github.com/unclecheese/silverstripe-blog-featured-posts - I believe this means I can close this now :)
