### ISSUE TITLE
BUG Sites with large number of users (Member) breaks

### ISSUE THREAD

**Issue by camfindlay** [silverstripe/silverstripe-blog#311]
There are a number of fields that list Member to be selected to assign authors etc. These seem to all use Member::get() which given a sizable website with a large number of users brings everything to a grinding halt.

There should be some way to qualify a Member for select rather than a blanket "get all the things" for these situations.

Example in BlogPost:
```php
$authorField = ListboxField::create(
				'Authors',
				_t('BlogPost.Authors', 'Authors'),
				Member::get()->map()->toArray()
			)->setMultiple(true);
```

This kills my large site when I drill into a BlogPost, however if I add a simple ->limit(10) to the Member ORM call, no problem, page loads (though it's not useful in this state).

I'd want to be able to set a config value denoting a Security group I can add any users to which becomes my pool of potential authors that are selectable. This keeps the whole thing more controllable and avoids issues with large user bases.

**Comment by micmania1** [comment]
@camfindlay Can this be closed?

**Comment by camfindlay** [comment]
yip sure can! #312 fixes and we've tested on production in ss.org :+1:
