### ISSUE TITLE
delete button in gridfield is gone

### ISSUE THREAD

**Issue by guyvanbael** [silverstripe/silverstripe-blog#313]
The only way to delete a post is to edit (open as a page) and archive it. Is this correct behaviour?
I liked the option to be able to delete it in the gridfield.

![schermafbeelding 2015-10-30 om 08 36 58](https://cloud.githubusercontent.com/assets/3098809/10840644/b3d1fbd2-7ee1-11e5-828e-cd4ddba35092.png)

**Comment by tractorcow** [comment]
I think that has always been the case.

We could create an "archive" button, although it would not be strictly the same as the `GridFieldDeleteAction` in core.

**Comment by tractorcow** [comment]
Actually, this is more an issue for lumberjack than the blog module directly (although it does rely on it).

The core lumberjack module https://github.com/silverstripe/silverstripe-lumberjack probably should have this functionality implemented there.

It's fine to leave this issue open here for the time being.

**Comment by stevie-mayhew** [comment]
@wernerkrauss solved this in CatalogManager (https://github.com/Little-Giant/silverstripe-catalogmanager/) by adding an additional action to publish/unpublish to the GridField (https://github.com/Little-Giant/silverstripe-catalogmanager/blob/master/code/Actions/GridfieldPagePublishAction.php) which I think is the best option for these type of interactions. Deletion is still handled from within the object so it has to be a more conscious decision by the user to actually delete the item.

**Comment by micmania1** [comment]
We could add the publish/unpublish functionality as above but I'd prefer some sort of confirmation step before actually performing the action.

**Comment by micmania1** [comment]
I'm going to close this issue for now. If anybody plans to work on this feel free to leave a comment here or open a new issue/pull request on the lumberjack module.
