### ISSUE TITLE
Problem with URLSegment

### ISSUE THREAD

**Issue by StefanHhe** [silverstripe/silverstripe-blog#316]
When I create a new blog page and the new created page is a child page of another page in the pagetree the URL Segment must be: http://www.domain.com/parent/new-blog

This works fine in SS 3.1.12. I've upgraded to Silverstripe 3.2.0. Now the URL is:
http://www.domain.com/new-blog

The url of the parent page is missing.

![urlsegmentblog320](https://cloud.githubusercontent.com/assets/15635166/10914487/fa7d1b4c-8252-11e5-8cf5-a47b8d96328f.png)

**Comment by tractorcow** [comment]
Hi @StefanHhe 

I believe this is related to the issue noted at https://github.com/silverstripe/silverstripe-lumberjack/pull/13.

We're looking to release a new version of blog and lumberjack in the next week or two, so we'll try to make sure this is resolved then.

Do you want to try the fix noted in the pull request to see if it resolves your issue? (You may need to use my fork until it's merged).

**Comment by StefanHhe** [comment]
Thanks, the fix works!!!
