### ISSUE TITLE
$MonthyArchiveLink doesn't return month

### ISSUE THREAD

**Issue by mandrew** [silverstripe/silverstripe-blog#323]
For some reason this is set to day by default. If I set to month in the template by using $MonthyArchiveLink('month') then it still returns day :-1: 
Function: https://github.com/silverstripe/silverstripe-blog/blob/master/code/model/BlogPost.php#L549

**Comment by tractorcow** [comment]
That's because the method is terrible.

Use `$getMonthlyArchiveLink('var')` to specify a different period type.

**Comment by micmania1** [comment]
The reason for this is that the `$MonthlyArchiveLink` method doesn't exist so it falls back to using PHPs magic `__get()` method to call `getMonthlyArchiveLink` which doesn't pass parameters along. This is intended behaviour in framework.

Ref:
https://github.com/silverstripe/silverstripe-framework/pull/2492
https://github.com/silverstripe/silverstripe-framework/issues/2505

**Comment by mandrew** [comment]
Should it exist though? $YearlyArchiveLink works and doesn't need the get method to call it. I would see them as complimentary and so they should be called the same

**Comment by tractorcow** [comment]
Because YearlyArchiveLink doesn't have parameters. :)
