### ISSUE TITLE
Fatal error: Using $this when not in object context in blog/code/model/BlogPost.php on line 216

### ISSUE THREAD

**Issue by luukgruijs** [silverstripe/silverstripe-blog#324]
Hi guys,

i'm facing this error. Does anybody have an idea?

Fatal error: Using $this when not in object context in blog/code/model/BlogPost.php on line 216

Thanks in advance.

**Comment by kinglozzer** [comment]
Looks like a bug, it should be `$self->getCandidateAuthors()...` as we still need to support old PHP versions :(

**Comment by luukgruijs** [comment]
Thank you, that indeed solved my problem.

**Comment by dhensby** [comment]
Is a PR needed for this?

**Comment by 3Dgoo** [comment]
I've submitted a pull request that fixes this: #340

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-blog/pull/341
