### ISSUE TITLE
Blog has to be at the top level of the Sitetree

### ISSUE THREAD

**Issue by MichaelJJames** [silverstripe/silverstripe-blog#342]
Blog has to be at the top level of the Sitetree or it causes a redirect loop

**Comment by dhensby** [comment]
Do you mean at the root of the site tree?

**Comment by MichaelJJames** [comment]
Hi Dan, 

Yeah it has to be at the root

Thanks 
Michael

**Comment by jameshoward** [comment]
I have a blog at a 2nd level (e.g. `/about/blog`) and it's working fine. Could it be an issue with `allowed_children` on the parent page type you're trying to add the blog to?

**Comment by tractorcow** [comment]
This is probably caused by https://github.com/silverstripe/silverstripe-lumberjack/pull/13, and is fixed now with lumberjack 1.1.3.
