### ISSUE TITLE
Create a Query for Blog posts filtered by specific category help!

### ISSUE THREAD

**Issue by dleinbach** [silverstripe/silverstripe-blog#346]
Can anyone help we with a function that queries blog posts filtered by category?
  I have pages that need to query the most recent posts by category set by the page.
Thanks so much

**Comment by micmania1** [comment]
@dleinbach you can view posts filtered by category in blog 2.x by going /[blog-url]/category/[category-url]

You can see the code for how to filter by categories here: https://github.com/silverstripe/silverstripe-blog/blob/master/code/model/Blog.php#L870
