### ISSUE TITLE
Error when running BlogMigrationTask

### ISSUE THREAD

**Issue by toddvalentine** [silverstripe/silverstripe-blog#347]
I am upgrading from v1.0 to v2.3. I have tried running the MigrateBlogTask, but I keep hitting this error: 

[User Error] Uncaught Exception: Object->__call(): the method 'publish' does not exist on 'BlogHolder'
GET /dev/tasks/BlogMigrationTask
Line 739 in /var/www/html/mysite/framework/core/Object.php

Does anyone have any thoughts? As is, my blog is showing no entries after upgrading.

**Comment by camfindlay** [comment]
@toddvalentine just as a quick gotcha avoidance, make sure you dont run the migration on your live server. Good idea to get a copy of your database and do this migration on a test server or locally if you can.

Something else you might be able to try is the I have a work in progress of a new migration script you could try out at https://github.com/silverstripe/silverstripe-blog/pull/315 - still needs some tidy up and documentation but might be useful code (if you end up using this please let me know how it goes). 

That error is something I hit and why I ended up rewriting the migration script currently under review in the pull request mentioned.

**Comment by thirdmanrecords** [comment]
Thanks Cam. Was testing locally when I hit the error, so all good! I will check out the new migration script and let you know. Looking forward to getting the v3.2/ss-blog updates in place!
