### ISSUE TITLE
RSS links on blog posts dont work

### ISSUE THREAD

**Issue by nzjoel** [silverstripe/silverstripe-blog#35]
The RSS links at the bottom of each blog post dont appear to work. The "RSS feed for comments on this page" one goes to the home page and the "RSS feed for all comments" one goes to a "Page not found" page.

![rss links](https://www.evernote.com/shard/s14/sh/3355d03d-6fa4-4a12-a0f1-1e36e8eebcf4/fd21af985f03c1e57e04dbcc9a53083d/res/121ea408-311d-48c1-b608-245245dc2719/New_BlogEntry_%C2%BB_Your_Site_Name-20120713-153016.jpg.png)

**Comment by assertchris** [comment]
This is no longer an issue in `dev-master`.
