### ISSUE TITLE
BUG: Can't not revert to historic versions

### ISSUE THREAD

**Issue by vinh63** [silverstripe/silverstripe-blog#353]
When I revert a blog post to a previous historic version, it is not actioned.

**Comment by tractorcow** [comment]
Is this a version that existed prior to upgrade to 2.x?

**Comment by vinh63** [comment]
No, it was a version created after the upgrade. In short, I cannot revert to any previous versions or the "revert" function is not working at all.

**Comment by dhensby** [comment]
This should be fixed in 3.3

I believe this is a regression in `LookupField` not having an appropriate validation function:

Original PR causing regression: https://github.com/silverstripe/silverstripe-framework/pull/3636

Patch https://github.com/silverstripe/silverstripe-framework/pull/4897

**Comment by dhensby** [comment]
This should not be a bug with 3.1

**Comment by dhensby** [comment]
Hmm, I just tested on 3.1.x-dev, 3.2.x-dev, 3.x-dev and couldn't replicate - perhaps this is fine in 3.2, then?

**Comment by micmania1** [comment]
Maybe this is related to custom code. Do you get an error or anything when you try to revert?

**Comment by vinh63** [comment]
No error.

On 27 January 2016 at 14:30, Michael Strong <notifications@github.com>
wrote:

> Maybe this is related to custom code. Do you get an error or anything when
> you try to revert?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/silverstripe/silverstripe-blog/issues/353#issuecomment-175330615>
> .
>



-- 

Vinh Nguyen | Marketing Coordinator
SilverStripe
http://silverstripe.com/

Phone: +64 4 978 7330 ext 72

**Comment by dhensby** [comment]
@micmania1 this can be replicated on the CWP demos

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4968

wait until 3.2.2 or use 3.2.x-dev
