### ISSUE TITLE
Previous and Next post options

### ISSUE THREAD

**Issue by Tim1701** [silverstripe/silverstripe-blog#355]
I preface this by acknowledging my relative inexperience with Silverstripe, and perhaps this is a very simple thing already accounted for somewhere.

Nevertheless, I'm having a hell of a time adapting the previous/next link functions I'd been using with the older Blog module to work with this one. Nothing seems to work. The goal is, when viewing a blog post singly, to have links to the immediately previous and next post items. With the old module, this worked:
(In BlogEntry.php)
	`public function NextPost() {
		return BlogEntry::get()->filter('Date:GreaterThan',$this->Date)->sort('Date', 'ASC')->limit(1)->first();
		}`
	`public function PreviousPost() {
		return BlogEntry::get()->filter('Date:LessThan',$this->Date)->sort('Date', 'DESC')->limit(1)->first();
		}`

(In BlogEntry.ss)
   ` <% if $PreviousPost %>
	<% with $PreviousPost %>
	<a href="$Link" title="Go to $Title">&#171; Prev</a>
	<% end_with %>
    <% end_if %>`
  ` <% if $NextPost %>
	<% with $NextPost %>
	<a href="$Link" title="Go to $Title">Next &#187; </a>
	<% end_with %>
    <% end_if %>`

Adapting this to account for the different page types and database labels used in the new module hasn't worked, nothing seems to be returned for the $Link and $Title entities. I've tried many variations on this, different functions, no joy. So, am I missing something incredibly obvious here, or is there a bug somewhere?

**Comment by stevie-mayhew** [comment]
You can add an extension to `BlogPost_Controller` with the following which works:

```php
/**
     * @return DataObject
     */
    public function getNextPost()
    {
        return BlogPost::get()
            ->filter(array(
                'ParentID' => $this->owner->ParentID,
                'PublishDate:GreaterThanOrEqual' => $this->owner->PublishDate
            ))
            ->exclude(array('ID' => $this->owner->ID))
            ->sort('PublishDate', 'ASC')
            ->first();
    }

    /**
     * @return DataObject
     */
    public function getPreviousPost()
    {
        return BlogPost::get()
            ->filter(array(
                'ParentID' => $this->owner->ParentID,
                'PublishDate:LessThanOrEqual' => $this->owner->PublishDate
            ))
            ->exclude(array('ID' => $this->owner->ID))
            ->sort('PublishDate', 'DESC')
            ->first();
    }
```

**Comment by Tim1701** [comment]
Thanks -- that does work. Can't quite pin down what is different here than in some of the variants i tried before, perhaps I neglected "get" in the functions. In any event, much obliged; SS is a fine platform, I knew there would be some way to get it working. :+1:
