### ISSUE TITLE
ENHANCEMENT: Open Graph

### ISSUE THREAD

**Issue by camfindlay** [silverstripe/silverstripe-blog#359]
Since users of blogging often like to promote article on social media it would be good if the blog module provided open graph meta data for posts. http://ogp.me/

**Comment by jonom** [comment]
This might be better applied to a whole website rather than just the blog pages. https://github.com/tractorcow/silverstripe-opengraph can be added on to set this up, or for a pre-configured variation with share features in the CMS you could try https://github.com/jonom/silverstripe-share-care

**Comment by camfindlay** [comment]
Good point! thanks @jonom

**Comment by tractorcow** [comment]
Oh no, that old thing. :)

Well, it still works! :D
