### ISSUE TITLE
Subject Header for Blog Post Notification Missing BlogPost Title

### ISSUE THREAD

**Issue by gordonbanderson** [silverstripe/silverstripe-blog#364]
The offending line is https://github.com/silverstripe/silverstripe-blog/blob/master/code/extensions/BlogPostNotifications.php#L30 - it's missing a %s to substitute the BlogPost title into

**Comment by gordonbanderson** [comment]
Fix here https://github.com/gordonbanderson/silverstripe-blog/commit/687406dea8770bb9d00df856d00c317f1d6a273d but I'll let Travis run it's thing first prior to issuing pull request.

**Comment by micmania1** [comment]
Thanks for the fix :+1:
