### ISSUE TITLE
Link() / URLSegment Incorrect when Blog is Child

### ISSUE THREAD

**Issue by Spambanjo** [silverstripe/silverstripe-blog#368]
If Blog is a child of another page, Link() is returned without the parents' URLSegments

**Comment by micmania1** [comment]
@Spambanjo thanks for reporting. Can you tell me which version of blog you're using?

**Comment by Spambanjo** [comment]
I was using a version I've heavily modified when I noticed it the first time, I'm not in the office now so I can't tell you which version that is exactly. I downloaded the master branch and tried a fresh install but the same thing happened.

**Comment by tractorcow** [comment]
What version of lumberjack are you using? It sounds like the old ParentID bug we had fixed recently.

See https://github.com/silverstripe/silverstripe-lumberjack/pull/13

**Comment by Spambanjo** [comment]
Lumberjack 1.1. I looked at the thread you linked and it seems identical to one of the replies. https://github.com/silverstripe/silverstripe-blog/issues/316

I'm in the UK so it's getting late, I'll give it another look first thing tomorrow, hopefully you're right. Thanks for your help so far

**Comment by tractorcow** [comment]
The fix should be tagged in 1.1.3, so just make sure you're using that version at least.

**Comment by Spambanjo** [comment]
Excellent, that's the problem for sure. I should have selected the master branch instead of the 1.1 when I reinstalled it today. Thanks again!

**Comment by tractorcow** [comment]
1.1.x-dev should have been fine.

**Comment by tractorcow** [comment]
Both 1.1 and master branches on lumberjack will have this fix.

**Comment by tractorcow** [comment]
Closing since this is a lumberjack issue not a blog one, in any case. :) And also because it's been fixed. ;P

**Comment by Spambanjo** [comment]
Unfortunately updating to version 1.1.3 of lumberjack did not solve the problem. I've tested all other page types in my project by adding them as a child of another page and all of them (including BlogPost) create their Link() correctly on the front end.

Blog does not create the link correctly, skipping the parent's URLSegment. You can quickly see evidence of this on the URLSegment field's preview text.

**Comment by tractorcow** [comment]
Did you check that you'd removed the ParentID DB field? Even if it's not in the datamodel, it could affect queries.

**Comment by tractorcow** [comment]
Re-open for now, since it's not apparently so cut and dry. :)

**Comment by Spambanjo** [comment]
Thanks TC, this was PEBCAK. I reinstalled lumberjack then implemented the changes @ https://github.com/silverstripe/silverstripe-lumberjack/pull/13/files#diff-ab68ac84f26307fec09e052f475d2de1L84 again carefully and everything seems to be working fine now.

Thanks for all your help.
