### ISSUE TITLE
Unable to Archieve without internal error

### ISSUE THREAD

**Issue by helenclarko** [silverstripe/silverstripe-blog#374]
Error that is generated.

ERROR [Notice]: Array to string conversion
IN POST /admin/pages/edit/EditForm
Line 175 in /var/www/vhosts/domain.com/httpdocs/framework/forms/DropdownField.php

Same issue as https://github.com/silverstripe/silverstripe-framework/issues/4835 
Which has been attached to Silverstripe/Framework.

**Comment by micmania1** [comment]
@helenclarko can you provide a full backtrace?

**Comment by helenclarko** [comment]
@micmania1, hopefully this works.

[Notice] Array to string conversion
GET /admin/pages/edit/show/27?isDevtoken=af19d0edb0ac916c515fd9473f4b5727&isDev=1

Line 175 in G:\xampp\htdocs\framework\forms\DropdownField.php
Source

166 			foreach($source as $value => $title) {
167 				$selected = false;
168 				if($value === '' && ($this->value === '' || $this->value === null)) {
169 					$selected = true;
170 				} else {
171 					// check against value, fallback to a type check comparison when !value
172 					if($value) {
173 						$selected = ($value == $this->value);
174 					} else {
175 						$selected = ($value === $this->value) || (((string) $value) === ((string) $this->value));
176 					}
177 
178 					$this->isSelected = $selected;
179 				}
180 
181 				$disabled = false;

Trace

    DropdownField->Field(Array)
    LookupField.php:79
    LookupField->Field()
    ViewableData.php:402
    ViewableData->obj(Field,,,1)
    ViewableData.php:475
    ViewableData->XML_val(Field,,1)
    call_user_func_array(Array,Array)
    SSViewer.php:179
    SSViewer_Scope->__call(XML_val,Array)
    SSViewer.php:550
    SSViewer_DataPresenter->__call(XML_val,Array)
    .cache.framework.templates.forms.FormField_holder.ss:31
    SSViewer_DataPresenter->XML_val(Field,,1)
    .cache.framework.templates.forms.FormField_holder.ss:31
    include(C:\Users\Sam\AppData\Local\Temp\silverstripe-cache-php5.5.15G--xampp-htdocs\Sam\.cache.framework.templates.forms.FormField_holder.ss)
    SSViewer.php:1059
    SSViewer->includeGeneratedTemplate(C:\Users\Sam\AppData\Local\Temp\silverstripe-cache-php5.5.15G--xampp-htdocs\Sam/.cache.framework.templates.forms.FormField_holder.ss,LookupField,,Array,)
    SSViewer.php:1119
    SSViewer->process(LookupField,)
    ViewableData.php:341
    ViewableData->renderWith(Array)
    FormField.php:865
    FormField->FieldHolder()
    ViewableData.php:402
    ViewableData->obj(FieldHolder,,,1)
    ViewableData.php:475
    ViewableData->XML_val(FieldHolder,,1)
    call_user_func_array(Array,Array)
    SSViewer.php:179
    SSViewer_Scope->__call(XML_val,Array)
    SSViewer.php:550
    SSViewer_DataPresenter->__call(XML_val,Array)
    .cache.blog.templates.BlogAdminSidebar_holder.ss:25
    SSViewer_DataPresenter->XML_val(FieldHolder,,1)
    .cache.blog.templates.BlogAdminSidebar_holder.ss:25
    include(C:\Users\Sam\AppData\Local\Temp\silverstripe-cache-php5.5.15G--xampp-htdocs\Sam\.cache.blog.templates.BlogAdminSidebar_holder.ss)
    SSViewer.php:1059
    SSViewer->includeGeneratedTemplate(C:\Users\Sam\AppData\Local\Temp\silverstripe-cache-php5.5.15G--xampp-htdocs\Sam/.cache.blog.templates.BlogAdminSidebar_holder.ss,BlogAdminSidebar,,Array,)
    SSViewer.php:1119
    SSViewer->process(BlogAdminSidebar,)
    ViewableData.php:341
    ViewableData->renderWith(Array)
    FormField.php:865
    FormField->FieldHolder()
    ViewableData.php:402
    ViewableData->obj(FieldHolder,,,1)
    ViewableData.php:475
    ViewableData->XML_val(FieldHolder,,1)
    call_user_func_array(Array,Array)
    SSViewer.php:179
    SSViewer_Scope->__call(XML_val,Array)
    SSViewer.php:550
    SSViewer_DataPresenter->__call(XML_val,Array)
    .cache.cms.templates.Includes.CMSMain_EditForm.ss:58
    SSViewer_DataPresenter->XML_val(FieldHolder,,1)
    .cache.cms.templates.Includes.CMSMain_EditForm.ss:58
    include(C:\Users\Sam\AppData\Local\Temp\silverstripe-cache-php5.5.15G--xampp-htdocs\Sam\.cache.cms.templates.Includes.CMSMain_EditForm.ss)
    SSViewer.php:1059
    SSViewer->includeGeneratedTemplate(C:\Users\Sam\AppData\Local\Temp\silverstripe-cache-php5.5.15G--xampp-htdocs\Sam/.cache.cms.templates.Includes.CMSMain_EditForm.ss,CMSForm,,Array,)
    SSViewer.php:1119
    SSViewer->process(CMSForm,)
    ViewableData.php:341
    ViewableData->renderWith(Array)
    Form.php:1550
    Form->forTemplate()
    ViewableData.php:476
    ViewableData->XML_val(EditForm,,1)
    call_user_func_array(Array,Array)
    SSViewer.php:179
    SSViewer_Scope->__call(XML_val,Array)
    SSViewer.php:550
    SSViewer_DataPresenter->__call(XML_val,Array)
    .cache.cms.templates.Includes.CMSMain_Content.ss:92
    SSViewer_DataPresenter->XML_val(EditForm,,1)
    .cache.cms.templates.Includes.CMSMain_Content.ss:92
    include(C:\Users\Sam\AppData\Local\Temp\silverstripe-cache-php5.5.15G--xampp-htdocs\Sam\.cache.cms.templates.Includes.CMSMain_Content.ss)
    SSViewer.php:1059
    SSViewer->includeGeneratedTemplate(C:\Users\Sam\AppData\Local\Temp\silverstripe-cache-php5.5.15G--xampp-htdocs\Sam/.cache.cms.templates.Includes.CMSMain_Content.ss,CMSPageEditController,,Array,)
    SSViewer.php:1119
    SSViewer->process(CMSPageEditController,)
    ViewableData.php:341
    ViewableData->renderWith(Array)
    LeftAndMain.php:722
    LeftAndMain->Content()
    ViewableData.php:402
    ViewableData->obj(Content,,,1)
    ViewableData.php:475
    ViewableData->XML_val(Content,,1)
    call_user_func_array(Array,Array)
    SSViewer.php:179
    SSViewer_Scope->__call(XML_val,Array)
    SSViewer.php:550
    SSViewer_DataPresenter->__call(XML_val,Array)
    .cache.framework.admin.templates.LeftAndMain.ss:41
    SSViewer_DataPresenter->XML_val(Content,,1)
    .cache.framework.admin.templates.LeftAndMain.ss:41
    include(C:\Users\Sam\AppData\Local\Temp\silverstripe-cache-php5.5.15G--xampp-htdocs\Sam\.cache.framework.admin.templates.LeftAndMain.ss)
    SSViewer.php:1059
    SSViewer->includeGeneratedTemplate(C:\Users\Sam\AppData\Local\Temp\silverstripe-cache-php5.5.15G--xampp-htdocs\Sam/.cache.framework.admin.templates.LeftAndMain.ss,CMSPageEditController,,Array,)
    SSViewer.php:1119
    SSViewer->process(CMSPageEditController,)
    ViewableData.php:341
    ViewableData->renderWith(SSViewer)
    LeftAndMain.php:599
    LeftAndMain->{closure}()
    call_user_func(Closure)
    PjaxResponseNegotiator.php:82
    PjaxResponseNegotiator->respond(SS_HTTPRequest)
    LeftAndMain.php:576
    LeftAndMain->show(SS_HTTPRequest)
    RequestHandler.php:288
    RequestHandler->handleAction(SS_HTTPRequest,show)
    Controller.php:200
    Controller->handleAction(SS_HTTPRequest,show)
    RequestHandler.php:200
    RequestHandler->handleRequest(SS_HTTPRequest,DataModel)
    Controller.php:157
    Controller->handleRequest(SS_HTTPRequest,DataModel)
    LeftAndMain.php:451
    LeftAndMain->handleRequest(SS_HTTPRequest,DataModel)
    AdminRootController.php:93
    AdminRootController->handleRequest(SS_HTTPRequest,DataModel)
    Director.php:385
    Director::handleRequest(SS_HTTPRequest,Session,DataModel)
    Director.php:149
    Director::direct(/admin/pages/edit/show/27,DataModel)
    main.php:184

**Comment by helenclarko** [comment]
Steps to reproduce:

    create a new blog post
    go to /admin/pages and open the blog post to edit it
    archive (delete) the blog post
    you should see the error message in the browser inspector network tab
    you can see the error again by trying to access the deleted page by manually specifying the url (e.g. /admin/pages/edit/show/92)

Thanks.

**Comment by helenclarko** [comment]
Seems to be an issue with TagField::create under $options = BlogAdminSidebar::create of BlogPost.php

**Comment by helenclarko** [comment]
Commenting out, like the following seems to work:
`
// TagField::create(
                    // 'Categories',
                    // _t('BlogPost.Categories', 'Categories'),
                    // $categories,
                    // $self->Categories()
                // )
                    // ->setCanCreate($self->canCreateCategories())
                    // ->setShouldLazyLoad(true),
                // TagField::create(
                    // 'Tags',
                    // _t('BlogPost.Tags', 'Tags'),
                    // $tags,
                    // $self->Tags()
                // )
                    // ->setCanCreate($self->canCreateTags())
                    // ->setShouldLazyLoad(true),
`

**Comment by tractorcow** [comment]
We've recently made a change to framework to resolve issues with restoring from archive; We probably need to add the same fix for archive.

https://github.com/silverstripe/silverstripe-cms/pull/1378
 
Want to test that adding the archive action resolves your issue?

**Comment by micmania1** [comment]
So in terms of a fix for blog, what do we want to do? The options I see are:

- Update composer requirements for cms/framework to the fixed version(s) as a minimum
- Patch blog to support broken versions of framework/cms
- Do nothing and tell people to upgrade if they report this issue again

I don't really have a strong preference - would anybody object to blog dictating the minimum framework or cms version in a patch release? I don't believe semver covers that scenario.

**Comment by helenclarko** [comment]
@tractorcow 
The changed to CMSMain have not solved this issue.

**Comment by tractorcow** [comment]
@helenclarko did you add in 'archive' to the cms main exemptions, or did you mean that the prior change didn't fix it? I'm suggesting a new fix, not that the prior one was sufficient. :)

**Comment by micmania1** [comment]
@helenclarko is this still an issue?

**Comment by micmania1** [comment]
I've tested this and archiving is working as expected in the latest stable releases of blog/framework/cms. Feel free to re-open if the problem persists.
