### ISSUE TITLE
Conflict with GridFieldConfig_Lumberjack

### ISSUE THREAD

**Issue by Spambanjo** [silverstripe/silverstripe-blog#375]
The latest GridFieldConfig_Lumberjack.php adds the component GridFieldSiteTreeAddNewButton. This causes an error when adding or modifying members from the Security page.

A temp fix is to modify around line 102 in **blog/code/extensions/BlogMemberExtension.php** from:

```
$gridField = new GridField(
  'BlogPosts',
  'Blog Posts',
  $this->owner->BlogPosts(),
  new GridFieldConfig_BlogPost()
);
```

Replacing it with:

```
$conf = new GridFieldConfig_BlogPost();
$conf->removeComponentsByType('GridFieldSiteTreeAddNewButton');
$gridField = new GridField(
  'BlogPosts',
  'Blog Posts',
  $this->owner->BlogPosts(),
  $conf
);
```

**Comment by tractorcow** [comment]
Hi @Spambanjo , can you please raise a pull request for this on the blog module?

**Comment by micmania1** [comment]
@Spambanjo I've checked this out but I can't see any error. The GridFieldSiteTreeAddNewButton component shouldn't render anything if there is no parent page as is the case in the security area. See https://github.com/silverstripe/silverstripe-lumberjack/blob/1.1/code/forms/gridfield/GridFieldSiteTreeAddNewButton.php#L49

If this is still a problem for you, can you please let us know what the error is and the steps to re-produce? In the meantime I'll close this but please feel free to re-open.
