### ISSUE TITLE
Non-english tags/categories can create empty URLSegments

### ISSUE THREAD

**Issue by micmania1** [silverstripe/silverstripe-blog#376]
Create a tag with the title ` شخصی و افراد` and save.
Click the tag in the front-end - notice there is no URLSegment and the link leads to 404.

Disclaimer: I have no idea what the example tag says or even what language it is.

**Comment by tractorcow** [comment]
I think this probably needs fixing over at https://github.com/assertchris/silverstripe-segment-field

**Comment by alialamshahi** [comment]
Thanks micmania1,
The language is Farsi, both tags and categories URLSegment don't support non-English letters. I updated database manually but every time I assign a post with a tag or category their value becomes NULL again!

**Comment by micmania1** [comment]
@tractorcow we don't use that in blog. Or do we?

Can anybody tell me how the CMS behaves in this scenario?

**Comment by tractorcow** [comment]
The normal CMS Is theoretically ment to support extended characters, if URLSegmentFilter.default_allow_multibyte is on. However, this is for pages only, not tags / categories.

It would be good if segment-field extension also followed this rule. ;)

**Comment by alialamshahi** [comment]
Any updates on this issue? I'm still editing URLSegments in the database manually (through PHPadmin), every time a category or a tag are used in a blog post their URLSegments becomes NULL again!

**Comment by micmania1** [comment]
@alialamshahi can you check out #402 and let me know if this resolves your issue?

**Comment by alialamshahi** [comment]
@micmania1 works just fine! thanks a million!

**Comment by Misagh90** [comment]
Hi,
@micmania1 @alialamshahi 
It's happen even in blog_profile.ss for Author, the url goes to 404 page in Persian (Farsi).
