### ISSUE TITLE
Issue with Translatable

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-blog#378]
When I create a translated version of the Blog (e.g. from English to Spanish), and then create a new BlogPost under this es-ES Blog, then the BlogPost will be saved as en-US, despite having a es-ES Parent. The result is that the BlogPost doesn't appear anywhere (it appears temporarily in the site tree, but not in the Lumberjack gridfield of the Blog), and the user is left very confused :)

I am not sure whether this is a Blog or Translatable issue; I'm putting it here in the assumption that Translatable is more generic, and perhaps Blog is accidently overwriting or preventing something. 

I tried this with Blog 2.4.0 and Translatable 2.1.1. 

Until there is a fix, the issue can be circumvented with an Extension:
```php
class BlogPostExtension extends SiteTreeExtension {
	public function onBeforeWrite()
	{
		parent::onBeforeWrite();

		if($this->getOwner()->hasExtension('Translatable')) {
			$this->getOwner()->Locale = $this->getOwner()->Parent()->Locale;
		}
	}
}
```

**Comment by tractorcow** [comment]
We should probably roll this fix into lumberjack.

**Comment by micmania1** [comment]
Does this behave correctly if you right click the blog in the site tree and create a new blog post?

**Comment by JorisDebonnet** [comment]
Yeah, it does. I imagine the SiteTree objects are created in exactly the same way anyway, right?

I'll see if I can find where in Lumberjack this would need to go - although it still feels a bit like a workaround rather than a real fix. But perhaps that's because I don't really know how Translatable works under the hood, exactly.

**Comment by JorisDebonnet** [comment]
I have now fixed this in Lumberjack: 
https://github.com/silverstripe/silverstripe-lumberjack/pull/32
