### ISSUE TITLE
Issue with Add New Blog Post Button

### ISSUE THREAD

**Issue by sajansharmanz** [silverstripe/silverstripe-blog#380]
Hey guys,

Using Silverstripe CMS 3.3 and Silverstripe Framework 3.3 (Latest default composer install) the Add New Blog Post button is creating an error when clicked, the following is what it says

> _There seems to have been a technical problem. Please click the back button, refresh your browser, and try again._

However, adding a blog post works fine when you right click in the site tree and select add new page here -> Blog Post

**Comment by lekoala** [comment]
I have the same issue on 3.1.17. It's seems linked to a lack or an invalid security token for the gridfield.

**Comment by lekoala** [comment]
to be more precise, it's probably due to this change

https://github.com/silverstripe/silverstripe-framework/commit/013524af5069bb0cf909853f04418d9bef56d18c

**Comment by mikeyc7m** [comment]
bump!
reverting to 3.1.16 worked for me too.

**Comment by dhensby** [comment]
@lekoala yep, I think that's the change that is causing the problem. The button needs to make sure the security token is being sent to the server otherwise it's vulnerable to XSS - that commit is a security patch

@tractorcow is this a core problem, a lumberjack one or a blog one?

**Comment by siteleas** [comment]
Thank you for this update. I am having this problem since 3.3 upgrade as well.

**Comment by tractorcow** [comment]
Probably lumberjack... will look at it now.

**Comment by tractorcow** [comment]
Looks like we need new framework releases... https://github.com/silverstripe/silverstripe-framework/pull/5099

**Comment by tractorcow** [comment]
Plan is to patch and release 3.3.0-rc1, 3.2.3-rc1 and 3.1.18-rc1 with this fix, since it's been patched across all versions.

**Comment by siteleas** [comment]
Which one will be the one to use with SilverStripe 3.3?

**Comment by tractorcow** [comment]
Oh, once 3.3.1 is out you can use any version of blog. It'll be a bugfix to framework not to blog or lumberjack.

**Comment by tractorcow** [comment]
fixed with https://github.com/silverstripe/silverstripe-framework/pull/5099
