### ISSUE TITLE
RSS feeds for Categories and Tags

### ISSUE THREAD

**Issue by sekjal** [silverstripe/silverstripe-blog#382]
RSS feeds only work for an entire Blog at this time; the only way then to have multiple feeds based on interest is to create multiple blogs.  Having tag and category specific feeds would help users subscribe to only the content they want to see, and increase the possibilities for automation using third-party tools like IFTTT or Zapier.

**Comment by micmania1** [comment]
This would be a welcomed feature. Do you have the time to create a PR?

**Comment by sekjal** [comment]
Yes, I should within the next few weeks.

**Comment by hdrlab** [comment]
Yes, this would be a welcome feature. I was just searching for how to get an RSS feed for categories. My goal is to allow users to signup for email updates for specific topics (categories). Per-category RSS feeds would be ideal for allowing each topic to get the right articles.

**Comment by tractorcow** [comment]
You could update the `rss` action to allow `category` or `tag` to be assigned the `$ID` param, where the urlsegment of the category or tag could be the `$OtherID` parameter.

@sekjal are you looking closer to this pull request?

**Comment by sekjal** [comment]
Unfortunately, I've been pulled away in the last couple months on other urgent projects.  I'm hoping to get to this in June, but if anyone else wants to take a stab at it first, I'd be happy to test.

**Comment by micmania1** [comment]
Added in #407
