### ISSUE TITLE
2.4.0 breaks SS framework unit tests

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-blog#386]
Hi there,

I've installed SS 3.3.1 with the CMS and a couple of other official addons, including this one (2.4.0).

Now when I run `phpunit` in my environment I get this error:

```bash
# phpunit --list-groups                                                      
ERROR [User Error]: Uncaught ReflectionException: Class BlogMemberExtension does not exist
IN GET /dev
Line 281 in /var/www/framework/core/ClassInfo.php

Source
======
  272: 	public static function has_method_from($class, $method, $compclass) {
  273: 		$lClass = strtolower($class);
  274: 		$lMethod = strtolower($method);
  275: 		$lCompclass = strtolower($compclass);
  276: 		if (!isset(self::$method_from_cache[$lClass])) self::$method_from_cache[$lClass] = array();
  277: 
  278: 		if (!array_key_exists($lMethod, self::$method_from_cache[$lClass])) {
  279: 			self::$method_from_cache[$lClass][$lMethod] = false;
  280: 
* 281: 			$classRef = new ReflectionClass($class);
  282: 
  283: 			if ($classRef->hasMethod($method)) {
  284: 				$methodRef = $classRef->getMethod($method);
  285: 				self::$method_from_cache[$lClass][$lMethod] = $methodRef->getDeclaringClass()->getName();
  286: 			}
  287: 		}

Trace
=====
ReflectionClass->__construct(BlogMemberExtension)
ClassInfo.php:281

ClassInfo::has_method_from(BlogMemberExtension,add_to_class,Extension)
Object.php:641

Object::get_extra_config_sources(Member)
Config.php:518

Config->getUncached(Member,log_last_visited,0,,,Array)
Config.php:591

Config->get(Member,log_last_visited)
Config.php:886

Config_ForClass->__get(log_last_visited)
Controller.php:75

Controller->init()
FakeController.php:23

FakeController->__construct()
bootstrap.php:59

include_once(/var/www/framework/tests/bootstrap.php)
Fileloader.php:92

PHPUnit_Util_Fileloader::load(/var/www/framework/tests/bootstrap.php)
Fileloader.php:76

PHPUnit_Util_Fileloader::checkAndLoad(/var/www/framework/tests/bootstrap.php)
Command.php:778

PHPUnit_TextUI_Command->handleBootstrap(/var/www/framework/tests/bootstrap.php)
Command.php:606

PHPUnit_TextUI_Command->handleArguments(Array)
Command.php:138

PHPUnit_TextUI_Command->run(Array,1)
Command.php:129

PHPUnit_TextUI_Command::main()
phpunit:619
```

I've re-build etc, have I missed something?

**Comment by tractorcow** [comment]
Try flushing on the CLI during tests. The class should be here https://github.com/silverstripe/silverstripe-blog/blob/0a8ee233a601f81f5264fbfbcc7e7c4c4b77ea32/code/extensions/BlogMemberExtension.php, so I guess the manifest just needs cleaning?

`./vendor/bin/phpunit ./blog/tests '' 'flush=all'`

**Comment by robbieaverill** [comment]
@tractorcow magic - plenty of other issues popping up now, but this is great. Thanks!

**Comment by tractorcow** [comment]
That's ok, just ping me with whatever you get stuck on. :)

**Comment by tractorcow** [comment]
It'll be great once we move to psr-4 and can autoload classes without having to flush...

**Comment by robbieaverill** [comment]
Much appreciated! Side note - would a move to psr-4 mean adopting a new style guideline...?

**Comment by tractorcow** [comment]
We are adopting psr-2 a lot earlier than psr-4, so yes. :D

**Comment by robbieaverill** [comment]
Lovely. I'm sure there's a method to the madness, but coming from a tidy Zend standard in the Magento world to the SS standard was a bit of a 180 degree shift/shock!

**Comment by tractorcow** [comment]
Well willing to accept critique. :D

**Comment by robbieaverill** [comment]
I would love to provide some constructive criticism- will email you

On Monday, 7 March 2016, Damian Mooyman <notifications@github.com> wrote:

> Well willing to accept critique. :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/silverstripe/silverstripe-blog/issues/386#issuecomment-193088797>
> .
>


-- 
*Robbie Averill*
LA PETITE MANOUCHE - NZ Gypsy Jazz Guitar Duo
Phone: +64 27 321 4758
contact@lapetitemanouche.com
www.lapetitemanouche.com
