### ISSUE TITLE
DropdownField warning when trying to save a BlogPost

### ISSUE THREAD

**Issue by IrinaStr** [silverstripe/silverstripe-blog#387]
I get the error 'Warning at line 337 of /home/www/html-data/dev/silverstripe/framework/forms/DropdownField.php' when trying to save a BlogPost. I'm using SS 3.3.1 and have installed the blog module via "composer require silverstripe/blog 2.0.x-dev".

Any ideas what might be wrong?

**Comment by kinglozzer** [comment]
You’ll need to install version 2.1.0 or higher (see https://github.com/silverstripe/silverstripe-blog/issues/293)

**Comment by IrinaStr** [comment]
I see, thanks!
