### ISSUE TITLE
PubDate in RSS feed is wrong

### ISSUE THREAD

**Issue by ksdhans** [silverstripe/silverstripe-blog#394]
The date that ends up in the RSS feed is the post's creation date, and not its publish date. I've worked around this by creating a custom RSSFeed.ss template that replaces:
			<% if $Date %><pubDate>$Date.Rfc822</pubDate>
			<% else %><pubDate>$Created.Rfc822</pubDate><% end_if %>

 with the following:
			<% if $PublishDate %><pubDate>$PublishDate.Rfc822</pubDate>
			<% else_if $Date %><pubDate>$Date.Rfc822</pubDate>
			<% else %><pubDate>$Created.Rfc822</pubDate><% end_if %>

This works, but it would be better if it worked correctly out of the box.

**Comment by dhensby** [comment]
Would you mind opening a PR?

**Comment by ksdhans** [comment]
Not so fast. I could transfer my RSSFeed.ss changes to the main RSSFeed.ss, but that's in silverstripe-framework, and not the blog module. Is modifying RSSFeed.ss in the core really the correct solution for a blog problem?

**Comment by dhensby** [comment]
You can add a template to another module and it *should* override the framework one

**Comment by micmania1** [comment]
I think we'll need a separate template for this. If we overwrite the existing template in Blog then it will affect all RSS feeds which isn't what we want.

If you can create/copy the RSS template to a custom template (ie. BlogRssFeed.ss) with the date updated to publish date then you can use `$rss->setTemplate('BlogRssFeed') here: https://github.com/silverstripe/silverstripe-blog/blob/master/code/model/Blog.php#L1052

**Comment by ksdhans** [comment]
What about adding a getDate() method that returns PublishDate? RSSFeed.ss will use Date if it exists.

**Comment by dhensby** [comment]
Either of those suggestions are good.

**Comment by tractorcow** [comment]
> What about adding a getDate() method that returns PublishDate? RSSFeed.ss will use Date if it exists.

Please PR anyone. :)

**Comment by micmania1** [comment]
See #403
