### ISSUE TITLE
Cannot add nor edit new blog post as categories and tags field generates a dialog box error of "Please select a value within the list provided. Array is not a valid option"

### ISSUE THREAD

**Issue by josephtan** [silverstripe/silverstripe-blog#396]
I am having trouble adding / editing blog post in Silverstripe version 3.3.2.

After downloading and uninstalling Silverstripe 3.3.2 zip file on localhost and installing the blog module with composer as instructed on this git repository I find that I each time I tried to create a blog post the error message "Please select a value within the list provided. Array is not a valid option" always shows up even with categories and tag fields selected or empty as shown on the screenshot below.

![blog-bug](https://cloud.githubusercontent.com/assets/663450/15417474/aeaaf21e-1e99-11e6-87a0-7e6604ba0e5a.jpg)

**Comment by dhensby** [comment]
Hmm. Would https://github.com/silverstripe/silverstripe-framework/pull/5488 fix or cause this?

**Comment by josephtan** [comment]
That is what I I have thought and replaced the code on issue [#5488 Fix for array to string conversion in DropdownField ](https://github.com/silverstripe/silverstripe-framework/pull/5488/commits/7d7800e5e77914b47528f19cc56b65184adf2842).

However I am still getting the same errors as on the screen shot every time I try to create and edit a blog post.

**Comment by dhensby** [comment]
Hmm. Interesting. Needs investigating. Would you be able to debug?

**Comment by josephtan** [comment]
It would take some time to debug.

However what I have currently found out is that the problem was not the Fix for array to string issue.

There is a condition in the validate function of branch 3.3 of the [DropdownField.php](https://github.com/josephtan/silverstripe-framework/blob/3.3/forms/DropdownField.php).

Removing the "!" in the if (!array_key_exists($this->value, $source) || in_array($this->value, $disabled))  **line "337"** enables me to edit and submit my changes. The catch is that when removing the "!" breaks all other dropdown fields within SilverStripe

It may be the DropDownField.php does not accept the input box to be empty.

Its probably the jquery-ui dropdown has not filled up the empty hidden input fields for categories and tags. Hence the error message on the first post.

**Comment by kinglozzer** [comment]
@josephtan The latest version of the tagfield module should prevent that - as it overrides the `validate()` method. Which versions of the blog & tagfield modules are you using?

**Comment by josephtan** [comment]
@kinglozzer Hmm...not entirely sure how to find the versions of each module.

in blog/composer.json I the extra is written as:

```
"extra": {
		"branch-alias": {
			"dev-master": "2.4.x-dev"
		}
	},
```
while on tagfield/composer.json

`"extra": {
		"branch-alias": {
			"dev-develop": "2.0.x-dev"
		}
	}`

does that help? I am saying this is what I have got when composer unpack the modules after I typed down 

`composer require silverstripe/blog 2.0.x-dev` on the terminal screen

**Comment by kinglozzer** [comment]
Hmm, the most up-to-date version of the blog module is 2.4.2, and it looks like you’ve installed 2.0. I think the instructions in README.md need to be updated :/

Can you try editing *your* composer.json (in the document root) and replacing `"silverstripe/blog": "2.0.x-dev"` with `"silverstripe/blog": "^2.4"`, then run `composer update`? That should bring in the latest version of the module which should hopefully fix this issue for you

**Comment by dhensby** [comment]
Thanks @kinglozzer
