### ISSUE TITLE
Is There any email notification for Blog 

### ISSUE THREAD

**Issue by Misagh90** [silverstripe/silverstripe-blog#408]
Hi,
Is there any automatic Email notification when Contributors create a new blog post to send Editors to approve and publish the post?

Thanks

**Comment by micmania1** [comment]
Nope, blog doesn't support this kind of functionality out of the box. You can try https://github.com/silverstripe-australia/silverstripe-advancedworkflow which is probably what you're after.

**Comment by tractorcow** [comment]
You could probably hack in something based off https://github.com/silverstripe-labs/comment-notifications, although that's just for comments.
