### ISSUE TITLE
Double encoded html entities in excerpt

### ISSUE THREAD

**Issue by teeli** [silverstripe/silverstripe-blog#413]
It seems that & character (possible others, but not all entities) is double encoded (`&amp;amp;`) in the blog post excerpt. It works in summary and content, but not in the excerpt generated from content.

**Comment by teeli** [comment]
framework/cms 3.4.0
blog 2.4.3

**Comment by dhensby** [comment]
Thanks - the problem is that the blog excerpt is being cast as Text instead of HTMLText.

Before a patch is released you can fix this problem by adding this to your `mysite/_config/config.yml`:

```yml
BlogPost:
  casting:
    Excerpt: HTMLText
```
