### ISSUE TITLE
timeout issue

### ISSUE THREAD

**Issue by ctx2002** [silverstripe/silverstripe-blog#416]
Hi:
I am use this module with subsite module (https://github.com/silverstripe/silverstripe-subsites).

whenever I want to create a new blog post, it show me "504 Gateway Time-out" error 
 ([error] 2386#0: *6 upstream timed out (110: Connection timed out) while reading response header from upstream,)

I can not figure out what is problem, do you guys think is this related to subsite module?
or is the problem related to TagField module? ajax call take ages, and return "504 Gateway" error

my web server is nginx 1.8

**Comment by andrewandante** [comment]
Hi! How many blog posts have you got associated, and how many subsites? If you remove the subsites module, does it affect your ability to publish?

Nginx 504s tend to show up when something is taking too long to process, which is usually a volume problem.

Can you replicate the issue with a fresh install of SilverStripe, pulling in only subsites and blog?

Thanks!

**Comment by ctx2002** [comment]
installed a fresh copy of SilverStripe and blog, it worked.
I have not tried install subsites yet.

I was debugging old site, it seems there was an infinite loop , or may be there were so many things that blog page tried to pull out.

I have found out that  Silverstripe has used a cache file,/tmp/silverstripe-cache-php5.6.15-1+deb.sury.org-trusty+1-home-vagrant-www-silverstripe-freshCopy/vagrant/.cache.framework.admin.templates.LeftAndMain.ss
 
in that LeftAndMain.ss , there is a line which causing problem, 
$val .= $scope->locally()->XML_val('Content', null, true); this function seems has a infinite loop.

But I am unable to find out what exactly caused problem.

**Comment by dhensby** [comment]
It will be some circular reference in your code rather than the template parser putting out some kind of loop...

**Comment by ctx2002** [comment]
in BlogPost class, if i disabled "$options = BlogAdminSidebar::create ..." code, then page been loaded.
why is this? it looks BlogAdminSidebar tried to load too many contents, any one know why?

**Comment by micmania1** [comment]
@ctx2002 can you check your error log and see if anything shows up there?

**Comment by ctx2002** [comment]
no errors in error log, just disable BlogAdminSidebar::create, then it worked.
I guess TagField::create(), function causing long delay. Because, occasionally, blog page was showing up,
if I was clicked Tag/Category drop down field, it took round 20 second to finish an AJax call.

**Comment by ctx2002** [comment]
how can I remove BlogAdminSidebar from blogpost, any one?

**Comment by ctx2002** [comment]
woo, finally I have found reason, on BlogPost:: -> public function getCandidateAuthors()
    {
        if ($this->config()->restrict_authors_to_group) {
            return Group::get()->filter('Code', $this->config()->restrict_authors_to_group)->first()->Members();
        } else {
            $list = Member::get();
            $this->extend('updateCandidateAuthors', $list);
            return $list;
        }
    }

**$list = Member::get();** ?? my system has over 100 thousand members.

I think Silverstipe need to remove this code. It hard for non-programmer to figure this out,
my client have no clue why this happened, because it was working when site first created.

In Documentation, I did not see any text mention **updateCandidateAuthors** or **restrict_authors_to_group**

**Comment by ctx2002** [comment]
In Blog documentation, the Doc should tell user **restrict_authors_to_group** is a **config variable** must be set, also need tell user where to the restrict_authors_to_group, at moment, I have to find it in DB.

**Comment by dhensby** [comment]
@ctx2002 great investigation work - would you mind submitting a docs patch?

**Comment by ctx2002** [comment]
ok, I will probably submitting a docs patch this weekend.

**Comment by robbieaverill** [comment]
Bump @ctx2002 - did you still feel like updating the docs for this?

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
