### ISSUE TITLE
Unpublished entries appear on live site

### ISSUE THREAD

**Issue by d4v3c** [silverstripe/silverstripe-blog#417]
I changed 

`$blogPosts = BlogPost::get()->filter('ParentID', $this->ID);`

to

`$blogPosts = Versioned::get_by_stage('BlogPost', 'Live')->filter('ParentID', $this->ID);`

in getBlogPosts() to work around this.

Should I send this as a PR, or I'm missing something?

**Comment by dhensby** [comment]
`$blogPosts = BlogPost::get()->filter('ParentID', $this->ID);`

Will automatically filter to the current stage. Perhaps you had the CMS open in another tab and were browsing in draft mode? If you opened the site in private browsing mode, you probably wouldn't have seen the draft content.

**Comment by d4v3c** [comment]
I used a different browser for testing, but I was logged in on that one too...

Thanks :)
