### ISSUE TITLE
Widgets not working

### ISSUE THREAD

**Issue by nimeso** [silverstripe/silverstripe-blog#419]
I've installed both the blog module and widgets and the latest version of SS

composer require silverstripe/blog
and
composer require silverstripe/widgets

I've done a dev/build?flush=1
and ?flush=1 in the cms

No 'widgets' tab is showing at all :(
All the files are there.

Am I going mad?

Cheers heaps

**Comment by nimeso** [comment]
![image](https://cloud.githubusercontent.com/assets/1796069/21246080/4e2bc516-c38b-11e6-8e76-491a2a99bc19.png)

**Comment by nimeso** [comment]
Please close this issue, sorry I didn't read stuff lol

**Comment by micmania1** [comment]
@nimeso just to clarify for anyone who finds this link via Google, what was the fix?

I assume its the following but please correct me if i'm wrong:

Add the WidgetPageExtension to your blog in your mysite/config.yml
```
Blog:
  extensions:
    - 'WidgetPageExtension'
```
