### ISSUE TITLE
"New Blog" not found when creating a new page

### ISSUE THREAD

**Issue by noder123** [silverstripe/silverstripe-blog#420]
As per the documentation:
https://github.com/silverstripe/silverstripe-blog/blob/master/docs/en/userguide/adding-blog-posts.md a "New Blog" radio button should come when creating a new page but it's missing in my SilverStripe installation. I installed the blog module via composer.
![screen shot 2016-12-19 at 12 15 40 pm](https://cloud.githubusercontent.com/assets/3831086/21303522/e9134d32-c5e4-11e6-945e-1dbf91ba66a0.png)

**Comment by dhensby** [comment]
Did you perform a dev/build?

What version of SilverStripe and Blog are you using?

**Comment by noder123** [comment]
I installed SilverStripe (3.5.0) using composer based instructions at: https://www.silverstripe.org/download/ I then opened the installer.php and completed the installation.
For the blog, I did $composer require silverstripe/blog
Let me know if I missed something.

**Comment by dhensby** [comment]
navigating to dev/build in the browser (https://docs.silverstripe.org/en/3/developer_guides/model/data_model_and_orm/#generating-the-database-schema)

**Comment by noder123** [comment]
I opened /dev/build, it created database tables. I'm still not able to see "New Blog" checkbox.

**Comment by kinglozzer** [comment]
@noder123 Try visiting `mysite.com/admin/pages/add?flush=1`

**Comment by noder123** [comment]
My URL changes to http://localhost/silverstripe/admin/pages/add?flush=1&flushtoken=48e68af8211e3249945f367691e10577 but I'm still not able to see the option.

Thanks for your support!

**Comment by noder123** [comment]
I installed the blog module in ~Sites//silverstripe directory but somehow folders named "blog" and "lumberjack" appeared in the parent directory i.e. ~/Sites. Any reason why?

**Comment by noder123** [comment]
I reinstalled everything and it's working now. Thanks for your time and support. Keep writing great code!
