### ISSUE TITLE
The code coverage test is too damn slow

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-blog#424]
Do we need to whitelist the code coverage so that it only looks at blog/code/*?

It takes far too long to run the code coverage test.

**Comment by kinglozzer** [comment]
<img width="300" src="https://cloud.githubusercontent.com/assets/1655548/22329202/1e3eae98-e3b8-11e6-8937-e5ef8580ab58.jpg" />

**Comment by dhensby** [comment]
46mins is too damn high

**Comment by robbieaverill** [comment]
It's already whitelisting against `src/` :)

**Comment by dhensby** [comment]
:/

**Comment by robbieaverill** [comment]
Let's implement what @chillu has been putting into the framework etc with phpdbg - the GraphQL coverage runs in a minute or two now

**Comment by robbieaverill** [comment]
Fixed with #459
