### ISSUE TITLE
Dev/Build throws user warnings on localisation

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/silverstripe-blog#427]
On latest master (dev-master 92004f8), running dev/build throw the following `[User Warnings]`:

- Localisation entity en.BlogCategoriesWidget.Direction is invalid
- Localisation entity en.BlogCategoriesWidget.Limit is invalid
- Localisation entity en.BlogCategoriesWidget.Sort is invalid
- Localisation entity en.BlogTagsWidget.Direction is invalid
- Localisation entity en.BlogTagsWidget.Limit is invalid
- Localisation entity en.BlogTagsWidget.Sort is invalid
- Localisation entity en.BlogCategoriesWidget.Direction is invalid
- Localisation entity en.BlogCategoriesWidget.Limit is invalid
- Localisation entity en.BlogCategoriesWidget.Sort is invalid
- Localisation entity en.BlogTagsWidget.Direction is invalid
- Localisation entity en.BlogTagsWidget.Limit is invalid
- Localisation entity en.BlogTagsWidget.Sort is invalid

**Comment by robbieaverill** [comment]
This is likely to be from the i18n changes in the framework recently. Updating legacy syntax is simple but tedious - I'll have a go at it in the next day or two if I have some time.

**Comment by andrewandante** [comment]
Is there a guide? Happy to do it myself. Simple but tedious I can do :p

**Comment by robbieaverill** [comment]
@andrewandante actually this isn't what I thought (although still related to the i18n upgrade) - looks like all those translations are nested three levels (see `blog/lang/en.yml` `en.BlogCategoriesWidget.Direction`). I'm assuming the new i18n backend doesn't support this level of nesting, so we'll need to flatten this out a little bit.

**Comment by dhensby** [comment]
Isn't that exactly how it should be nested?

**Comment by robbieaverill** [comment]
Haha, there's another key I didn't include in that example. Basically these translations are arrays where the majority of translations are strings at that nesting level.

**Comment by dhensby** [comment]
Ah. Ok

**Comment by tractorcow** [comment]
Sorry, ss 4.0 does support nested strings for localisation, but only for specific purposes (e.g. pluralisation, which is localised as an associative array).

We need to un-nest these, and maybe use a `_` in place of `.` for those keys.
