### ISSUE TITLE
Versioned assets break established publish behaviour

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/silverstripe-blog#429]
With the addition of versioned assets, publishing a blog post is not as simple as it once was. For example, as a content author, I would assume that when I publish my blog post with a feature image, the image itself is also published - however, it remains in draft.

The Campaigns feature seems designed to solve this, so we could look into hooking each BlogPost into a small campaign that includes attached images, presumably with some config to toggle this behaviour.

Alternatively, a BetterButton that warns onPublish that assets foo and bar will also be published could be an option.

This wouldn't be as annoying if you could push the asset from stage to live from within the BlogPost itself, but you have to navigate into the asset-admin, find the asset and publish it manually.

Other solutions welcomed with warm and loving arms.

**Comment by dhensby** [comment]
I think the problem with the publish betterbutton is that if someone adds a dataextension to add another bedroomed object then this button wouldn't publish the new object. Using a campaign should make it much easier to add new versioned relationships

**Comment by micmania1** [comment]
I'm a bit confused. Is this a betterbuttons, blog or core silverstripe bug?

If the blog (without betterbuttons) doesn't publish the image along with the blog then I'd say its definitely not desired behaviour.

**Comment by andrewandante** [comment]
Haven't tested on any other pagetype, but I think it's a matter of setting that the image `belongs_to` to the post, to that it is published alongside. Is that how it works?

**Comment by micmania1** [comment]
I doubt it but never tried SS4 properly. In SS3 you never needed to do this but that didn't have versioned assets so could be different.

All we're doing is adding an image to the page which is very standard SS so I doubt this is a blog issue. Even if that's new desired SS behaviour I'd say that needs to change as its extremely counter-intuitive.
