### ISSUE TITLE
Access level to Blog::$icon must be public

### ISSUE THREAD

**Issue by neilcreagh** [silverstripe/silverstripe-blog#432]
Installing the blog I got this error when trying to rebuild the database 
`Fatal error: Access level to Blog::$icon must be public (as in class Page) in ...blog/code/model/Blog.php on line 15`

The solution was to edit line 104 on Blog.php from Private to Public
`public static $icon = 'blog/images/site-tree-icon.png';`

Not sure if I should submit a Pull Request or not, as I imagine if this was a common problem it would have been raised already

**Comment by stevie-mayhew** [comment]
This will be caused by you having it set to `public` on your `Page.php`.

Instead of changing this level, change your one to `private` instead 😄

**Comment by neilcreagh** [comment]
I see - thanks
