### ISSUE TITLE
Developer Documentation Missing?

### ISSUE THREAD

**Issue by JustinTBrown** [silverstripe/silverstripe-blog#439]
Is there documentation posted somewhere other than the links provided in the [README](https://github.com/silverstripe/silverstripe-blog/blob/master/README.md)? Something that gives an overview of the various models, their features, available configurations and how they relate to one another? I know that you can learn these things by reviewing the source, but it would be awesome to have simpler introduction. 😃

**Comment by micmania1** [comment]
@JustinTBrown all we have at the moment is what's in the README. 

You can generate API docs locally using [apigen](https://github.com/ApiGen/ApiGen) which is used to generate the framework & cms API docs. This should show you what classes are available and their methods.

You also might find the docs over at lumberjack useful: https://github.com/silverstripe/silverstripe-lumberjack

If you have specific things you'd like to know please feel free to ask them here or on the [community slack channel](https://silverstripe-users.signup.team/) and we'll see if there's a good place for those types of questions to live in the docs.
