### ISSUE TITLE
with Translatable: FeaturedImage cannot be edited on the translation

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-blog#442]
I am using SS 3.6, Blog 2.4.5 and Translatable 2.2.3 (so, all latest stable). I am not using any extensions on BlogPosts or any Translatable tweaks, except to make sure that i18n is synced with the Translatable record. 

When I create a BlogPost, I can choose a Featured Image. Like any Image, I can edit, delete, etc it afterwards. 

But if I create a translation of this BlogPost, then it is not possible to change the Featured Image of that translation. It is stuck on the image that was present when the translation was first created. When the image on the original BlogPost is updated, the translation does not follow, so it is stuck on the old version. 

There is currently no way to fix the image on such a Translation, except by setting it in the database. 

Here's what it looks like. Note how the FeaturedImage does not have an "Original ..." version, and it does not have any buttons. I'm wondering whether this is because perhaps the FeaturedImage is added to the CMS after Translatable has done its thing, or something like that?

![image](https://cloud.githubusercontent.com/assets/3286264/26782867/cc3d1ffe-49f5-11e7-81fc-5214f50fe3a6.png)

**Comment by JorisDebonnet** [comment]
I'm guessing this is not worth fixing anymore since it's on the SS 3.x line...

**Comment by NightJar** [comment]
Quite right. However if you were to make a PR I certainly wouldn't be against merging it, but you'd have to update your installations to reference a development head I think would be the policy there.

If you're able to confirm that the issue is still relevant in the SS 4 compatible line, then we'd certainly welcome a PR for a fix there!

**Comment by JorisDebonnet** [comment]
Well, I never really looked into fixing this myself, and am using Fluent on SS4 nowadays... so I guess a fix for this won't come from me :) 

Fluent works differently, and allows updating the image (which is shared across the locales) via any of the locale edit screens. This fixes the original issue I had here, which was that translations did not follow updates to the image in the originel language.
