### ISSUE TITLE
Composer installation of blog fails for SS4.0.0-alpha7

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-blog#448]
After using `composer create-project silverstripe/installer testsite 4.0.0-alpha7` to install a fresh instance of SS, the command `composer require silverstripe/blog` gives the error:

Installation failed, reverting ./composer.json to its original content.

**Comment by dhensby** [comment]
What's the train given for failure?

**Comment by SpiritLevel** [comment]
Sorry...thought it would be a simple dependency issue. Here we go:

Using version ^2.4 for silverstripe/blog
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove silverstripe/cms 4.0.0-alpha7
    - Conclusion: don't install silverstripe/cms 4.0.0-alpha7
    - silverstripe/blog 2.4.0 requires silverstripe/cms ^3.1.0 -> satisfiable by silverstripe/cms[3.5.x-dev, 3.6.x-dev, 3.x-dev, 3.7.x-dev].
    - silverstripe/blog 2.4.1 requires silverstripe/cms ^3.1.0 -> satisfiable by silverstripe/cms[3.5.x-dev, 3.6.x-dev, 3.x-dev, 3.7.x-dev].
    - silverstripe/blog 2.4.2 requires silverstripe/cms ^3.1.0 -> satisfiable by silverstripe/cms[3.5.x-dev, 3.6.x-dev, 3.x-dev, 3.7.x-dev].
    - silverstripe/blog 2.4.3 requires silverstripe/cms ^3.1.0 -> satisfiable by silverstripe/cms[3.5.x-dev, 3.6.x-dev, 3.x-dev, 3.7.x-dev].
    - silverstripe/blog 2.4.4 requires silverstripe/cms ^3.1.0 -> satisfiable by silverstripe/cms[3.5.x-dev, 3.6.x-dev, 3.x-dev, 3.7.x-dev].
    - silverstripe/blog 2.4.5 requires silverstripe/cms ^3.1.0 -> satisfiable by silverstripe/cms[3.5.x-dev, 3.6.x-dev, 3.x-dev, 3.7.x-dev].
    - silverstripe/blog 2.4.x-dev requires silverstripe/cms ^3.1.0 -> satisfiable by silverstripe/cms[3.5.x-dev, 3.6.x-dev, 3.x-dev, 3.7.x-dev].
    - silverstripe/blog 2.x-dev requires silverstripe/cms ^3.1.0 -> satisfiable by silverstripe/cms[3.5.x-dev, 3.6.x-dev, 3.x-dev, 3.7.x-dev].
    - silverstripe/blog 2.5.x-dev requires silverstripe/cms ^3.1.0 -> satisfiable by silverstripe/cms[3.5.x-dev, 3.6.x-dev, 3.x-dev, 3.7.x-dev].
    - Can only install one of: silverstripe/cms[3.5.x-dev, 4.0.0-alpha7].
    - Can only install one of: silverstripe/cms[3.6.x-dev, 4.0.0-alpha7].
    - Can only install one of: silverstripe/cms[3.x-dev, 4.0.0-alpha7].
    - Can only install one of: silverstripe/cms[3.7.x-dev, 4.0.0-alpha7].
    - Installation request for silverstripe/cms 4.0.0-alpha7 -> satisfiable by silverstripe/cms[4.0.0-alpha7].
    - Installation request for silverstripe/blog ^2.4 -> satisfiable by silverstripe/blog[2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.x-dev, 2.x-dev, 2.5.x-dev].


Installation failed, reverting ./composer.json to its original content.

**Comment by dhensby** [comment]
You're trying to install blog 2.4 which is a 3.x compatible version and not 4.x

Make sure you require the correct version (3.0.x-dev)
