### ISSUE TITLE
Blog comment notifications spam authors if spammed

### ISSUE THREAD

**Issue by camfindlay** [silverstripe/silverstripe-blog#449]
Current behaviour is that at https://github.com/silverstripe/silverstripe-blog/blob/2.4/code/extensions/BlogPostNotifications.php#L18 The authors are always notified of comments.

Issue being is if the comment is spam, and there is a flood of spam, then all authors will get a flood of notifications in their inbox (just shifting the problem).

I'm proposing a simple fix, a configurable option not to send notifications if the comment is identified as spam (say by Akismet). Would keep the config boolean to match current functionality so would be an opt-in feature to keep in line with current minor version.

PR shortly.

Anything else to include here?
What testing would be adequite?
Docs?

**Comment by camfindlay** [comment]
@robbieaverill which branch should a PR be raised against for a 2.5.x minor?

**Comment by camfindlay** [comment]
See #450

**Comment by robbieaverill** [comment]
Done in #450 - thanks @camfindlay
