### ISSUE TITLE
SS4 Bug : Internal Server Error when creating a new blog page

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-blog#452]
To reproduce:
(1) install ss4 with `composer create-project silverstripe/installer 400beta1 4.0.0-beta1`
(2) install blog with `composer require silverstripe/blog dev-master` (could not install with 2.4.5 or any other version).
(3) run `dev/build?flush`
(4) go into CMS and try to create a new blog page. Nothing happens except an "Internal Server Error" pop-up gets displayed.

**Comment by SpiritLevel** [comment]
A bit more information. When one then goes to `admin/pages` one gets the following:

![screenshot from 2017-07-05 15-03-27](https://user-images.githubusercontent.com/8912185/27847681-4eb1eaa0-6193-11e7-965f-2ed990cf47bc.png)

However, one is able to get to other sections of the CMS such as `admin/security` and `admin/assets`.

**Comment by dhensby** [comment]
@andrewandante have you had this issue?

**Comment by dhensby** [comment]
This should have been fixed in lumberjack, please run a composer update

**Comment by SpiritLevel** [comment]
@dhensby I can't install the blog anymore...after a fresh install of SS4 I tried the two commands:

(1) `composer require silverstripe/blog`
(2) `composer require silverstripe/blog dev-master`

The output of these two commands is:

![screenshot from 2017-07-06 08-56-32](https://user-images.githubusercontent.com/8912185/27884630-0d10e5a6-6229-11e7-90b1-e9d941b6db10.png)

**Comment by robbieaverill** [comment]
Typo in package name

**Comment by SpiritLevel** [comment]
Sorry about previous post; misspelled silverstripe :(

Blog seems to be working fine now. Thanks.
