### ISSUE TITLE
SS 3.6.1 : Archive widget borks when added to blog.

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-blog#453]
In a fresh ss3.6.1 instance, I added blog, comments, and widgets. Then, I created a blog page. I then added the Archives widget and got the following error (the other widgets appear to be working fine).

![screenshot from 2017-07-07 14-12-27](https://user-images.githubusercontent.com/8912185/27940461-dede9be6-631e-11e7-8da2-e5474d5f51e6.png)

**Comment by robbieaverill** [comment]
Are you running MySQL 5.7?

**Comment by SpiritLevel** [comment]
Yip :)

![screenshot from 2017-07-07 16-51-55](https://user-images.githubusercontent.com/8912185/27943583-9db9b450-6334-11e7-9ebf-0ac112d1565a.png)

**Comment by robbieaverill** [comment]
Yes, ok. I've seen this before. Will need to investigate. Thanks for reporting!

**Comment by SpiritLevel** [comment]
Thanks @robbieaverill :)

By the way, I'm running Ubuntu16.04 with PHP7.0.

**Comment by kinglozzer** [comment]
https://github.com/silverstripe/silverstripe-blog/pull/446 addresses this

**Comment by SpiritLevel** [comment]
Thanks @kinglozzer :) Will close this.

**Comment by SpiritLevel** [comment]
https://github.com/silverstripe/silverstripe-blog/pull/446 didn't fix this issue so reopening.

Using (i) a fresh install of 3.6.1 (ii) composer require silverstripe/blog (iii) composer require silverstripe/widgets and (iv) adding WidgetPageExtension to Blog and BlogPost I get the same error message as above.

**Comment by robbieaverill** [comment]
@SpiritLevel can you provide the version of blog that you've installed with composer? `composer show silverstripe/blog`

**Comment by SpiritLevel** [comment]
Here we go :)
blog 2.4.5
tagfield 1.3.2
lumberjack 1.3.0
widgets 1.2.5
ss 3.6.1
php 7.0.22
mysql  5.7.19

**Comment by robbieaverill** [comment]
@SpiritLevel 2.4.5 doesn't contain the fix from #446, it looks like we haven't released it yet (it'll be in 2.4.6 when it comes out, which is shortly).

**Comment by SpiritLevel** [comment]
Thanks @robbieaverill Will watch for it. I'll close this again....

**Comment by dhensby** [comment]
@SpiritLevel if you require version 2.4.6 then composer should pull in the dev build until the stable is tagged

**Comment by SpiritLevel** [comment]
Thanks @dhensby :) I'll give it a go.

**Comment by SpiritLevel** [comment]
@dhensby....I tried composer require silverstripe/blog dev-master but that requires SS4 and I am running SS3.6.1. Can you explain how I pull in the dev build that I need ? :)

**Comment by SpiritLevel** [comment]
OK. The Archives widget now works when using 2.4.x-dev for blog. Thanks! I am still curious as to which of the dev branches would be best for me to pull in :)

However, I can confirm that the [Yearly archive bug](https://github.com/silverstripe/silverstripe-blog/issues/464) remains; the monthly archives work fine.

**Comment by dhensby** [comment]
I'd just require `^2.4.6` but the different versions (2.x-dev vs 2.4.x-dev) just represent if you're hooked into just bug fixes or new features too. 2.4.x-dev is the patch release line and 2.x-dev is the minor release line
