### ISSUE TITLE
3.0.0 beta

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-blog#454]
If I read #405 and #421, it sounds like SilverStripe 4 compatibility has been achieved. I also don't see any remaining issues under the 3.x label (although maybe #453 needs to be solved). 

Anyway, my question is: any chance for an alpha or beta release for blog module 3.0.0? :) 

(and if not, does anyone have an overview of the work that is still required, which could be added as issues under the 3.x milestone?)

**Comment by robbieaverill** [comment]
We could definitely do at least an alpha

**Comment by dhensby** [comment]
done https://github.com/silverstripe/silverstripe-blog/releases/tag/3.0.0-alpha1
