### ISSUE TITLE
silverstripe-blog-camfindlay-patch-1  (potential bug )

### ISSUE THREAD

**Issue by AnonymousWebHunter** [silverstripe/silverstripe-blog#457]
Silverstripe website version 3.6.1 with blog module version **silverstripe-blog-camfindlay-patch-1.**
I have the following pages: **News** and **Events** ( both extend Blog ) and **NewsDetail** and **EventDetail** ( both extend B**logPost** ). The problem is, for example when I want to add a new NewsDetail, the category select provides categories from both NewsDetail and EventDetail. 

I have already done a similar thing with another website ( with another version of the blog module ) and this problem didn't occur. I'm looking through the code but this makes no sense, it should give me only categories for that blog ( $parent->Categories() ).

Also after a look into the database, each category has the relation with it's blog page by the field BlogID, how is this possible ?

**Comment by robbieaverill** [comment]
Hey @AnonymousWebHunter - that branch seems like it should have been temporary. It doesn't exist any more. Could you try upgrading to the latest version?

**Comment by AnonymousWebHunter** [comment]
Hey @robbieaverill,

Thanks for your reply, I will upgrade to the latest possible version that is compatible with my version and see if this issue still occurs.

**Comment by AnonymousWebHunter** [comment]
@robbieaverill , I deleted blog module, News page and Events. And rebuild everything with blog version 2.4 and it looks like I still get categories from both pages.

**Comment by dhensby** [comment]
I can't replicate this.

![events](https://user-images.githubusercontent.com/563596/28367870-5b7986b0-6c8a-11e7-8840-9872db7310bb.png)
![news](https://user-images.githubusercontent.com/563596/28367914-7f0808c2-6c8a-11e7-9993-02336ce4a52a.png)

I've created page types as you described with their inheritance.

Either you're doing something custom which is making it behave strangely or you need to provide more explicit steps to replicate this issue.
