### ISSUE TITLE
Categorisation Tab

### ISSUE THREAD

**Issue by MichaelJJames** [silverstripe/silverstripe-blog#462]
Hi, 

Only Full Admins can see the Categorisation tab on the main blog page of the CMS.

Thanks

**Comment by robbieaverill** [comment]
@MichaelJJames can you provide the blog and SilverStripe core versions you're using? (`composer show`)

I suppose the expected behaviour should be that users who can view Blog and BlogPost pages should be able to see the Categorisation tab as well.

**Comment by MichaelJJames** [comment]
Hi Robbie,

Sorry about the late reply.

composer.json contents below
```
{
	"name": "silverstripe/installer",
	"description": "The SilverStripe Framework Installer",
	"require": {
		"php": ">=5.3.3",
		"silverstripe/cms": "3.5.1",
		"silverstripe/framework": "3.5.1",
		"silverstripe/reports": "3.5.1",
		"silverstripe/siteconfig": "3.5.1",
		"silverstripe/translatable": "^2.2",
		"martimiz/silverstripe-languageprefix": "dev-master",
		"undefinedoffset/sortablegridfield": "^0.6.5",
		"jonom/silverstripe-betternavigator": "^3.0",
		"silverstripe/userforms": "^4.2",
		"silverstripe/lumberjack": "^1.2",
		"silverstripe/blog": "^2.4",
		"unclecheese/betterbuttons": "^1.3",
		"kinglozzer/metatitle": "^1.0",
		"silverstripe/dynamodb": "^2.0"
	},
	"require-dev": {
		"phpunit/PHPUnit": "~3.7@stable"
	},
	"extra": {
		"branch-alias": {
			"3.x-dev": "3.5.x-dev"
		}
	},
	"config": {
		"process-timeout": 600
	},
	"prefer-stable": true,
	"minimum-stability": "dev"
}

```

**Comment by robbieaverill** [comment]
Hi @MichaelJJames, I can't reproduce this on SS 3.5 or 3.6 using blog 2.4.5.

I've tested it with a user that only has access to Pages, and that user can still access the categorisation tab:

![image](https://user-images.githubusercontent.com/5170590/30188826-cccbb85c-9484-11e7-9a39-825f26f51be9.png)

![image](https://user-images.githubusercontent.com/5170590/30188835-dd2cb17e-9484-11e7-97c2-35961dacab51.png)

If you're still experiencing this issue, could you please provide the exact blog version you're using (`composer show silverstripe/blog`) as well as some screenshots of the security settings for the user that you're having problems with?

Thanks :)

Robbie

**Comment by MichaelJJames** [comment]
Hi, 

This is the the version of the blog 2.4.5 and screen shot of my permissions 

![helga-permissions](https://user-images.githubusercontent.com/6860174/30421151-c5a31814-9933-11e7-908f-aa86cb3514a0.png)

Thanks 
Michael
