### ISSUE TITLE
Blog Profile does not support UTF-8

### ISSUE THREAD

**Issue by Misagh90** [silverstripe/silverstripe-blog#465]
Hi,
I create a yml file in my config & i add
```
URLSegmentFilter:
  default_allow_multibyte: true
```
to create Persian(Farsi) URL link but it's not working on blog Profile pages. (it's work on another kind of Pages) (I try in another languages except English, but still not working)
I thinks that not supporting UTF-8.
how can i fix this?!

**Comment by robbieaverill** [comment]
Hi, could you please supply the version of SilverStripe CMS and Blog that you're using?

**Comment by Misagh90** [comment]
@robbieaverill 
Silverstripe 3.6.1 & Blog 2.4
I understand that BlogMemberExtension.php need something like: `$filter->setAllowMultibyte(true);`

**Comment by robbieaverill** [comment]
Fix at #466
