### ISSUE TITLE
SS4beta3 + Blog: funky layout error

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-blog#475]
![screenshot from 2017-09-20 11-57-11](https://user-images.githubusercontent.com/8912185/30620697-fd2f52a4-9dfa-11e7-8098-6bb0f0b87d9a.png)

It goes away if you go to another section of the CMS and return to the blog post.

**Comment by micmania1** [comment]
I'm guessing this is related to the blog sidebar.

**Comment by fspringveldt** [comment]
I'm unable to reproduce this on my side. @SpiritLevel do you mind sharing the results of your project's `composer show` ?

**Comment by SpiritLevel** [comment]
@fspringveldt Sorry for delay...I'll try to reproduce this tonight :)

**Comment by SpiritLevel** [comment]
I just noticed in the screenshot I posted above that the icon in the CMS toolbar for comments is a black house. Need a blue comment bubble ;)

I tried installing 4.0.0-alpha3 again but it seems that `RedirectorPageController.php` is now having a hard time finding `PageController`...namespacing error I'm supposing. Here are the errors I am getting:
![screenshot from 2017-09-25 20-13-33](https://user-images.githubusercontent.com/8912185/30796432-79e895f8-a22e-11e7-8040-cd24114f83e9.png)

**Comment by robbieaverill** [comment]
@SpiritLevel can you post the contents of your PageController? It needs to not be in a namespace.

**Comment by SpiritLevel** [comment]
I just installed 4.0.0-alpha3 without making any changes and there is no PageController.php. There is only a Page.php with the following contents:
```php
<?php

use SilverStripe\CMS\Controllers\ContentController;
use SilverStripe\CMS\Model\SiteTree;

class Page extends SiteTree {

	private static $db = array(
	);

	private static $has_one = array(
	);

}
class Page_Controller extends ContentController {

	/**
	 * An array of actions that can be accessed via a request. Each array element should be an action name, and the
	 * permissions or conditions required to allow the user to access it.
	 *
	 * <code>
	 * array (
	 *     'action', // anyone can access this action
	 *     'action' => true, // same as above
	 *     'action' => 'ADMIN', // you must have ADMIN permissions to access this action
	 *     'action' => '->checkAction' // you can only access this action if $this->checkAction() returns true
	 * );
	 * </code>
	 *
	 * @var array
	 */
	private static $allowed_actions = array (
	);

	public function init() {
		parent::init();
		// You can include any CSS or JS required by your project here.
		// See: https://docs.silverstripe.org/en/developer_guides/templates/requirements/
	}

}

```

**Comment by robbieaverill** [comment]
How did you install it? Beta 3 should be using the CMS recipe which should install these files: https://github.com/silverstripe/recipe-cms/tree/1/mysite/code

**Comment by SpiritLevel** [comment]
composer create-project silvetrstripe/installer BlogTest 4.0.0-alpha3

**Comment by robbieaverill** [comment]
Oh, right. Can you try with the latest version please? It's beta 3

**Comment by SpiritLevel** [comment]
Oops...sorry...

**Comment by SpiritLevel** [comment]
Well, I can't seem to reproduce it with ss4-beta3 (yes, beta3!) blog dev-master, widgets dev-master and comments dev-master.

I feel a bit like the boy who cried wolf. 

Sorry to waste everybody's time :( I'll close this....
