### ISSUE TITLE
SS3.6.1 + Blog : too many redirects in CMS preview

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-blog#477]
![screenshot from 2017-09-20 18-48-06](https://user-images.githubusercontent.com/8912185/30630383-8153fe20-9e34-11e7-8944-ad0eefa7014b.png)

**Comment by SpiritLevel** [comment]
I should add that all I did was install SS3.6.1, install the blog, create a blog, and create a blogpost. I have not added any redirects, changed any templates or php files...this behaviour is right out of the box.

**Comment by robbieaverill** [comment]
I have a slight suspicion that this may be related to the installation path you're using and some questionable redirect code, possibly in the widgets module. Do you have the ability to try this out on a TLD?

**Comment by SpiritLevel** [comment]
Yup. Will do now.

**Comment by SpiritLevel** [comment]
@robbieaverill Just got this locally when creating a new page of type Blog...the CMS is empty apart from the tools section...having a hard time reproducing original issue...:\ All very sporadic.
![screenshot from 2017-09-22 15-09-30](https://user-images.githubusercontent.com/8912185/30727880-227623ea-9fa8-11e7-9b39-244066afb441.png)

**Comment by SpiritLevel** [comment]
@robbieaverill OK, I have tried several times to reproduce the original issue locally but can't. But, the proof is posted that I did hit too many redirects! I haven't tried on a TLD. 

I am working with the blog+widgets+comments combo a lot at the moment so I anticipate coming across this again. If I do, I'll immediately push the site up to a TLD and see if the problem arises there too.

**Comment by robbieaverill** [comment]
Ok, cool. Reopen if you find it again, thanks!

**Comment by SpiritLevel** [comment]
@robbieaverill I am able to consistently get a blank Main area in the CMS when creating a page of type Blog, just as in the above pic. Refreshing the page populates the Main area, and the new blog page has been created. I restarted my apache server and cleared the browser cache for good measure and the blank area still occurs.

**Comment by robbieaverill** [comment]
Can you please check your PHP and Apache (?) error logs? Black screens usually come with some sort of error log

**Comment by SpiritLevel** [comment]
OK. I checked error_log for php and /var/log/apache2/error.log for apache. I cleared out the contents of both and repeated the addition of a blog page. Both error files remained empty after adding a blog page and the main area goes blank. The apache access log shows that I am accessing the CMS.

php.ini settings:
error_reporting = E_ALL
display_errors = On
log_errors = On
error_log = /home/dra/.php-error-log (writable by web server)

Here are the contents of /var/log/apache2/access.log (stops at WidgetAreaEditor.js ?):

::1 - - [22/Sep/2017:16:34:05 +1200] "GET /SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/ HTTP/1.1" 200 1865 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
::1 - - [22/Sep/2017:16:34:20 +1200] "GET /SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/admin/ HTTP/1.1" 302 398 "http://localhost/SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
::1 - - [22/Sep/2017:16:34:20 +1200] "GET /SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/admin/pages HTTP/1.1" 200 5280 "http://localhost/SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
::1 - - [22/Sep/2017:16:34:21 +1200] "GET /SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/admin/pages/listview HTTP/1.1" 200 9460 "http://localhost/SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/admin/pages" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
::1 - - [22/Sep/2017:16:34:21 +1200] "GET /SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/admin/pages/treeview HTTP/1.1" 200 9700 "http://localhost/SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/admin/pages" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
::1 - - [22/Sep/2017:16:34:27 +1200] "GET /SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/admin/pages/add/ HTTP/1.1" 200 15228 "http://localhost/SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/admin/pages/add/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
::1 - - [22/Sep/2017:16:34:27 +1200] "GET /SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/framework/javascript/SelectionGroup.js?m=1498564096&_=1506054867795 HTTP/1.1" 200 578 "http://localhost/SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/admin/pages/add/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
::1 - - [22/Sep/2017:16:34:31 +1200] "POST /SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/admin/pages/add/AddForm HTTP/1.1" 200 8208 "http://localhost/SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/admin/pages/add/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
::1 - - [22/Sep/2017:16:34:32 +1200] "GET /SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/admin/pages/edit/show/15 HTTP/1.1" 200 42894 "http://localhost/SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/admin/pages/edit/show/15" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
::1 - - [22/Sep/2017:16:34:34 +1200] "GET /SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/blog/js/cms.js?m=1503894955&_=1506054874041 HTTP/1.1" 200 1633 "http://localhost/SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/admin/pages/edit/show/15" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
::1 - - [22/Sep/2017:16:34:34 +1200] "GET /SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/lumberjack/javascript/GridField.js?m=1494903962&_=1506054874044 HTTP/1.1" 200 571 "http://localhost/SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/admin/pages/edit/show/15" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
::1 - - [22/Sep/2017:16:34:34 +1200] "GET /SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/framework/javascript/ToggleCompositeField.js?m=1498564096&_=1506054874046 HTTP/1.1" 200 650 "http://localhost/SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/admin/pages/edit/show/15" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
::1 - - [22/Sep/2017:16:34:34 +1200] "GET /SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/blog/js/gridfieldaddbydbfield.js?m=1503894955&_=1506054874049 HTTP/1.1" 200 612 "http://localhost/SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/admin/pages/edit/show/15" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
::1 - - [22/Sep/2017:16:34:34 +1200] "GET /SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/widgets/javascript/WidgetAreaEditor.js?m=1503634818&_=1506054874051 HTTP/1.1" 200 2099 "http://localhost/SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/admin/pages/edit/show/15" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"

**Comment by SpiritLevel** [comment]
[This](https://github.com/silverstripe/silverstripe-cms/issues/1972) might be related.
