### ISSUE TITLE
Email alert/notifications for blog post review

### ISSUE THREAD

**Issue by buffy999** [silverstripe/silverstripe-blog#483]
Hi,

You can contact me by email if this not an issue.

I'm not sure if this blog does have the email alert/notifications, what i am wanting is, if the user as "contributors" want to create a new blog which they can create or edit BlogPosts, but are unable to publish without authorisation of an editor, when the user has submit for the editors to review their blog page before approval to publish, but the editors does not receive any email alert or notifications for them to review their blog pages and approve for publish. 

Is there a code for that or is there some where i can find?

Would be really helpful to use the email alert/notifications.

Thanks.

Kirsten Morgan

**Comment by robbieaverill** [comment]
Hi Kirsten, this module doesn't have that functionality built in. You'd probably have some luck using [the Advanced Workflow module](https://github.com/symbiote/silverstripe-advancedworkflow) which does let you set up email notifications for workflow transitions like that.

**Comment by buffy999** [comment]
Thanks.
i've already had look at the Advanced Workflow module, i only need to have email notifications functionality to add into blog. I'll keep trying find elsewhere.
