### ISSUE TITLE
Multibyte URLs have stopped working

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-blog#488]
Similar to #484, but in SS4. The tests for them are also failing.

https://travis-ci.org/silverstripe/silverstripe-blog/jobs/296592633

Appears to have started failing in the last 24 hours or so. Previously passing master builds are now failing when re-run: https://travis-ci.org/silverstripe/silverstripe-blog/jobs/287015877

However, this build from yesterday passed: https://travis-ci.org/silverstripe/silverstripe-blog/jobs/296438910

**Comment by NightJar** [comment]
Cannot reproduce, [builds now pass](https://travis-ci.org/silverstripe/silverstripe-blog/builds/334537119).

Tests [are very simple](https://github.com/silverstripe/silverstripe-blog/blob/ef2f1165d74e169073b8819874433796e0edfecb/tests/BlogFunctionalTest.php) and I cannot see any obvious reason for them to fail.
Nor can I [see any changes](https://github.com/silverstripe/silverstripe-blog/compare/271fbfeae75a1dc88ad940a9e8ac9af5d09f5c93...ef2f1165d74e169073b8819874433796e0edfecb) that might rectify any issues to do with routing.

**Comment by NightJar** [comment]
Appears something changed somewhere that I didn't see, because it passes now and the old builds in OP still fail:
https://travis-ci.org/silverstripe/silverstripe-blog/jobs/287015877
https://travis-ci.org/silverstripe/silverstripe-blog/jobs/296592633

**Comment by robbieaverill** [comment]
Resurfaced again since https://github.com/silverstripe/silverstripe-cms/pull/2365#issuecomment-460487655 was merged

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-blog/pull/571
 and https://github.com/silverstripe/silverstripe-cms/pull/2384

**Comment by robbieaverill** [comment]
Re-fixed again

**Comment by NightJar** [comment]
@Cheddam has some follow up suggestions. i.e. fixed in the case that the tests cover, but probably not in the other two use cases that have the same old functionality.
That is, `profile` has been addressed, but `tags` and `catagories` have not.
