### ISSUE TITLE
special characters in post title cause issues with url creation

### ISSUE THREAD

**Issue by hp7** [silverstripe/silverstripe-blog#491]
Having quotes and apostrophes in post title cause charters to be dropped in page url formation.
_Example_
**Post title:** 
"It's like riding a bike"
**Creates post URL:**
/It

SS ver 3.6.2
blog mod ver 2.*@dev
--------
Possible solution remove non compliant characters when forming URL

**Comment by robbieaverill** [comment]
Thanks for reporting @hp7.

For reference, the existing rules for creating a URL segment are in `URLSegmentExtension::generateURLSegment`, which should pass through the core URLSegmentFilter with multibyte support enabled. The behaviour you're reporting should be covered in core.

Related issues: #484 #488

**Comment by robbieaverill** [comment]
@hp7 I can't reproduce this using silverstripe/framework 3.6.2, silverstripe/cms 3.6.2 and silverstripe/blog 2.4.x-dev.

Can you please provide a dump of your `composer show` output?
