### ISSUE TITLE
Question: How do I add comments to blog posts? 

### ISSUE THREAD

**Issue by nimeso** [silverstripe/silverstripe-blog#492]
Hi guys,
How do I add comments to blog posts? Is this supported?
Cheers

**Comment by robbieaverill** [comment]
Hey @nimeso, yeah - you can apply the comments extension to the Blog and/or BlogPost class to enable the feature. See here for more information: https://github.com/silverstripe/silverstripe-comments/blob/master/docs/en/Configuration.md
