### ISSUE TITLE
Widget implementation needs to be adjusted for new Widgets ownership API

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-blog#497]
From #496 

I've just had a quick look at the test failure, here's a couple of notes:

* The fixture that is failing to be loaded is being successfully loaded in [a different test](https://github.com/silverstripe/silverstripe-blog/blob/master/tests/Widgets/BlogArchiveWidgetTest.php#L40) from the draft stage
* The failure is when trying to load the fixtured widget from the live stage
* The failing test published the owner BlogPost recursively (which should publish the widgets too) before switching the stage

I think in https://github.com/silverstripe/silverstripe-widgets/pull/163 we implemented the ownership  API into the widgets module, which is probably causing this error. It looks as if the way widgets are associated to blog pages in this module needs to be updated, since it's more like a has_one from Widget to Blog/BlogPost rather than using the intermediary WidgetArea, which is where the ownership API is centered.

**Comment by robbieaverill** [comment]
Closed by #500

**Comment by dhensby** [comment]
@robbieaverill #500 fixes test failures, but I'm not sure it's solved any underlying ownership issues? But maybe they were already implemented and it's just the test wasn't quite right?

**Comment by robbieaverill** [comment]
I've still got this issue pinned to come back to at some point and revalidate

**Comment by robbieaverill** [comment]
No, it looks fine =)
