### ISSUE TITLE
Widget templates can not be found

### ISSUE THREAD

**Issue by nspyke** [silverstripe/silverstripe-blog#498]
`[User Warning] None of the following templates could be found: Array ( [silverstripe\blog\widgets\blogcategorieswidget] => SilverStripe\Blog\Widgets\BlogCategoriesWidget [silverstripe\widgets\model\widget] => SilverStripe\Widgets\Model\Widget [silverstripe\orm\dataobject] => SilverStripe\ORM\DataObject [silverstripe\view\viewabledata] => SilverStripe\View\ViewableData ) in themes "Array ( [0] => nelson-mtb-club [1] => $default ) "`

Moving the widget folder into templates/SilverStripe/Blog folder fixed the issue for me

**Comment by robbieaverill** [comment]
Thanks for reporting @nspyke - would you be keen to submit a pull request to move the templates?

**Comment by nspyke** [comment]
Yea I can do that

**Comment by robbieaverill** [comment]
Note to self - re-check to see if still a bug - related: https://github.com/silverstripe/silverstripe-blog/issues/497

**Comment by robbieaverill** [comment]
Cannot reproduce any more. Feel free to reopen if you're still having problems with this.
