### ISSUE TITLE
[Emergency] Uncaught Error: Class 'BlogPost' not found

### ISSUE THREAD

**Issue by digi-brains** [silverstripe/silverstripe-blog#513]
When getting a single blog post from my home page controller (to display on my home page) I get the error Class 'BlogPost' not found.

**HomePageController**
```
class HomePageController extends PageController {
    public function getBlogPost() {
        $blogPost = BlogPost::get()
            ->sort('PublishDate', 'Desc')
            ->limit(1);
        return $blogPost;
    }
}
```

**HomePage.ss**
```
        <% loop $BlogPost %>
        ...
        <% end_loop %>
```

**Comment by dhensby** [comment]
You need to import the `BlogPost` class by adding `use SilverStripe\Blog\Model\BlogPost` to the top of your PHP file.
