### ISSUE TITLE
Undescriptive error message on edit form when upload file exceeds allowed file size 

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-blog#514]
I used the cwp-installer 2.0.0.rc-1 to install the blog module.

I try to add a file via the Featured Image upload field to a blog post. 

The file size of the image I attempt to upload is _too large_, however. Instead of a descriptive error the following is rendered:

![image](https://user-images.githubusercontent.com/14869519/37190175-4c4341fa-23bd-11e8-8392-888c4ba8a7f8.png)

**Comment by robbieaverill** [comment]
At the least it shouldn’t be showing a stack trace of the error (higher impact)

**Comment by robbieaverill** [comment]
Although to be fair it probably only does that in developer mode

**Comment by robbieaverill** [comment]
This isn't a problem using CWP 2.1.0-beta1 any more, in that you do get a descriptive error message now:

![image](https://user-images.githubusercontent.com/5170590/42364376-037d8526-814f-11e8-8297-d84e0859c81a.png)

Closing
