### ISSUE TITLE
Bring URLSegment back to the Main tab

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-blog#526]
The Post Options are now in a tab, rather than a sidebar, which causes the URLSegment to be invisible when you make an edit to your BlogPost's Title. As a result, you may be less likely to think about clicking on that "Update URL" button. To be honest, my clients almost never do that anyway, resulting in out-of-date URLs.

Out-of-date URLs caused by updated Titles could be partly prevented by bringing the URLSegment back to its default position, since then with a little attention you can at least _see_ that the URL got dissynchronized from the Title.

**Comment by robbieaverill** [comment]
I'm going to classify this as a bug. Do you feel like making a PR for it?

**Comment by JorisDebonnet** [comment]
Working on it now!

**Comment by robbieaverill** [comment]
Fixed with #527, thanks =)
