### ISSUE TITLE
Categories and tags keeps disappearing in the Post Options

### ISSUE THREAD

**Issue by buffy999** [silverstripe/silverstripe-blog#531]
Not sure if others have come across the same issue i'm having at the moment.
I'm using the latest versions of the Blog, Tagfield and Lumberjack, with SS4.1.0.

I've created couple of wordings in both Categories and Tags in the Categorisation section, it works ok as expected, but once i created a new blog post, and went to the Post Options tab, i tried to enter the wordings in both Categories and Tags fields, it keeps disappearing, and it does not show the list of wordings i've created from Categoristation, it just show empty.

Any thoughts to why is behaving? or something i've missed?

**Comment by robbieaverill** [comment]
@buffy999 are you using the latest stable tags for blog, tagfield and lumberjack? Just confirming in order to reproduce

**Comment by buffy999** [comment]
Here's the list of the modules i'm using:

Blog 3.1.0
Lumberjack 2.0.0-rc1
Tagfield 2.0.0
SilverStripe 4.1.0

**Comment by robbieaverill** [comment]
Very helpful, thanks!

**Comment by NightJar** [comment]
Hi @buffy999 - could you please also inform:

* Do those resources exist physically in the file system?
* Have you recently upgraded from 4.0 to 4.1 (i.e. are you now using a `public` folder, where your project wasn't originally)?

**Comment by robbieaverill** [comment]
Suspect we're missing a `composer vendor-expose` command here, or the SilverStripe site was deployed without using composer and is missing these requirements

**Comment by NightJar** [comment]
Suspect the same ;)

**Comment by buffy999** [comment]
Hi @NightJar,

Do you mean the "resources" folder that has the themes and vendor in it, yes i have that under "public" folder, should the "resources" folder be removed?

Yes i've recently upgraded from 4.0 to 4.1, and yes i'm using the public folder.

**Comment by NightJar** [comment]
@buffy999 I mean the `$installation_root/public/resources` (and for that matter `$installation_root/resources`) should _not_ be committed to your git repository. This is a dynamically generated folder via `composer install`.

I suspect that if you remove this folder (in its entirety) then run `composer vendor-expose` (which is a SilverStripe extension to composer) your issue will disappear.

**Comment by NightJar** [comment]
The way to do it would be to painstakingly visit every module, and copy and paste it's static resources into the correctly structured folder under the `resources` root. Not ideal, I don't recommend it ;)

Step by step with composer should be reasonably straight forward. It depends on your environment, but once you've got composer installed (`apt-get install composer`, or suchlike) then the commands are basically as follows:

* `composer create-project silverstripe/installer $project_name $desired_version`
* `cd $project_name`
* use either `composer require` or directly edit (preferable) the compser.json file to include all your required dependencies (read: SilverStripe modules, in the simplest case)
* add your project code (probably `mysite`)

You can find great documentation at https://docs.silverstripe.org/en/4/getting_started/composer/ and even some lessons from our friend UncleCheese at https://www.silverstripe.org/learn/lessons/v4/up-and-running-setting-up-a-local-silverstripe-dev-environment-1

There are great examples about version constraints (please use good ones) at https://getcomposer.org/doc/articles/versions.md

Please let me know if you get lost, I'm happy to help. Although you'll probably get more immediate and thorough feedback via the community's slack channel, if you're able https://www.silverstripe.org/community/slack-signup/

**Comment by buffy999** [comment]
YEESSSS!!! Finally got it to work with categories and tagging now. Also worked with other issues i had with userforms and profile. Thank you so much for helping me. 

What i did was i redo the whole thing again by reinstalling the SilverStripe through Composer this time, and lots of tweaking to copy all the backup files over etc etc, and did remove the resources folder and run the composer vendor-expose, and it did the trick! i have learnt a lot now. :D

Thanks again for all your help.
