### ISSUE TITLE
Add an Extension Point for PaginatedList in BlogController

### ISSUE THREAD

**Issue by gordonbanderson** [silverstripe/silverstripe-blog#532]
hi,

It would be good to have an extension point in the PaginatedList method, my use case being one of returning items with a field `Pinned => 1` (true) first.

Cheers

Gordon

**Comment by dhensby** [comment]
that would require adjusting the sort. Is there no way to do this currently?

**Comment by robbieaverill** [comment]
Closing due to lack of feedback. Feel free to reopen and/or submit a pull request to add the feature you're looking for 😄
