### ISSUE TITLE
Blog Profile Image upload field not working

### ISSUE THREAD

**Issue by buffy999** [silverstripe/silverstripe-blog#533]
Having trouble uploading the blog profile image in the editing profile form, it disappeared after i submit the form.

Before importing the file:
<img width="467" alt="blog-profile-field" src="https://user-images.githubusercontent.com/7983615/40515641-b7e1fd2c-6001-11e8-9fc4-52350e091f0b.png">

After importing the file and saved/submitted the form:
<img width="450" alt="blog-profile-imported" src="https://user-images.githubusercontent.com/7983615/40515693-dc2fd316-6001-11e8-97ca-6722ce36f859.png">

It should be showing the image in that field after importing the file. Also the image itself is not being published automatically, it just sitting in the asset folder.

**Comment by robbieaverill** [comment]
Thanks for reporting @buffy999, can you please provide the versions of blog and SilverStripe CMS that you're using?

**Comment by buffy999** [comment]
Oh right!  SS4.1 and Blog 3.1

**Comment by NightJar** [comment]
Hi @buffy999 

Thanks for including screenshots, they're very helpful!
Could you please confirm for me that this is (or is supposed to be) an UploadField?

Your screen shot snippets imply that it is rendering itself as a [FileField](https://github.com/silverstripe/silverstripe-framework/blob/4/templates/SilverStripe/Forms/FileField.ss) as opposed to the JavaScript enabled UploadField which provides the functionality you're describing (uploading on selection, setting the relation, and showing a preview - without reloading the page or submitting the form proper).

The easiest way to tell would be to inspect the source - the classnames (and ID) often reflect the type of field it is. UploadField will have [`entwine-uploadfield uploadfield`](https://github.com/silverstripe/silverstripe-asset-admin/blob/1.0/code/Forms/UploadField.php#L238).
UploadField will also have a complex set of HTML - where FileField will be a simple `<input type="file"`

Can you please also tell us which versions of `assets` and `asset-admin` you have installed? You can use `composer show` to find out if you're unsure.

**Comment by buffy999** [comment]
Hi @NightJar, here's the code from source, looks like it is UploadField code (unless i'm wrong?):

```
<div id="Form_ProfileForm_BlogProfileImage_Holder" class="field entwine-uploadfield uploadfield">
	<label class="left" for="Form_ProfileForm_BlogProfileImage">Blog Profile Image</label>
	<div class="middleColumn">
		<div class="uploadfield-holder">
</div>
<input class="entwine-uploadfield uploadfield" type="file" id="Form_ProfileForm_BlogProfileImage" data-schema="{&quot;name&quot;:&quot;BlogProfileImage&quot;,&quot;id&quot;:&quot;Form_ProfileForm_BlogProfileImage&quot;,&quot;type&quot;:&quot;file&quot;,&quot;schemaType&quot;:&quot;Custom&quot;,&quot;component&quot;:&quot;UploadField&quot;,&quot;holderId&quot;:&quot;Form_ProfileForm_BlogProfileImage_Holder&quot;,&quot;title&quot;:&quot;Blog Profile Image&quot;,&quot;source&quot;:null,&quot;extraClass&quot;:&quot;entwine-uploadfield uploadfield&quot;,&quot;description&quot;:null,&quot;rightTitle&quot;:null,&quot;leftTitle&quot;:null,&quot;readOnly&quot;:false,&quot;disabled&quot;:false,&quot;customValidationMessage&quot;:&quot;&quot;,&quot;validation&quot;:[],&quot;attributes&quot;:[],&quot;autoFocus&quot;:false,&quot;data&quot;:{&quot;createFileEndpoint&quot;:{&quot;url&quot;:&quot;\/profile\/ProfileForm\/field\/BlogProfileImage\/upload&quot;,&quot;method&quot;:&quot;post&quot;,&quot;payloadFormat&quot;:&quot;urlencoded&quot;},&quot;maxFiles&quot;:null,&quot;multi&quot;:false,&quot;parentid&quot;:7,&quot;canUpload&quot;:true,&quot;canAttach&quot;:true}}" data-state="{&quot;name&quot;:&quot;BlogProfileImage&quot;,&quot;id&quot;:&quot;Form_ProfileForm_BlogProfileImage&quot;,&quot;value&quot;:{&quot;Files&quot;:[]},&quot;message&quot;:null,&quot;data&quot;:{&quot;files&quot;:[]}}" 
 />
	</div>
</div>
```

Versions:
Assets - 1.1.0
Asset-admin - 1.1.0

**Comment by NightJar** [comment]
Hi @buffy999, thanks for that. It does indeed appear to (intend to) be an upload field - however has only rendered the output for a basic `<input type="file"` field. It could be that JavaScript is intended to convert this into a fully functional upload filed (drag and drop and preview and all that) - Are you able to see if there are any errors in the dev tools javascript console?

**Comment by buffy999** [comment]
Hi @NightJar, there's no errors in the javascript console. what javascript files that related to the UploadField?

**Comment by buffy999** [comment]
Hi @NightJar, what javascript files that are need for the UploadField to work for the Blog Profile Image field? Pretty keen to get this sorted soon. :)

**Comment by kinglozzer** [comment]
Screenshots look like a front-end form rather than a CMS form, is `UploadField` actually intended to work as a full React interface outside of the CMS?

**Comment by buffy999** [comment]
@kinglozzer, yes it is at the front-end form, not a CMS form. I'm not sure if it should be UploadField or FileField and i have no idea if it is actually intended to work as a full React interface.

From my understanding, in my other websites that has version SS 3.6.1, which it does work for the Blog Profile image using the UploadField, it does show these CSS and Javascript files in the view source:

```
<link rel="stylesheet" type="text/css" href="/framework/thirdparty/jquery-ui-themes/smoothness/jquery-ui.css?m=1517901538" />
<link rel="stylesheet" type="text/css" href="/framework/css/UploadField.css?m=1517901394" />

<script type="text/javascript" src="/framework/thirdparty/jquery/jquery.js?m=1517901476"></script>
<script type="text/javascript" src="/framework/thirdparty/jquery-ui/jquery-ui.js?m=1517901484"></script>
<script type="text/javascript" src="/framework/thirdparty/jquery-entwine/dist/jquery.entwine-dist.js?m=1517901545"></script>
<script type="text/javascript" src="/framework/admin/javascript/ssui.core.js?m=1517901448"></script>
<script type="text/javascript" src="/framework/javascript/i18n.js?m=1517901424"></script>
<script type="text/javascript" src="/framework/javascript/lang/en.js?m=1517901464"></script>
<script type="text/javascript" src="/assets/_combinedfiles/uploadfield.js?m=1517909598"></script>
```

So i'm assuming there's some few files missing in the SS4.1.0 for the UploadField for the Blog Profile Image to work on the front-end form, unless i'm wrong?

**Comment by buffy999** [comment]
@andrewandante, totally understand your pain. 

Do i need to make extension php file for using the FileField to get the Blog Profile Image field to work? or find a fix for this blog module?

**Comment by NightJar** [comment]
>is UploadField actually intended to work as a full React interface outside of the CMS?
Not to my knowledge, no.

Unfortunately @buffy999 this may require you to use a custom solution (ie. some other Javascript dependency) for your front end use-case.

UploadField is intended as a CMS form field - and to try to re-create the same functionality in the front end would require you to import the majority of the `silverstripe/admin` client, along with converting your front end to be React based (if it's not already), and build with `silverstripe/webpack-config`.

Sorry I completely overlooked that you might be trying to use the field outside the CMS.

From the front-end there is also the benefit that uploads are not 'live' - that is your installation won't end up with hundreds of abandoned files (from forms users didn't submit) and you needing to implement a cleanup task with cron and all sorts (UploadField uploads and saves as soon as the user selects a file).

**Comment by chromos33** [comment]
You might want to create your own "FrontEndUploadField" like using dropzone.js and dealing with sending/evaluating/saving the data on your own. Sadly there is no SS4 version of unclecheese/silverstripe-dropzone yet (if at all). Though this means dealing with the way SilverStripe 4 changed the File stuff around for more security (and obscurity.. havn't figured it out yet).

**Comment by robbieaverill** [comment]
I'm going to close this for now since the issue describes using functionality that the blog module doesn't claim to support. Feel free to reopen the issue if you disagree!
