### ISSUE TITLE
The "modified" label is not working

### ISSUE THREAD

**Issue by MarcioBarrientos** [silverstripe/silverstripe-blog#535]
https://github.com/silverstripe/silverstripe-blog/blob/06dbb72432e0004223cf58476a5880cfbfc4149a/src/Forms/GridField/GridFieldBlogPostState.php#L25

This have to be changed to $record->isModifiedOnStage() to call that function and check if the blogpost is modified.

**Comment by robbieaverill** [comment]
Yep you're right - would you like to make a PR for this? There's also one of these in lumberjack I think =)

**Comment by MarcioBarrientos** [comment]
Fix #536

**Comment by robbieaverill** [comment]
Fixed with #536, thanks @MarcioBarrientos
