### ISSUE TITLE
Make Categories and Tags configurable

### ISSUE THREAD

**Issue by chromos33** [silverstripe/silverstripe-blog#537]
Would be nice if it were possible (out of the box) if the used TagFields/GridFields that are used for Categories and Tags were configurable.
For example that you could config the Field that (Blog.php::162) uses to sort BlogTags (and BlogCategores) by another Field instead of static "Title"

I.e. for Compatibility with tractorcow/silverstripe-fluent.

**Comment by robbieaverill** [comment]
You could add an extension to modify the fields, since they're created in a beforeUpdateCMSFields callback they'll always be adjustable by extensions. Are you experiencing a particular problem with fluent in conjunction with this?

I'll triage this as an enhancement for now.

**Comment by chromos33** [comment]
Already did this myself just wanted do open a Ticket to make a suggestion. 
The problem is with how fluent rewrites Queries making Sorting currently breaking everything with it because of MYSQL error something along the lines of using DISTINCT and Sort when the Sort parameter  no longer being in the Select. If Title is to be translated which in most cases it is.

**Comment by robbieaverill** [comment]
Oh OK. Related PR to add sorting capability to fluent: https://github.com/tractorcow/silverstripe-fluent/pull/415

**Comment by robbieaverill** [comment]
I think this is fixed in fluent. Blog fields are extensible so you can adjust them if required. I'm not sure there's anything left over, but feel free to reopen if I've misunderstood.
