### ISSUE TITLE
Problem with Tags when containing "(" etc

### ISSUE THREAD

**Issue by chromos33** [silverstripe/silverstripe-blog#539]
Is this perhaps an oversight or why is in URLSegmentExtension.php line 43 setAllowMultibyte set to true while in Blog.php line 864 (version 2.5) it is missing.

https://github.com/silverstripe/silverstripe-blog/blob/2.5.1/code/model/Blog.php#L851-L871

This works as long as there are no Chars like "(" or ")" in the Tag itself.
As soon as they are there they stop being found by the query because it removes the "(" and the database only knows what rawurlencode replaces them with i.e. %28.

**Comment by dhensby** [comment]
so is the URLSegment not stored as it's filtered value? Is that the problem?

**Comment by chromos33** [comment]
As an Example the Title of the Tag is "Something (ICE)" and the URLSegment is stored as "something-%28ice%29". The problem is that from the URL Parameter "something-(ice)" gets reduced to "something-ice" in the filter function without the filter.setAllowMultibyte(true) which then results in "no results"

**Comment by dhensby** [comment]
Ah, right, I see - so in `URLSegmentExtension` `setAllowMultibyte` is set to true, but there's no "find by URL segment" method added by the extension which means anyone querying by `URLSegment` has to make sure that they add use the same setting.

**Comment by chromos33** [comment]
yes. That's why I currently setAllowMultibyte to true in the getCurrentTags function localy to resolve that problem. I just did not want this fix to vanish whenever we decide to composer update ;)

**Comment by dhensby** [comment]
fix merged and merged up :)
