### ISSUE TITLE
Friendlier URLs for pagination

### ISSUE THREAD

**Issue by feejin** [silverstripe/silverstripe-blog#547]
Instead of /?start=10, something like /page/1 would be preferable. 

Cosmetically, it irks me that it's the only thing on 90% of our sites that uses query strings. 

Commercially it gives me headaches having to defend query strings when clients get SEO people in and pick up on them. Also Wordpress does friendly URLs and I feel SilverStripe should be at least as good as the competition in this respect.

**Comment by robbieaverill** [comment]
This is achievable, but the blog pagination relies heavily on logic in the framework’s PaginatedList which uses a get var for this. I think you’d need to either raise this on the framework or subclass PaginatedList and adjust it to use a route parameter instead.

**Comment by robbieaverill** [comment]
I'm going to close this for now, but I think if you'd like this discussion to continue then you should reopen this issue on https://github.com/silverstripe/silverstripe-framework/issues =) Thanks!
