### ISSUE TITLE
BUG Blog member fields should not be inserted before defaults

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-blog#551]
**Version: SS 4.3.x-dev (CWP 2.1.x-dev)**

![image](https://user-images.githubusercontent.com/5170590/45093997-62d21000-b11a-11e8-8ab9-8ffa35e6b4e8.png)

The fields that blog adds to the Member object should not be added before the important defaults e.g. first name, last name, email, password

## Pull requests

- [x] #552 
- [x] https://github.com/silverstripe/silverstripe-ldap/pull/17

**Comment by robbieaverill** [comment]
Ignore the "username" field, that's coming from LDAP

**Comment by ScopeyNZ** [comment]
PRs merged.
