### ISSUE TITLE
Member section shows blog profile summary as first field

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-blog#564]
This is less important so should be further down (probably with blog profile image).
![image](https://user-images.githubusercontent.com/555033/49548700-707e7800-f94b-11e8-894c-dd03a98e89d8.png)

cc @brynwhyman

**Comment by NightJar** [comment]
After which field would you like it, specifically @clarkepaul ?

**Comment by robbieaverill** [comment]
We already fixed this in blog 3.2.x-dev - which version are you using @clarkepaul? 

Previous issue: https://github.com/silverstripe/silverstripe-blog/issues/551

**Comment by clarkepaul** [comment]
Still present apparently, according to @micmania1

**Comment by clarkepaul** [comment]
Where it used to be @NightJar which I think is with the blog avatar (or other blog stuff).

**Comment by micmania1** [comment]
We're using blog 3.2.1 @robbieaverill

**Comment by ScopeyNZ** [comment]
Looks like it was merged into `master`: https://github.com/silverstripe/silverstripe-blog/commit/fb1b6929a974bbe2b056a58eb5deb811776ad0f3 . That means it'll be released in an eventual 4.0.0 .

I guess we can alter this issue to "Backport fb1b6929a974bbe2b056a58eb5deb811776ad0f3 and tag 3.2.2"?

**Comment by NightJar** [comment]
https://github.com/silverstripe/silverstripe-blog/blob/master/src/Model/BlogMemberExtension.php#L138

**Comment by NightJar** [comment]
Have fun :)
https://github.com/silverstripe/silverstripe-blog/releases/tag/3.2.2
