### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-blog#565]
I have just updated the translations for Dutch on Transifex to include all untranslated strings (of "master-v2"). Shall I send a PR for just that one (to branch 3.0?), or would someone update all of them?

**Comment by robbieaverill** [comment]
Hey @JorisDebonnet, non English translations are synced in occasionally by one of the core team during releases. I'll do an update now for you.

**Comment by robbieaverill** [comment]
Done in 3.0, 3.1 and 3.2 release lines
