### ISSUE TITLE
"Add a Custom Summary" should be uncollapsed by default if it is filled

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-blog#566]
"Add a Custom Summary" is at the bottom of the form, and collapsed by default. That's fine if it is not used, but less fine if it _is_ used. It becomes especially problematic if a translation module such as Fluent is used, because then you'll happily translate the Title and Content, but forget about the Custom Summary. 

After all, it says "*Add* a Custom Summary", so there's no visual indication whatsoever that something is filled in there. 

My suggestion is to simply uncollapse it (onload) if it has any content.

**Comment by NightJar** [comment]
This seems like a reasonable suggestion to me. Would you be willing to grant us another of your fantastic PRs @JorisDebonnet ?

**Comment by JorisDebonnet** [comment]
> This seems like a reasonable suggestion to me. Would you be willing to grant us another of your fantastic PRs @JorisDebonnet ?

Haha... Well, I don't have experience with the front-end (javascript) yet, but guess it could be interesting to dive into some time. So I just might. 

(Although that's the sort of statement that causes delays, of course ...)

**Comment by NightJar** [comment]
Of course :) If you'd like some help you could try giving people a shout in the #frontend or #ss4 channels on the community slack workspace (`silverstripe-users`).

**Comment by feejin** [comment]
Wading in with my 2c, I think it should be uncollpased all the time, and not even in a collapsable field. I have so many support calls from people who miss it, and it also doesn't work well with Fluent as no label means no language marker. Not as if it takes up much space down there.

**Comment by sminnee** [comment]
@ScopeyNZ is this ticket fixes now with #587 merged?

**Comment by ScopeyNZ** [comment]
Yep. Thanks for the reminder.
