### ISSUE TITLE
Please tag a 2.5.3 release with the latest fixes

### ISSUE THREAD

**Issue by xini** [silverstripe/silverstripe-blog#568]
Can you please tag a new 2.5.3 release with the latest fixes on the 2 branch?
Thanks.

**Comment by ScopeyNZ** [comment]
Looks like there's been a bunch of fixes in the 2 branch, but that branch is for the next feature release (2.6.0). Can you let me know which fix specifically is affecting you? I'll have to cherry pick the fixes into the 2.5 branch.

**Comment by robbieaverill** [comment]
I've cherry picked that commit back into the 2.5 release line and tagged 2.5.3 =)

**Comment by xini** [comment]
Great, thanks!
