### ISSUE TITLE
$canEdit does not work in templates

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-blog#576]
I recently started using `$canEdit` in templates to display an easy link to the CMS, for people that are logged in and can in fact edit the page. I used to use a much longer construct, and was happy to find that there is such a nice and short way to do this check.

This works fine for all pages, except `BlogPost`s (and derived classes). I know this module has quite some extensions on access levels and stuff, so I guess it broke the plain `$canEdit` calls. Specifically, it says I'm trying to call `DataExtension::canEdit` with 0 arguments while there should be 1.

**Comment by robbieaverill** [comment]
If I'm reading this correctly, BlogPost has a `canEdit()` with a nullable member argument, whereas `DataExtension` is not nullable. Therefore if you're using BlogPost on its own (with no extensions) then this would work correctly, but since blog ships with extensions out of the box: `BlogPostNotifications` (aside from the fact that extensions are an important construct in SilverStripe), this fails when not providing an argument.

If this is correct, I think this is probably a framework architecture issue rather than a blog specific problem. You could try `$canEdit($CurrentMember)` in templates, which should provide the current user (or null) as the argument in theory. Would you mind giving that a go?

**Comment by JorisDebonnet** [comment]
I had a similar idea, so I actually already tried `$canEdit($CurrentMember)`, but that doesn't work for a reason I understand even less :) It's not limited to Blog though, so I figured I might be using the template syntax wrong or something?... but when I use the code `<% if $canEdit($CurrentMember) %>`, it says (on any page): 

`[Emergency] Uncaught BadMethodCallException: Object->__call(): the method 'forTemplate' does not exist on 'SilverStripe\Security\Member'`

Maybe it's new in SS4 that it first tries to parse all the variables and only then puts them into the template? I also tried `<% if $canEdit(\SilverStripe\Security::getCurrentUser()) %>`, but constructs like that just make it exit the template right there and move on (without an error), resulting in crazy layouts because html markup is broken.

So anyway, I ended up making a custom method `Page::showEdit()` for this, but of course it would be nicer if `$canEdit` just worked out of the box, as it normally does.

**Comment by NightJar** [comment]
I wonder if `$canEdit($CurrentMember)->exists()` (possibly with an `&&` check first) would work 🤔

**Comment by JorisDebonnet** [comment]
> I wonder if `$canEdit($CurrentMember)->exists()` (possibly with an `&&` check first) would work 🤔

I can't get that to work in any case: `<% if $CurrentMember->exists() && $canEdit($CurrentMember) %>` and `<% if $canEdit($CurrentMember)->exists() %>` both give the same issue as when I try the `Security::getCurrentUser()` method, i.e. no error, but it just breaks out of the template at that point. Strange issue actually, there's no error in silverstripe.log either.

**Comment by NightJar** [comment]
Sorry @JorisDebonnet - the arrow (`->`) should be a dot (`.`) in the template!

**Comment by JorisDebonnet** [comment]
Oh, right -- then I don't get the fatal error thing anymore, but `<% if $CurrentMember.exists() && $canEdit($CurrentMember) %>` (or with `Exists`) still complains about forTemplate being used on Member. `$canEdit($CurrentMember).exists()` as well, as I'd expect because it resolves that first before calling Exists on it.

**Comment by NightJar** [comment]
Interesting. I mostly expected `$canEdit($CurrentMember).Exists` to work, as nothing should be returned until the entire statement has been processed. Exists of course should return a boolean, not a Member object, perhaps that's a poor assumption though (in that an object is still "truthy").

**Comment by robbieaverill** [comment]
I don't think there's anything we can do about this in the blog module (please correct me if I'm wrong), so I'm going to close it for now. In the long run we may need to make the argument nullable in DataExtension, but doing that would be a major semver change so wouldn't be available until SilverStripe 5. If you'd like to raise an issue on silverstripe/framework for this, you can reference this issue. Thanks!
