### ISSUE TITLE
Plz add $request param to BlogController::index() at the version 3.2.4

### ISSUE THREAD

**Issue by a2nt** [silverstripe/silverstripe-blog#579]
The other modules require stable version of silverstipe/blog module for example blocks extension and I'm tired to change manually 
BlogController::index() to BlogController::index(SilverStripe\Control\HTTPRequest $request)

**Comment by NightJar** [comment]
Hi @a2nt - can you please describe the issue you're seeing with more detail?
Are you also saying that you've tested a fix, and it works? If so, how would you feel about creating a pull request against the `3.2` branch to patch this in the next release?

**Comment by a2nt** [comment]
Well that's easy

PageController::index(SilverStripe\Control\HTTPRequest $request)
And BlogController extends PageContoller and it makes a notice

Yes I have tested it among different websites and it works ok. You have fixed this issue at the master branch already.

**Comment by ScopeyNZ** [comment]
I agree that not having it was an oversight. Unfortunately as updating it is a breaking API change it has to go in the next major - hence it only exists in `master` (and the invalid 3.2.2 tag). 

There's not really anything we can do here without backporting a breaking change into a minor release.

I think 4.x-dev is pretty stable right now - not sure when we're likely to tag it though.
