### ISSUE TITLE
Remove widgets

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-blog#589]
There's a whole bunch of "widgets" which is our outdated way of doing blocks: https://github.com/silverstripe/silverstripe-blog/tree/master/src/Widgets

We don't have an equivalent replacement for this in elemental. Widgets are designed for a "sidebar" which should show up on every blog post. You can do this via https://github.com/dnadesign/silverstripe-elemental-virtual, but that's creating a lot of duplicate blocks, and needs to be configured again on every new blog post.

The concept of a configurable "sidebar" is kind of outdated. I think the baseline is giving devs the ability to add includes to their template for that functionality - since in most cases, they'll have to adjust the template anyway - take the silverstripe.org/blog for example, it has tags and categories.

In terms of widget types:
- Archive: Kind of useful for month based browsing on large blogs
- Categories and Tags: Should be a template addition? I don't think there's much value in a user-configurable limit and sort order
- Featured and Recent Posts: I think that's actually a more generic use case for a block module that just lists pages in a parent?
- Tag Cloud: I think we should drop support altogether, that can be a third party addition if anyone wants to recreate it...

## Acceptance criteria
- [x] All code pertaining to widgets is removed in CMS 6

## CMS 5 PRs
- https://github.com/silverstripe/silverstripe-blog/pull/779
- https://github.com/silverstripe/developer-docs/pull/567

## CMS 6 PRs
- https://github.com/silverstripe/silverstripe-blog/pull/778
- https://github.com/silverstripe/developer-docs/pull/562
- https://github.com/silverstripe/recipe-blog/pull/58

**Comment by GuySartorelli** [comment]
This card is fairly old now, and I honestly doubt anyone is actually using the widgets. Most likely anyone who wants that functionality has already recreated it with elemental blocks. Widgets aren't even commercially supported in CMS 5, and we're gearing up for a CMS 6 release in just over half a year.

We should remove all of the widgets and call it a day.

**Comment by GuySartorelli** [comment]
CMS 5 PRs merged. Reassigning to Steve for CMS 6 PRs

**Comment by GuySartorelli** [comment]
PRs merged
