### ISSUE TITLE
BUG New tags for blog post never get assigned to parent blog, result in orphaned duplicates

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-blog#593]
Use case: I have a blog post A, in a Blog X

If I edit that posts and add a new tag, it gets created in the DB, but with a BlogID = 0.

If I now navigate to another blog post B in Blog X and edit tags, and search for that new tag, it never appears in the list. I create the same tag.

As a result, I end up with two tags with duplicate content in the DB, both with BlogID = 0.

Given that you can determine the tags in a blog by joining on blog posts with the ParentID of that blog, it seems hugely unnecessary to even require that tags be bound to a single (or orphaned) blog. It also means you have a huge number of duplicates (a version for a tag for each blog, plus many orphaned duplicates of that tag).

When assigning tags to a post, you also have no visibility about which tags are "safely" assigned to the parent blog, or whether they simply global tags.

My recommendation is this:
 - Drop has_one from both BlogTag and BlogCategory to Blog.
 - Re-implement the `Tags` and `Categories` methods on blog post to join against child posts instead.
- Blog Tags / Categories gridfields become read-only views.
- Add build task for resolving / merging duplicate tags and categories

**Comment by tractorcow** [comment]
WIP at https://github.com/silverstripe/silverstripe-blog/pull/594

**Comment by tractorcow** [comment]
I'm writing up the dedupe task now.

**Comment by tractorcow** [comment]
https://github.com/silverstripe/silverstripe-blog/pull/594 is fixed and working.

**Comment by robbieaverill** [comment]
Nice work @tractorcow, thanks again for your contribution
