### ISSUE TITLE
BlogHolder doesn't save the correct Member ID as the owner

### ISSUE THREAD

**Issue by cam-findlay** [silverstripe/silverstripe-blog#61]
The following form element that sets up the Owner of the blogholder messes up the ID number of the Member object that is then saved in the BlogHolder object OwnerID.

In line 44 of BlogHolder.php

```php
$fields->addFieldToTab('Root.Main', new DropdownField('OwnerID', 'Blog owner', array_merge(array('' => "(None)"), $blogOwners->map('ID', 'Name')->toArray())), "Content");
```

it is the array_merge that stuffs it up... is there a better way to do the same thing while retaining the correctly mapped Member->ID's?

**Comment by assertchris** [comment]
@cam-findlay is this still an issue, after the rewrite?

**Comment by tractorcow** [comment]
I think we should close it if it hasn't had activity after 3 years.

**Comment by camfindlay** [comment]
I'll look at installing the blog rewrite this weekend and see if this is still an issue. May not be due to the adoption of @micmania1 's work in blog. Will report back.
