### ISSUE TITLE
Cannot loop over Children in Menu when BlogPost table is renamed

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-blog#628]
related to #620 

There is a hardcoded reference to table "BlogPost" in `SilverStripe\Blog\Model\BlogFilter::stageChildren()` that breaks looping over Children (e.g. in navigation) when the table is renamed.

PR will follow.

## PRs
- https://github.com/silverstripe/silverstripe-blog/pull/629

**Comment by GuySartorelli** [comment]
PR merged
