### ISSUE TITLE
Blog RSS Feed importing error

### ISSUE THREAD

**Issue by OpticBlaze** [silverstripe/silverstripe-blog#66]
Hi there, when i try to use the RSS Widget that allows you to import another RSS Feed i get the following error message:

[Deprecated] Assigning the return value of new by reference is deprecated
GET /customers/diveschoolcapetown/blog/?url=/customers/diveschoolcapetown/blog

Line 651 in /usr/www/users/zzzz/customers/diveschoolcapetown/framework/thirdparty/simplepie/simplepie.inc
Source

642 	 * @access public
643 	 * @since 1.0 Preview Release
644 	 * @param string $feed_url This is the URL you want to parse.
645 	 * @param string $cache_location This is where you want the cache to be stored.
646 	 * @param int $cache_duration This is the number of seconds that you want to store the cache file for.
647 	 */
648 	function SimplePie($feed_url = null, $cache_location = null, $cache_duration = null)
649 	{
650 		// Other objects, instances created here so we can set options on them
651 		$this->sanitize =& new SimplePie_Sanitize;
652 
653 		// Set options if they're passed to the constructor
654 		if ($cache_location !== null)
655 		{
656 			$this->set_cache_location($cache_location);
657 		}

Trace

    RSSWidget::getFeedItems
    RSSWidget.php:69
    RSSWidget->getFeedItems()
    ViewableData.php:106
    ViewableData->__get(FeedItems)
    ViewableData.php:110
    ViewableData->__get(FeedItems)
    ViewableData.php:368
    ViewableData->obj(FeedItems,,1,,)
    SSViewer.php:57
    SSViewer_Scope->getObj(FeedItems,,1,,)
    SSViewer.php:429
    SSViewer_DataPresenter->getObj(FeedItems,,1,,)
    SSViewer.php:73
    SSViewer_Scope->obj(FeedItems,,1)
    .cache.themes.intoblue_blog.templates.RSSWidget.ss:5
    include(/tmp/silverstripe-cache-usr-www-users-opticb-customers-diveschoolcapetown/.cache.themes.intoblue_blog.templates.RSSWidget.ss)
    SSViewer.php:778
    SSViewer->includeGeneratedTemplate(/tmp/silverstripe-cache-usr-www-users-opticb-customers-diveschoolcapetown/.cache.themes.intoblue_blog.templates.RSSWidget.ss,Widget_Controller,,Array)
    SSViewer.php:844
    SSViewer->process(Widget_Controller,)
    ViewableData.php:335
    ViewableData->renderWith(Array)
    Widget.php:295
    Widget_Controller->Content()
    ViewableData.php:366
    ViewableData->obj(Content,,,1)
    ViewableData.php:443
    ViewableData->XML_val(Content,,1)
    call_user_func_array(Array,Array)
    SSViewer.php:128
    SSViewer_Scope->__call(XML_val,Array)
    SSViewer.php:459
    SSViewer_DataPresenter->__call(XML_val,Array)
    .cache.widgets.templates.WidgetHolder.ss:25
    SSViewer_DataPresenter->XML_val(Content,,1)
    .cache.widgets.templates.WidgetHolder.ss:25
    include(/tmp/silverstripe-cache-usr-www-users-opticb-customers-diveschoolcapetown/.cache.widgets.templates.WidgetHolder.ss)
    SSViewer.php:778
    SSViewer->includeGeneratedTemplate(/tmp/silverstripe-cache-usr-www-users-opticb-customers-diveschoolcapetown/.cache.widgets.templates.WidgetHolder.ss,Widget_Controller,,Array)
    SSViewer.php:844
    SSViewer->process(Widget_Controller,)
    ViewableData.php:335
    ViewableData->renderWith(WidgetHolder)
    Widget.php:305
    Widget_Controller->WidgetHolder()
    ViewableData.php:366
    ViewableData->obj(WidgetHolder,,,1)
    ViewableData.php:443
    ViewableData->XML_val(WidgetHolder,,1)
    call_user_func_array(Array,Array)
    SSViewer.php:128
    SSViewer_Scope->__call(XML_val,Array)
    SSViewer.php:459
    SSViewer_DataPresenter->__call(XML_val,Array)
    .cache.widgets.templates.WidgetArea.ss:6
    SSViewer_DataPresenter->XML_val(WidgetHolder,,1)
    .cache.widgets.templates.WidgetArea.ss:6
    include(/tmp/silverstripe-cache-usr-www-users-opticb-customers-diveschoolcapetown/.cache.widgets.templates.WidgetArea.ss)
    SSViewer.php:778
    SSViewer->includeGeneratedTemplate(/tmp/silverstripe-cache-usr-www-users-opticb-customers-diveschoolcapetown/.cache.widgets.templates.WidgetArea.ss,WidgetArea,,Array)
    SSViewer.php:844
    SSViewer->process(WidgetArea,)
    ViewableData.php:335
    ViewableData->renderWith(WidgetArea)
    WidgetArea.php:94
    WidgetArea->forTemplate()
    ViewableData.php:444
    ViewableData->XML_val(SideBar,,1)
    call_user_func_array(Array,Array)
    SSViewer.php:128
    SSViewer_Scope->__call(XML_val,Array)
    SSViewer.php:459
    SSViewer_DataPresenter->__call(XML_val,Array)
    .cache.themes.intoblue_blog.templates.Includes.BlogSideBar.ss:6
    SSViewer_DataPresenter->XML_val(SideBar,,1)
    .cache.themes.intoblue_blog.templates.Includes.BlogSideBar.ss:6
    include(/tmp/silverstripe-cache-usr-www-users-opticb-customers-diveschoolcapetown/.cache.themes.intoblue_blog.templates.Includes.BlogSideBar.ss)
    SSViewer.php:778
    SSViewer->includeGeneratedTemplate(/tmp/silverstripe-cache-usr-www-users-opticb-customers-diveschoolcapetown/.cache.themes.intoblue_blog.templates.Includes.BlogSideBar.ss,BlogHolder_Controller,Array,Array)
    SSViewer.php:844
    SSViewer->process(BlogHolder_Controller,Array)
    SSViewer.php:872
    SSViewer::execute_template(BlogSideBar,BlogHolder_Controller,Array)
    .cache.themes.intoblue_blog.templates.Layout.BlogHolder.ss:2
    include(/tmp/silverstripe-cache-usr-www-users-opticb-customers-diveschoolcapetown/.cache.themes.intoblue_blog.templates.Layout.BlogHolder.ss)
    SSViewer.php:778
    SSViewer->includeGeneratedTemplate(/tmp/silverstripe-cache-usr-www-users-opticb-customers-diveschoolcapetown/.cache.themes.intoblue_blog.templates.Layout.BlogHolder.ss,BlogHolder_Controller,,Array)
    SSViewer.php:844
    SSViewer->process(BlogHolder_Controller,)
    SSViewer.php:840
    SSViewer->process(BlogHolder_Controller)
    Controller.php:204
    Controller->handleAction(SS_HTTPRequest)
    RequestHandler.php:168
    RequestHandler->handleRequest(SS_HTTPRequest,DataModel)
    Controller.php:149
    Controller->handleRequest(SS_HTTPRequest,DataModel)
    ContentController.php:197
    ContentController->handleRequest(SS_HTTPRequest,DataModel)
    ModelAsController.php:68
    ModelAsController->handleRequest(SS_HTTPRequest,DataModel)
    Director.php:283
    Director::handleRequest(SS_HTTPRequest,Session,DataModel)
    Director.php:112
    Director::direct(/blog,DataModel)
    main.php:126

**Comment by micmania1** [comment]
No input since June 2013 and is on an old version of blog. Feel free to fix and submit a PR if this affects you, but i'm closing for now.
