### ISSUE TITLE
invalid rss blog feed

### ISSUE THREAD

**Issue by surfjedi** [silverstripe/silverstripe-blog#68]
When trying to parse the SS3 blog's feed( ex: mysite.com/blog/rss) I get parse errors just before the closing </channel> tag.  

XML error: Mismatched tag at line 59, column 12

here is a screen shot of w3c rss feed validator showing the issue.

https://www.evernote.com/shard/s187/sh/1ad3ae45-daee-44b8-99fd-ba4a6f3d2780/1456fa3e991a1f85b1280333b088a884

It appears to be something in the rss template, but I cant seem to find the .ss file or feed producing code in the blog module.

Im tyring to parse this feed in an iOS app and any errors tho it out.

**Comment by assertchris** [comment]
@surfjedi this doesn't appear to be a problem in `dev-master`. Do you think we can close this?

**Comment by surfjedi** [comment]
Sure this was from Jan 2013 too I'm sure things have changed
