### ISSUE TITLE
Sections Categories and Tags don't have input fields

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-blog#696]
### Description
In Post Options tab on Blog Post Page in section Categories and Tags input fields are absent.

![ss-blog.png](https://images.zenhubusercontent.com/6240ee9a7a0aac6d45cfd39d/bfd21092-2669-49fe-a84d-f3f59b28f0ca)

## Steps to reproduce issue
- I go to "/admin/pages"
- I follow "New Blog"
- I click the "Blog Posts" CMS tab
- I press the "Add new Blog Post" button
- I click the "Post Options" CMS tab
- **I add "My Category" to the "Categories" tag field** _(input field is absent)_
- **I add "My Tags" to the "Tags" tag field**  _(input field is absent)_ 

### PR's

**Comment by GuySartorelli** [comment]
This is probably just because we haven't updated the JS stack for kitchen sink yet. I'll reference this issue in https://github.com/silverstripeltd/product-issues/issues/644

**Comment by GuySartorelli** [comment]
Yup, I was correct, this will be fixed as part of the above-mentioned issue. Closing.
