### ISSUE TITLE
"Edit this post" link (front-end) does not work

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-blog#70]
"Edit this post" link (front-end) does not work when using side-by-side because of page refresh (editing in the front-end is still possible when side-by-side is not being used).

This link is only visible when logged in as admin so maybe it can be hidden in side-by-side or I would think the preferred option would be that it works in side-by-side as well.

**Comment by assertchris** [comment]
Front-end editing is no longer supported. cc @tractorcow @sminnee
