### ISSUE TITLE
No need to show "Comments" link when comments are not installed

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-blog#72]
There is no need to show the "Comments" link when comments are not installed. This is not really a bug fix but rather an usability enhancement. Not sure is Disqus works with the blog module but would assume it can.
https://www.evernote.com/shard/s24/sh/b246b134-b6e1-406c-bb0c-3d11346208fa/a5db38953523b0972457be04987da5f7

**Comment by assertchris** [comment]
This doesn't appear to be a problem anymore.
