### ISSUE TITLE
TODO: BlogPost::getCMSFields(). Reimplement the sidebar

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-blog#729]
## Description
BlogPost::getCMSFields(). Reimplement the sidebar. There are some commented out lines of code, that implements BlogAdminSidebar. We need to examine the problem and, if it's necessary, add BlogAdminSidebar back. 
See https://github.com/silverstripe/silverstripe-blog/blob/fe638a0ccb9599a3ac6f810093d85e7793777102/src/Model/BlogPost.php#L337

**Comment by GuySartorelli** [comment]
I'm going to close this as "won't do" - we've discussed internally that we probably want to implement a better version of this module anyway, and in the meantime nobody has been clamoring for this to be implemented.
