### ISSUE TITLE
empty admin panel on blogholders.

### ISSUE THREAD

**Issue by tryadelion** [silverstripe/silverstripe-blog#85]
installed silverstripe  some days ago.
installed blog module today, worked fine except for comments.
to make comments work, installed the widgets module.
EVERY TIME  i try to edit a blogholder page, and only a blogholder page, the right side of the admin control panel turns out grey, empty, and everywere i tyr ot enter appears the same. have to go out of admin site and go back to make it work for other sites, yet i'm unable to edit a blogholder page. creating a new blogholder gives the same error.

**Comment by assertchris** [comment]
@tryadelion are you still having this issue?

**Comment by tryadelion** [comment]
sorry, i no longer take part in that project. but thank you.

2015-04-14 9:15 GMT+02:00 Christopher Pitt <notifications@github.com>:

**Comment by assertchris** [comment]
Sorry to see you go. :(
